window["msgs"] = {
	"lsFailed": "Failed to get authorization of local storage.",
	"loading": "Loading......",
	"unkDrive": "Unknown drive type.",
	"noPwd": "No password nor key file is specified.",
	"diffPwd": "Reinputed password is not same.",
	"noRoot": "Root folder is not specified.",
	"pwdError": "Password or key file is not correct.",
	"noFldName": "Folder name is not specified.",
	"flDone": "New folder is created.",
	"noFiles": "File to upload is not specified.",
	"noChecks": "Nothing is checked.",
	"noDownFolder": "Download folder is not supported yet.",
	"noNewName": "New name can NOT be blank.",
	"renDone": "Name is changed.",
	"moving": "Moving......",
	"moveDone": "File(s) have been moved.",
	"delConfirm": "Do you really want to delete?",
	"deleting": "Deleting......",
	"delDone": "File(s) have been deleted.",
	"updQueue": "Upload Queue",
	"updCanceled": "Upload has been canceled.",
	"upDone": "Upload is done.",
	"downQueue": "Download Queue",
	"downCanceled": "Download has been canceled.",
	"downDone": "Download is done.",
	"waiting": "Waiting",
	"gtlFDetail": "File Detail",
	"gtlMoveto": "Move to a folder",
	"spanSet": "Settings",
	"lblDrive": "Online Storage: ",
	"btnLogout": "Logout",
	"btnCancel": "Cancel",
	"btnOk": "OK",
	"btnSet": "Settings",
	"lblSkipLogin": "Keep login status",
	"spanRootNotice": "Choose a root folder for encrypted files.",
	"lblRoot": "Folder: ",
	"lblEncryFname": "Encrypt file's name and folder's name.",
	"lblKeyPwd": "Password: ",
	"lblKeyPwdRe": "Reinput: ",
	"lblKeyFile": "Key file: ",
	"spanMoreKey": "Add another key.",
	"spanClearKey": "Clear key files.",
	"spanKeyNotice": "Key file will only be read in the first 1024 bytes.",
	"spanPwdNotice": "Don't forget your password and key file, or you will be unable to decrypt your files forever.",
	"lblSaveKey": "Save my key's information.",
	"spanConfNotice": "A configuration file named of '{0}' will be saved in your drive's root directory.\nDo NOT delete it or you will be unable to decrypt your files forever.",
	"quotaInfo": "Free Space: {0}",
	"spanName": "Name",
	"thSize": "Size",
	"thTms": "Timestamp",
	"btnDownfs": "Download Files",
	"btnMovefs": "Move Files",
	"btnDelfs": "Delete Files",
	"btnNewFldr": "New Folder",
	"btnUpfs": "Upload Files",
	"btnUpfld": "Upload Folder",
	"btnDownload": "Download",
	"btnRename": "Rename",
	"btnMove": "Move...",
	"btnDelete": "Delete",
	"lnkTos": "Terms of Service & Privacy Policy",
};
