window["msgs"] = {
	"menuGeneral": "General Settings",
	"menuDrive": "Drive Settings",
	"menuHistory": "Recent Viewed",
	"spanGeneral": "General Settings",
	"lblDrive": "Online Storage: ",
	"lblOwnSecret": "Use my own client id and secret",
	"lblClientId": "Client ID",
	"lblClientSecret": "Client Secret",
	"lblSkipLogin": "Keep login status",
	"lblRelay": "Relay url: ",
	"btnLogout": "Logout",
	"btnCancel": "Cancel",
	"btnOk": "OK",
	"spanDrive": "Drive Settings",
	"lblConfNotice": "A configuration file named of '{0}' will be saved in your drive's root directory. Do NOT delete it or you will be unable to decrypt your files forever.",
	"lblReadTos": "Please read the ",
	"lblReadTos2": ".",
	"lblAgreeTos": "I agree the Terms of Service and Privacy Policy.",
	"lblRootNotice": "Input a root folder for encrypted files.",
	"lblRoot": "Folder: ",
	"spanAddRoot": "Add a new root folder.",
	"spanDeleteRoot": "Delete the root folder.",
	"lblEncryFname": "Encrypt file's name and folder's name.",
	"lblKeyPwd": "Password: ",
	"lblKeyPwdRe": "Reinput: ",
	"lblKeyFile": "Key file: ",
	"spanMoreKey": "Add another key.",
	"spanClearKey": "Clear key files.",
	"lblKeyNotice": "Key file will only be read in the first 1024 bytes.",
	"lblPwdNotice": "Don't forget your password and key file, or you will be unable to decrypt your files forever.",
	"lblSaveKey": "Save my key's information.",
	"btnDropDb": "Drop local datas",
	"btnUnregSw": "Uninstall sw",
	"spanNew": "New...",
	"spanUpload": "Upload...",
	"spanSelFldr": "Select a folder...",
	"lblUpfs": "Files",
	"lblUpfld": "Folder",
	"lblNewFldr": "Folder",
	"lblFldrInto": "Enter into the new folder.",
	"menuUpload": "Upload",
	"menuMovefs": "Move Files",
	"menuNewFldr": "New Folder",
	"menuDownfs": "Download Files",
	"menuDelfs": "Delete Files",
	"menuDownload": "Download",
	"menuRename": "Rename",
	"menuMove": "Move",
	"menuDelete": "Delete",
	"spanName": "Name",
	"spanSize": "Size",
	"spanTms": "Timestamp",

	"quotaInfo": "Free Space: {0}",
	"quotaInfoU": "Used Space: {0}",
	"cantView": "Sorry, we can't show this file to you.",
	"spanTask": "Download And Upload Queue",
	"elTime": "Elapsed Time:",
	"esTime": "Estimated left:",
	"waiting": "Waiting",
	"avspeed": "Average Speed: {0}/s",
	"lblNewFldr": "Folder",
	"noFiles": "File to upload is not specified.",

	"spanHistory": "Recent Played Video",
	"cantPlayRecent": "Can NOT play the recent viewed file, because it is not in this root folder.",

	"noAgreeTos": "Before using this service, you must agree the Terms of Service and Privacy Policy.",
	"noClientIdS": "Own client id and secret must be specified, or uncheck the using own client id and secret.",
	"lsFailed": "Failed to get authorization of local storage.",
	"loading": "Loading......",
	"unkDrive": "Unknown drive type.",
	"loginFailed": "Failed to signin the drive due to the error below. Please try again.\n\n{0}",
	"noPwd": "No password nor key file is specified.",
	"diffPwd": "Reinputed password is not same.",
	"noRoot": "Root folder is not specified.",
	"dupRoot": "New root folder is already exists.",
	"pwdError": "Password or key file is not correct.",
	"noFldName": "Folder name is not specified.",
	"flDone": "New folder is created.",
	"noChecks": "Nothing is selected.",
	"noDownFolder": "Download folder is not supported yet.",
	"noNewName": "New name can NOT be blank.",
	"renDone": "Name is changed.",
	"moving": "Moving......",
	"moveDone": "File(s) have been moved.",
	"dropConfirm": "Are you sure you really want to drop lacal datas?",
	"unswConfirm": "Do you want to uninstall service worker?\nIt will be installed again the next time you access this website.",
	"delConfirm": "Do you really want to delete?",
	"deleting": "Deleting......",
	"delDone": "File(s) have been deleted.",
	"delrootDone": "Root directory have been deleted.",
	"updCanceled": "Upload has been canceled.",
	"upDone": "Upload is done.",
	"downCanceled": "Download has been canceled.",
	"downDone": "Download is done.",
	"gtlFDetail": "File Detail",
	"gtlMoveto": "Move to a folder",
	"btnSet": "Settings",
	"spanDelHistory": "Delete this history.",
	"spanPlayNext": "Play the next video.",
	"lnkTos": "Terms of Service & Privacy Policy",
};
