var h;function aa(b){function c(d){return b.next(d)}function a(d){return b.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(c,a).then(f,e)}f(b.next())})}function l(b){return aa(b())};const ba={en:"English",ja:"日本語"},ca={bmp:"image/bmp",gif:"image/gif",jpe:"image/jpeg",jpeg:"image/jpeg",jpg:"image/jpeg",png:"image/png",webp:"image/webp"},da={aac:"audio/aac",mp3:"audio/mpeg",wav:"audio/wav"},ea={avi:"video/x-msvideo",mp4:"video/mp4",mpeg:"video/mpeg"};var fa={"ァ":"あ","ィ":"い","ゥ":"う","ェ":"え","ォ":"お","ぁ":"あ","ぃ":"い","ぅ":"う","ぇ":"え","ぉ":"お","ア":"あ","イ":"い","ウ":"う","エ":"え","オ":"お","カ":"か","キ":"き","ク":"く","ケ":"け","コ":"こ","ガ":"か","ギ":"き","グ":"く","ゲ":"け","ゴ":"こ","が":"か","ぎ":"き","ぐ":"く","げ":"け","ご":"こ","サ":"さ","シ":"し","ス":"す","セ":"せ","ソ":"そ","ザ":"さ","ジ":"し","ズ":"す","ゼ":"せ","ゾ":"そ","ざ":"さ","じ":"し","ず":"す","ぜ":"せ","ぞ":"そ","タ":"た","チ":"ち","ツ":"つ","テ":"て","ト":"と","ダ":"た","ヂ":"ち","ヅ":"つ","デ":"て","ド":"と","だ":"た","ぢ":"ち","づ":"つ","で":"て","ど":"と","ッ":"つ","ャ":"や",
"ュ":"ゆ","ョ":"よ","っ":"つ","ゃ":"や","ゅ":"ゆ","ょ":"よ","ナ":"な","ニ":"に","ヌ":"ぬ","ネ":"ね","ノ":"の","ハ":"は","ヒ":"ひ","フ":"ふ","ヘ":"へ","ホ":"ほ","バ":"は","ビ":"ひ","ブ":"ふ","ベ":"へ","ボ":"ほ","パ":"は","ピ":"ひ","プ":"ふ","ペ":"へ","ポ":"ほ","ば":"は","び":"ひ","ぶ":"ふ","べ":"へ","ぼ":"ほ","ぱ":"は","ぴ":"ひ","ぷ":"ふ","ぺ":"へ","ぽ":"ほ","マ":"ま","ミ":"み","ム":"む","メ":"め","モ":"も","ヤ":"や","ユ":"ゆ","ヨ":"よ","ラ":"ら","リ":"り","ル":"る","レ":"れ","ロ":"ろ","ワ":"わ","ヲ":"を","ン":"ん","ヴ":"う","ヷ":"わ","ヺ":"を","ｧ":"あ","ｨ":"い","ｩ":"う","ｪ":"え","ｫ":"お","ｯ":"つ","ｬ":"や","ｭ":"ゆ",
"ｮ":"よ","ｱ":"あ","ｲ":"い","ｳ":"う","ｴ":"え","ｵ":"お","ｶ":"か","ｷ":"き","ｸ":"く","ｹ":"け","ｺ":"こ","ｻ":"さ","ｼ":"し","ｽ":"す","ｾ":"せ","ｿ":"そ","ﾀ":"た","ﾁ":"ち","ﾂ":"つ","ﾃ":"て","ﾄ":"と","ﾅ":"な","ﾆ":"に","ﾇ":"ぬ","ﾈ":"ね","ﾉ":"の","ﾊ":"は","ﾋ":"ひ","ﾌ":"ふ","ﾍ":"へ","ﾎ":"ほ","ﾏ":"ま","ﾐ":"み","ﾑ":"む","ﾒ":"め","ﾓ":"も","ﾔ":"や","ﾕ":"ゆ","ﾖ":"よ","ﾗ":"ら","ﾘ":"り","ﾙ":"る","ﾚ":"れ","ﾛ":"ろ","ﾜ":"わ","ｦ":"を","ﾝ":"ん"},ha="ﾞ・），ﾟ･（。、ー「」｡､ｰ｢｣".split("");function ia(b,c){var a="",d="";if(c){d=c.indexOf(".");0<=d&&(a=c.substring(0,d).toUpperCase(),c=c.slice(d+1));switch(c.toLowerCase()){case "id":c="#";break;case "class":c="."}d=b}else c=b.charAt(0),"#"==c||"."==c?d=b.slice(1):(c="",a=b.toUpperCase());return{ga:a,o:c,pa:d}}function ja(b,c){return"#"==c.o?b.id==c.pa:"."==c.o?b.classList.contains(c.pa):c.o?b.getAttribute(c.o)==c.pa:!0}
function q(b,c,a){var d=[],e=document;c&&("string"==typeof c?(c=q(c),0<c.length&&(e=c[0])):e=c);a=ia(b,a);if(!a.ga)if("#"==a.o)d.push(document.getElementById(a.pa));else if("."==a.o)for(c=e.getElementsByClassName(a.pa),b=0;b<c.length;b++)d.push(c[b]);else a.ga="*";if(a.ga)for(e=e.getElementsByTagName(a.ga.toLowerCase()),b=0;b<e.length;b++)ja(e[b],a)&&d.push(e[b]);return d}
function r(b,c,a){var d=null;b?"string"==typeof b?(b=q(b,c,a),0<b.length&&(d=b[0])):b instanceof Event?d=b.currentTarget||b.srcElement||b.target:d=b:d=window.event.currentTarget||window.event.srcElement||window.event.target;return d}function t(b,c,a,d){var e=null;c?"string"==typeof c?e=r(c):e=c:e=r();d&&(e=e.parentElement);for(b=ia(b,a);e&&(e.tagName!=b.ga&&b.ga||!ja(e,b));)e=e.parentElement;return e}function ka(b){return!!(b.offsetWidth||b.offsetHeight||b.getClientRects().length)}
function u(b){(b=r(b))&&b.style.display&&(b.style.display="")}function v(b){if(b=r(b))b.style.display="none"}function w(b,c){if((b=b.nextElementSibling)&&c)switch(c.charAt(0)){case "#":for(c=c.slice(1);b&&b.id!=c;)b=b.nextElementSibling;break;default:for(c=c.toUpperCase();b&&b.tagName!=c;)b=b.nextElementSibling}return b}
function la(b,c,a){if((b=a?b.lastElementChild:b.previousElementSibling)&&c)switch(c.charAt(0)){case "#":for(c=c.slice(1);b&&b.id!=c;)b=b.previousElementSibling;break;default:for(c=c.toUpperCase();b&&b.tagName!=c;)b=b.previousElementSibling}return b}function x(b,c){return parseInt(b.getAttribute(c),10)}
function ma(b,c,a){if(window.navigator.msSaveBlob)window.navigator.msSaveBlob(b,c);else if(a)a.download=c,a.href=window.URL.createObjectURL(b),a.click();else throw Error("Element for download is not specified.");}function na(b){if(!b)return null;var c=b.charAt(0);if("?"==c||"#"==c)b=b.substring(1);var a={};b.split("&").forEach(function(d){var e=d.indexOf("=");0>e?a[decodeURIComponent(d)]="":a[decodeURIComponent(d.substring(0,e))]=decodeURIComponent(d.substring(e+1))});return a}
function oa(){var b=na(window.location.search),c=na(window.location.hash);c&&(b=b?Object.assign(b,c):c);return b}function y(b,c){var a="",d;for(d in b)a=c?a+("&"+d+"="+b[d]):a+("&"+encodeURIComponent(d)+"="+encodeURIComponent(b[d]));return a?"?".concat(a.substring(1)):a}
function A(b,c,a,d){var e=r("svg",b),f=document.createElementNS("http://www.w3.org/2000/svg","use");f.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","#".concat(c));e||(e=document.createElementNS("http://www.w3.org/2000/svg","svg"),b.appendChild(e));e.appendChild(f);a&&(e.style.fill=a);d&&(e.style.stroke=d)}
function pa(b){if(b)if(1024>b)var c="B";else 1048576>b?(c="KB",b=Math.round(b/102.4)/10):1073741824>b?(c="MB",b=Math.round(b/104857.6)/10):(c="GB",b=Math.round(b/1.073741824E8)/10);else c="B",b=0;var a=b.toString();b=a.indexOf(".");var d=a.split(""),e="",f="";0<=b?f=a.slice(b):b=d.length;a=b%3;0<a&&(a=3-a);for(var g=0;g<b;)3==a&&(e+=",",a=0),e+=d[g],g++,a++;return(e+f).concat(c)}
function qa(b){var c=b%60;b=(b-c)/60;var a=b%60;b=(b-a)/60;var d="";0<b?(d+=b.toString(10)+":",d+="0".concat(a).slice(-2)+":"):d+=a.toString(10)+":";return d+="0".concat(c).slice(-2)}function ra(b){var c=b.lastIndexOf("."),a="";0<=c&&(a=b.slice(c+1));return a.toLowerCase()}function sa(){return new Promise(function(b){setTimeout(b,500)})};function ta(){var b=new FileReader;b.addEventListener("load",function(c){c.target.m&&c.target.m(c.target.result)});b.addEventListener("error",function(c){c.target.i&&c.target.i(c.target.error)});return b}FileReader.prototype.m=void 0;FileReader.prototype.i=void 0;function ua(b,c){return new Promise(function(a,d){b.m=a;b.i=d;b.readAsArrayBuffer(c)})}function va(b){b=b.replace(/-/g,"+").replace(/_/g,"/");var c=b.length%4;0<c&&(b+="====".slice(c));return b}
function B(b){return window.btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=*$/g,"")}function wa(b){for(var c="",a=0;a<b.length;)c+=String.fromCharCode(b[a]),a++;return c}function xa(b){for(var c=new Uint8Array(b.length),a=0;a<b.length;a++)c[a]=b.charCodeAt(a);return c}
function ya(b){var c=forge.md.md5.create();c.update(b);c=c.digest().getBytes();for(var a=forge.md.md5.create(),d=new forge.util.ByteBuffer,e="";48>d.length();)a.start(),e&&a.update(e),a.update(b),a.update(c),e=a.digest().getBytes(),d.putBytes(e);d.truncate(d.length()-48);return{key:d.getBytes(32),iv:d.getBytes()}}
function za(b,c,a){var d=a;"string"==typeof a&&(d=ya(a));if(!(d&&d.iv&&d.key))throw Error("Need iv and key. They can be generated by computeEvpKDF from password and salt.");a=new forge.util.ByteBuffer(d.key);b=b?forge.cipher.createCipher("AES-CBC",a):forge.cipher.createDecipher("AES-CBC",a);b.start({iv:d.iv});b.update(new forge.util.ByteBuffer(c));b.finish();return b.output.getBytes()}
function Aa(){this.h=0;this.g=null;this.i=function(b){const c=this;return l(function*(){c.h=b})};this.write=function(b){const c=this;return l(function*(){c.g||(c.g=[]);c.g.push(b);b=null})};this.cancel=function(){return l(function*(){})};this.A=function(){if(this.g&&0<this.g.length&&(this.g[0]instanceof ArrayBuffer||this.g[0]instanceof Uint8Array)){for(var b=0,c=0;c<this.g.length;c++)b+=this.g[c].byteLength;b=new Uint8Array(b);var a=0;for(c=0;c<this.g.length;++c){var d=this.g[c];d instanceof ArrayBuffer&&
(d=new Uint8Array(d));b.set(d,a);a+=d.byteLength}return b}return null};this.u=function(){var b=this.A();b instanceof Uint8Array||(b=new Uint8Array(b));return new Blob([b],{type:"application/octet-binary"})};this.download=function(b){var c=this.u();ma(c,b,null)};this.B=function(){return this.h}}
function Ba(b){this.blob=null;if(b.xa)if(b.xa instanceof Blob)this.blob=b.xa;else throw Error("blob is not a Blob.");else throw Error("blob must be specified.");this.l=1600;b.V&&(this.l=b.V);this.h=0;this.i=null;this.B=function(c){const a=this;return l(function*(){if(c){if(c>=a.g())throw Error("offset can not be bigger than input size.");a.h=c}else a.h=0;a.i=ta()})};this.ba=function(){return this.l};this.m=function(){return this.h};this.g=function(){return this.blob.size};this.s=function(){return this.h>=
this.g()};this.C=function(c){const a=this;return l(function*(){if(1==a.i.readyState)return null;var d=a.h;a.h=c?a.h+c:a.h+a.l;return yield ua(a.i,a.blob.slice(d,a.h))})};this.R=function(){this.blob=this.i=null}}
function Ca(b){this.s=!0;this.g=b.cb;this.iv=this.key="";this.m=null;this.h="";this.l=this.i=0;b.ab&&(this.s=!1);if(!this.g)throw Error("reader must be specified.");if(b.ma)b="string"==typeof b.ma?ya(b.ma):b.ma,this.key=b.key,this.iv=b.iv;else throw Error("keycfg must be specified.");this.P=function(){const c=this;return l(function*(){if(c.l)return c.l;if(c.s)return c.l=16*Math.ceil((c.g.g()+1)/16),c.l;0==c.g.g()&&(yield c.u());var a=c.g.g()-16,d=yield c.F(a);c.l=a+d.length;return c.l})};this.u=function(c){const a=
this;return l(function*(){var d=c||0;if(c){if(a.s)throw Error("Can NOT set offset for encryption.");c-=c%16+16;0>c&&(c=0)}yield a.g.B(c);var e=a.iv;d&&(e=(yield a.B(16)).getBytes());var f=new forge.util.ByteBuffer(a.key);a.m=a.s?forge.cipher.createCipher("AES-CBC",f):forge.cipher.createDecipher("AES-CBC",f);a.m.start({iv:e});a.i=d;a.h=""})};this.F=function(c){const a=this;return l(function*(){var d=a.g.ba(),e="",f=0<=c?c:a.g.m();if(a.i==f&&a.h){if(d<=a.h.length)return a.i+=d,e=a.h.substring(0,d),
a.h=a.h.substring(d),e;e=a.h;f+=a.h.length;a.i+=a.h.length;d-=a.h.length}var g=16*Math.ceil((f%16+d)/16);a.m&&a.i==f||(yield a.u(f));var k=yield a.B(g);g=k.length();a.m.update(k);a.g.s()&&a.m.finish();k=a.m.output.getBytes();f<a.g.m()?(f-=a.g.m()-g,0<f&&(k=k.substring(f)),k.length>d&&(a.h=k.substring(d),k=k.substring(0,d)),a.i+=d):k="";e?k&&(e=e.concat(k)):k&&(e=k);return e})};this.C=function(){return this.g.m()};this.D=function(){return this.g.s()};this.R=function(){this.g.R();this.m=this.g=null};
this.A=function(){return this.g.A()};this.B=function(c){const a=this;return l(function*(){var d=yield a.g.C(c);return new forge.util.ByteBuffer(d)})}}
function Da(b){this.g=new Ca(b);this.h=b.fb;this.speed=this.m=this.i=0;if(!this.h)throw Error("writer must be specified.");this.start=function(c,a){const d=this;return l(function*(){var e=c||0,f=yield d.g.P();yield d.h.i(f);yield d.g.u(c);d.i=Date.now()+1E3;d.m=e;for(e=d.g.D()?2:0;0==e;)(f=yield d.g.F())&&(yield d.h.write(xa(f))),d.g.D()?e=2:a&&!a()&&(e=1);1==e&&(yield d.h.cancel());d.h=null;d.g.R();d.g=null;return 2==e})};this.l=function(){Date.now()>this.i&&(this.speed=1E3*(this.g.C()-this.m)/(Date.now()-
this.i+1E3),this.i=Date.now()+1E3,this.m=this.g.C());return this.speed}}function Ea(b,c){return l(function*(){yield b.B(0);yield c.i(b.g());for(var a=0;0==a;){var d=yield b.C();yield c.write(d);b.s()&&(a=2)}return 1==a?(yield c.cancel(),!1):!0})};function Fa(){this.A=!0;this.h=this.g=null;this.l=this.D=!1;this.m=-1;this.Y=function(){return null!=this.g};this.ba=function(b){if(this.A)try{var c=window.sessionStorage.getItem("language"),a=window.sessionStorage.getItem("relay_url"),d=window.sessionStorage.getItem("drive"),e=window.sessionStorage.getItem("drive_extra"),f=window.sessionStorage.getItem("skipLogin");window.sessionStorage.clear();c&&window.sessionStorage.setItem("language",c);a&&!b&&window.sessionStorage.setItem("relay_url",a);d&&
!b&&window.sessionStorage.setItem("drive",d);e&&!b&&window.sessionStorage.setItem("drive_extra",e);f&&!b&&window.sessionStorage.setItem("skipLogin",f)}catch(g){this.A=!1,console.error(g)}};this.s=function(b){var c=null;if(this.A)try{c=window.sessionStorage.getItem(b)}catch(a){this.A=!1,console.error(a)}return c};this.Ta=function(b){var c=this.s("login_state");return c&&b==c?!0:!1};this.u=function(b,c){if(this.A)try{return window.sessionStorage.setItem(b,c.toString()),!0}catch(a){this.A=!1,console.error(a)}return!1};
this.F=function(b){if(this.A)try{window.sessionStorage.removeItem(b)}catch(c){this.A=!1,console.error(c)}};this.Xa=function(){var b=this.s("language"),c=this.s("relay_url"),a=this.s("drive"),d=this.s("drive_extra"),e=this.s("skipLogin");this.h={};b&&(this.h.language=b,this.Z(b));c&&(this.h.ta=c,this.Sa(c));a&&(this.h.I=a,this.Za(a));d&&(this.h.hb=d,this.P(d));e&&this.$a(e)};this.mb=function(){var b=this.i("drive");b||(this.h||this.Xa(),b=this.h.I);return b};this.Za=function(b){return this.Ha("drive",
b)?(this.g[b]||(this.g[b]={}),!0):this.g?!1:!0};this.$a=function(b){b?this.l=this.Y():(this.l=!1,this.nb()&&(this.D=!0));this.u("skipLogin",this.l)};this.Wa=function(b){var c=this.i("language");!c&&b&&this.h&&(c=this.h.language);return c};this.Z=function(b){this.Ha("language",b)};this.Ra=function(){var b=this.i("relay_url");!b&&this.h&&(b=this.h.ta);return b?b:""};this.Sa=function(b){this.Ha("relay_url",b)};this.Va=function(){var b=null,c=this.B("extra_info");!c&&this.h&&this.h.hb&&(c=this.h.hb);
c&&(b=JSON.parse(c));return b&&2==b.length?{ya:b[0],fa:b[1]}:null};this.P=function(b){b?(b="string"===typeof b?b:JSON.stringify([b.ya,b.fa]),this.u("drive_extra",b),this.C("extra_info",b)):(this.F("drive_extra"),this.C("extra_info",null))};this.qb=function(){var b=this;return new Promise(function(c,a){if(window.indexedDB){var d=window.indexedDB.open("zgayard1946");d.onerror=function(e){a(e.target.error)};d.onupgradeneeded=function(e){e.target.result.createObjectStore("settings",{keyPath:"key"})};
d.onsuccess=function(e){var f=e.target.result;e=f.transaction("settings","readwrite");e.oncomplete=function(){f.close();c()};e.objectStore("settings").getAll().onsuccess=function(g){b.g={};g.target.result.forEach(function(k){b.g[k.key]=k.value});g=b.g.drive;b.l=g&&b.g[g]&&b.g[g].refresh_token?!0:!1}}}else a(Error("IndexedDB is not supported in your browser settings."))})};this.ob=function(){var b=this;return new Promise(function(c,a){var d=window.indexedDB.deleteDatabase("zgayard1946");d.onerror=
function(e){console.error("Failed to dropt IndexedDB.");a(e.target.error)};d.onsuccess=function(){b.ba(!0);b.g=null;b.l=!1;console.log("IndexedDB has been dropped.");c()}})};this.Ya=function(){const b=this;return l(function*(){b.D&&b.g&&(yield b.R(function(c){c.clear().onsuccess=function(){for(var a in b.g)c.put({key:a,value:b.g[a]})}}),b.D=!1)})};this.B=function(b){var c=this.i("drive");return c&&(c=this.g[c])?c[b]:null};this.nb=function(){var b=this.i("drive");return b&&(b=this.g[b])&&b.refresh_token?
(delete b.refresh_token,!0):!1};this.C=function(b,c,a){const d=this;return l(function*(){if(d.g){var e=d.i("drive");if(c)d.g[e]||(d.g[e]={}),d.g[e][b]=c;else if(d.g[e]&&d.g[e][b])delete d.g[e][b];else return;a?yield d.R(function(f){f.put({key:e,value:d.g[e]})}):d.D=!0}})};this.Ua=function(){const b=this;return l(function*(){b.ba(!0);if(b.g){var c=b.i("drive");delete b.g[c].refresh_token;delete b.g.drive;yield b.R(function(a){a.put({key:c,value:b.g[c]});a.delete("drive")})}})};this.lb=function(b,c){const a=
this;return l(function*(){var d=a.i("recent");d||(d=[]);0>a.m&&(d.push({drive:a.i("drive"),root:a.B("root"),played:[]}),a.m=d.length-1);var e=d[a.m],f={fid:b.H,time:b.ha};0<=c&&c<e.played.length?e.played[c]=f:e.played.push(f);yield a.saveData("recent",d)})};this.pb=function(){var b=this.i("recent");this.m=-1;if(b){var c=0;for(c=0;c<b.length;c++){var a=b[c];if(a.drive==this.i("drive")&&a.root==this.B("root")){this.m=c;break}}}if(0<=this.m){var d=[];b[this.m].played.forEach(function(e){d.push({H:e.fid,
K:"",ha:e.time})});return d}return null};this.rb=function(b){const c=this;return l(function*(){var a=c.i("recent");if(a&&!(0>c.m)){var d=a[c.m].played;b<d.length&&(d.splice(b,1),yield c.saveData("recent",a))}})};this.R=function(b){return new Promise(function(c,a){var d=window.indexedDB.open("zgayard1946");d.onerror=function(e){a(e.target.error)};d.onsuccess=function(e){var f=e.target.result;e=f.transaction("settings","readwrite");e.oncomplete=function(){f.close();c()};e=e.objectStore("settings");
b&&b(e)}})};this.Ha=function(b,c){if(c){if(this.u(b,c),this.g&&this.g[b]!=c)return this.g[b]=c,this.D=!0}else if(this.F(b),this.g&&this.g[b])return delete this.g[b],this.D=!0;return!1};this.i=function(b){return this.g&&this.g[b]?this.g[b]:null};this.saveData=function(b,c){const a=this;return l(function*(){a.g&&(a.g[b]=c);yield a.R(function(d){d.put({key:b,value:c})})})}};var Ga={};function Ha(b,c,a){this.j=b;this.o=c;this.g=a}Ha.prototype.A=function(){return this.o};function Ia(b,c){this.ta=null;this.u=c;this.h=null;this.g=b;this.ka||(this.ka=function(){})}function Ja(b){null==b.ta&&(b.ta=b.g.Ra());return b.ta}
function Ka(b,c){return l(function*(){var a="POST",d=b.l().concat(encodeURI(c.W)),e=new Headers;if(c&&c.G)e.append("Authorization",c.G);else if(c&&c.Ca){var f="Bearer";c&&c.Da&&(f=c.Da);e.append("Authorization",f+" "+c.Ca)}else e.append("Authorization",b.h);if(c&&c.za)for(var g of c.za.entries())e.append(g[0],g[1]);c&&c.Aa&&(a=c.Aa);a=yield fetch(d,{method:a,body:c.Ja,headers:e,redirect:"follow"});401==a.status&&b.g.l&&!c.ub&&(a=yield La(b,c));return a})}h=Ia.prototype;
h.Fa=function(b){const c=this;return l(function*(){if(b&&(c.h=c.g.s("access_token"),c.h))return null;var a=c.g.l,d={},e=oa();if(e&&e.token_type&&e.access_token){c.h=e.token_type+" "+e.access_token;c.g.u("access_token",c.h);if(e&&e.state)if(c.g.Ta(e.state))c.g.F("login_state");else return"Unauthorized access to this url.";return null}e&&e.code?d.code=e.code:a&&(d.Qa=c.g.B("refresh_token"));var f=c.g.Va();f&&(d.clientId=f.ya,d.gb=f.fa);if(d.code||d.Qa){if(e&&e.state)if(c.g.Ta(e.state))c.g.F("login_state");
else return"Unauthorized access to this url.";if((d=yield Ma(c,d))&&d.token_type&&d.access_token)return f&&d.client_secret_enc&&(f.fa=d.client_secret_enc,c.g.P(f)),c.h=d.token_type+" "+d.access_token,c.g.u("access_token",c.h),a&&d.refresh_token&&c.g.C("refresh_token",d.refresh_token),d.logout&&c.g.u("logout_url",d.logout),null}else if(a&&(d.jb=!0),(d=yield Ma(c,d))&&d.url)return f&&d.client_secret_enc&&(f.fa=d.client_secret_enc,c.g.P(f)),d.state&&(c.g.u("login_state",d.state)||(d.state=c.m())),d.logout&&
c.g.u("logout_url",d.logout),window.location.href=d.url.concat("&state=".concat(encodeURIComponent(d.state))),"redirect";return d&&d.error?"["+d.error+"] "+d.error_description:"Unknown error occured when doing authorization."})};
h.Pa=function(){const b=this;return l(function*(){b.h=null;b.g.F("access_token");var c=b.g.s("logout_url");c?window.location.href=c:(c=new FormData,c.append("drive_type",b.m()),c.append("action","logout"),c=yield fetch(b.u,{method:"POST",credentials:"include",body:c,redirect:"follow"}),c.ok&&(c=yield c.text(),(c=JSON.parse(c))&&c.logout&&(window.location.href=c.logout)))})};h.wa=function(){return l(function*(){})};h.X=function(){return l(function*(){})};h.ca=function(){return l(function*(){})};
h.ia=function(){return l(function*(){})};function Na(b){return l(function*(){if(!b||!b.$)throw Error("newname is not specified.");return yield C.ua(b)})}function Oa(b){return l(function*(){if(!b||!b.v)throw Error("parentid is not specified.");if(!b||!b.La)throw Error("oldparentid is not specified.");return yield C.ua(b)})}h.delete=function(){return l(function*(){})};h.sa=function(){return l(function*(){})};h.Ea=function(){return l(function*(){})};h.Oa=function(){return l(function*(){})};
h.Ia=function(b){return new Pa(b,this)};h.ra=function(){return l(function*(){})};h.kb=function(){};h.va=function(b){return new Qa(b,this)};function Ra(b){return l(function*(){return{eb:b.status,da:yield b.text()}})}function G(b,c,a,d,e,f,g){return l(function*(){var k={W:c,Aa:a};Sa(e,k);f&&(k.za=f);g&&(k.Ja=g);k=yield Ka(b,k);var m=yield Ra(k);if(d&&k.status!=d)throw Error(JSON.stringify(m));return m})}function H(b,c,a){return l(function*(){return(yield G(b,c,"GET",200,a,null,null)).da})}
function Sa(b,c){b.Da&&(c.Da=b.Da);b.Ca&&(c.Ca=b.Ca);b.G&&(c.G=b.G)}h.ua=function(){return l(function*(){})};
function Ma(b,c){return l(function*(){if(!c)throw Error("Options are not specified when auth onedrive.");var a=new FormData;a.append("drive_type",b.m());c.clientId&&a.append("client_id",c.clientId);c.zb&&a.append("redirect_uri",c.zb);c.gb&&a.append("client_secret",c.gb);c.code?a.append("code",c.code):c.Qa?a.append("refresh_token",c.Qa):c.jb&&a.append("need_code",c.jb);a=yield fetch(b.u,{method:"POST",body:a,credentials:"include",redirect:"follow"});if(200==a.status)return yield a.json();var d=yield a.text();
throw Error(d+" ("+a.status+")");})}function La(b,c){return l(function*(){console.log("Retry to send ajax.");if(c)c.ub=!0;else return null;var a=yield b.Fa();if(a)return console.error(a),null;c.G=b.h;return yield Ka(b,c)})}h.ib=function(b){return b.ok};
function Ta(b){b.Ga=Ia;if("function"===typeof Object.create)b.prototype=Object.create(Ia.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});else{var c=function(){};c.prototype=Ia.prototype;b.prototype=new c;b.prototype.constructor=b}b.prototype.yb||(b.prototype.yb=function(){return this.constructor.Ga});b.prototype.ka||(b.prototype.ka=function(...a){return this.constructor.Ga.call(this,...a)});b.prototype.Ab||(b.prototype.Ab=function(a,...d){return a?this.constructor.Ga.prototype[a].call(this,
...d):this.constructor.Ga.call(this,...d)})}function Ua(b,c,a){Ta(a);Ga[b]=new Ha(b,c,a)}var Va=-1,Wa=-9,Xa=0;
function Pa(b,c){this.I=c;this.s=b;this.C="";this.g=this.l=0;this.h=null;if(!this.s||!this.s.S)throw Error("fnm is not specified.");this.i=function(a){const d=this;return l(function*(){d.l=a;d.C=yield d.I.sa(d.s,a)})};this.write=function(a){const d=this;return l(function*(){var e=null;if(d.h){var f=d.h.byteLength;0<f?(e=new Uint8Array(f+a.byteLength),e.set(d.m(d.h),0),e.set(d.m(a),f)):e=d.m(a);d.h=null}else e=d.m(a);var g=new Blob([e],{type:"application/octet-binary"}),k="bytes "+d.g+"-";d.g+=g.size;
k+=d.g-1+"/"+d.l;var m=0,n=function(){const p=this;return l(function*(){var z=new Headers;z.append("Content-Range",k);try{var E=yield fetch(p.C,{method:"PUT",headers:z,body:g,redirect:"follow"});z="";if(c.ib(E)){var F=yield p.I.Ea(E);if(F==Wa)throw a=null,z=yield E.text(),Error(z+" ("+E.status+")");if(F!=Va&&F!=Xa&&F<p.g){var O=a.byteLength;O-=p.g-F;if(0<O){var P=a.slice(O);a=null;p.g>=p.l?yield p.write(P):(p.h=P,p.g=F)}else throw a=null,Error("Can NOT continue to upload buffer.");}}else throw a=
null,z=yield E.text(),Error(z+" ("+E.status+")");}catch(U){if(1>m)m++,yield sa(),yield n();else throw g=a=null,U;}})}.bind(d);yield n()})};this.cancel=function(){const a=this;return l(function*(){yield a.I.Oa(a.C)})};this.B=function(){return this.l};this.m=function(a){return a instanceof Uint8Array?a:new Uint8Array(a)}}
function Qa(b,c){this.I=c;this.D=b;this.url="";this.name=null;this.F=this.i=this.h=this.size=0;this.Z=!1;this.P=16E3;b.V&&(this.P=b.V);this.u=this.l=0;this.B=function(a){const d=this;return l(function*(){if(d.Z)if(d.i&&(d.F=d.i,d.i=0),a){if(a>=d.g())throw console.log("offset:"+a+",size:"+d.g()),Error("offset can not be bigger than input size.");d.h=a}else d.h=0;else{var e=yield d.I.ra(d.D);d.Z=!0;if(e){if(d.size=e.O||0,d.url=e.j,d.name=e.o,d.u="1"==e.M?1:0,a){if(a>=d.g())throw Error("offset can not be bigger than input size.");
d.h=a}}else throw Error("Failed to prepare reader.");}})};this.A=function(){return this.name};this.ba=function(){return this.P};this.m=function(){return this.h};this.g=function(){return this.size};this.s=function(){return this.h>=this.g()};this.C=function(a){const d=this;return l(function*(){a||(a=d.P);return yield d.Y(a)})};this.R=function(){};this.Y=function(a){const d=this;return l(function*(){if(a&&d.i)return null;if(a)d.i=a;else if(d.i)a=d.i;else throw Error("size must be specified.");if(d.F)return null;
var e=d.h+a-1,f=function(){const g=this;return l(function*(){var k=g.url,m=new Headers;10<=g.l&&(k=Ja(g.I),m.append("Zb-Url",g.url));g.I.kb(m,g.D.G);m.append("Range","bytes="+g.h+"-"+e);try{var n=yield fetch(k,{method:"GET",headers:m,redirect:"follow"});if(g.F){if(g.F=0,g.i)return yield g.Y()}else{g.i=0;g.l=10>g.l?1:11;if(200==n.status||206==n.status){2==g.u&&(g.u=1);var p=parseInt(n.headers.get("content-length"),10);if(p)g.h+=p;else{var z=n.headers.get("content-range");if(z){var E=z.indexOf("-");
if(0>E)var F=0;else{E++;var O=z.indexOf("/",E);F=O<=E?0:parseInt(z.slice(E,O),10)}}else F=0;g.h=F?F+1:e+1}200==n.status&&g.h<g.g()?g.h=g.g():g.h>g.g()&&(g.h=g.g());return yield n.arrayBuffer()}if(401==n.status&&1==g.u){console.log("Retry auth.");g.u=2;var P=yield g.I.Fa();if(P)console.error(P);else return g.D.G&&delete g.D.G,yield f()}else{var U=yield n.text();throw Error(U+" ("+n.status+")");}}}catch(D){if(0==g.l&&Ja(g.I))return g.l=10,yield f();if(1==g.l||11==g.l)return g.l++,yield sa(),yield f();
throw D;}})}.bind(d);return yield f()})}};Ua("onedrive","Microsoft OneDrive",function(b,c){this.ka(b,c);this.m=function(){return"onedrive"};this.wa=function(a){const d=this;return l(function*(){var e=yield H(d,"/me/drive",a);e=JSON.parse(e).quota;return{Na:e.deleted,Ma:e.total,oa:e.used}})};this.X=function(a){const d=this;return l(function*(){var e="/me/drive/root/children";if(a){if(a.U){e=function(k){const m=this;return l(function*(){var n={aa:""};Sa(a,n);n=yield m.i(n,k);var p=[];n&&p.push(n);return p})}.bind(d);if(a.v){var f={aa:a.v};
Sa(a,f);if(f=yield d.i(f))return yield e(f.tb.concat("/").concat(f.o).concat("/").concat(a.U))}else return yield e("/drive/root:/".concat(a.U));return null}a.v&&(e="/me/drive/items/"+a.v+"/children")}e=yield H(d,e.concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),a);var g=[];e&&JSON.parse(e).value.forEach(function(k){g.push(this.ea(k))},d);return g})};this.ca=function(a){const d=this;return l(function*(){return yield d.i(a)})};this.ia=function(a){const d=this;
return l(function*(){if(!a||!a.K)throw Error("Name of new folder is not specified.");var e=new Headers;e.append("Content-Type","application/json;charset=UTF-8");var f="/me/drive/root/children";a.v&&(f="/me/drive/items/"+a.v+"/children");var g=JSON.stringify({name:a.K,folder:{},"@microsoft.graph.conflictBehavior":"fail"});e=yield G(d,f,"POST",201,a,e,g);return d.ea(JSON.parse(e.da))})};this.delete=function(a){const d=this;return l(function*(){var e="/me/drive/items/".concat(a.H);yield G(d,e,"DELETE",
204,a,null,null);return 0})};this.sa=function(a){const d=this;return l(function*(){var e={W:"/me",Aa:"POST",G:a.G,za:new Headers({"Content-Type":"application/json;charset=UTF-8","Cache-Control":"no-cache",Pragma:"no-cache"})};e.W=a.N?"/me/drive/items/"+a.N+":/":e.W+"/drive/root:/";e.W+=a.S;e.W+=":/createUploadSession";e.Ja=JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"replace",name:a.S}});e=yield Ka(d,e);var f=yield Ra(e),g="";e.ok&&(g=JSON.parse(f.da).uploadUrl);return g})};this.Ea=
function(a){return l(function*(){if(0<=[200,201].indexOf(a.status))return Va;if(0>[202].indexOf(a.status))return Wa;var d=yield a.text();if((d=JSON.parse(d).nextExpectedRanges)&&d.length){var e=d[0].indexOf("-");if(0<e)return parseInt(d[0].substring(0,e),10)}return Xa})};this.Oa=function(a){return l(function*(){var d=yield fetch(a,{method:"DELETE",redirect:"follow"});if(!d.ok)throw(yield d.text())+" ("+d.status+")";})};this.ra=function(a){const d=this;return l(function*(){var e="/me/drive/items/".concat(a.j),
f={};a.G&&(f.G=a.G);e=yield H(d,e.concat(y({select:"name,size,@microsoft.graph.downloadUrl"},!0)),f);f=null;e&&(e=JSON.parse(e),f={j:e["@microsoft.graph.downloadUrl"],o:e.name,O:e.size});return f})};this.l=function(){return"https://graph.microsoft.com/v1.0"};this.ua=function(a){const d=this;return l(function*(){if(!a||!a.H)throw Error("fid is not specified.");var e=new Headers;e.append("Content-Type","application/json;charset=UTF-8");var f="/me/drive/items/".concat(a.H),g={};a.$&&(g.name=a.$);a.v&&
(g.parentReference={id:a.v});g=JSON.stringify(g);if("{}"==g)throw Error("No property to be updated.");yield G(d,f,"PATCH",200,a,e,g);return 0})};this.i=function(a,d){const e=this;return l(function*(){var f=d?d.startsWith("/me")?d:"/me".concat(d):"/me/drive/items/"+a.aa;f=yield G(e,f.concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),"GET",0,a,null,null);if(200==f.eb)return e.ea(JSON.parse(f.da));if(404==f.eb&&d)return null;throw Error(JSON.stringify(f));})};this.ea=
function(a){var d={j:a.id,o:a.name,O:a.size,na:a.lastModifiedDateTime,tb:a.parentReference.path,J:a.parentReference.id,M:"0"};a.folder?d.M="1":a.file&&(d.M="2");return d}});Ua("googledrive","Google Drive",function(b,c){this.ka(b,c);this.m=function(){return"googledrive"};this.wa=function(a){const d=this;return l(function*(){var e=d.i("/about").concat(y({fields:"storageQuota"}));e=yield H(d,e,a);e=JSON.parse(e).storageQuota;return{Na:e.usageInDriveTrash,Ma:e.limit,oa:e.usage}})};this.X=function(a){const d=this;return l(function*(){var e=d.i("/files"),f="'"+(a.v?a.v:"root")+"' in parents";a.U&&(f=f.concat(" and name = '"+a.U+"'"));e=yield H(d,e.concat(y({fields:"files(id,name,mimeType,parents,modifiedTime,size)",
q:f},!0)),a);var g=[];JSON.parse(e).files.forEach(function(k){g.push(this.ea(k))},d);return g})};this.ca=function(a){const d=this;return l(function*(){var e=d.i("/files/").concat(a.aa);e=yield H(d,e.concat(y({fields:"id,name,mimeType,parents,modifiedTime,size"},!0)),a);return d.ea(JSON.parse(e))})};this.ia=function(a){const d=this;return l(function*(){if(!a||!a.K)throw Error("Name of new folder is not specified.");var e=new Headers;e.append("Content-Type","application/json;charset=UTF-8");var f=d.i("/files");
e=yield G(d,f,"POST",200,a,e,JSON.stringify({mimeType:"application/vnd.google-apps.folder",name:a.K,parents:[a.v?a.v:"root"]}));return d.ea(JSON.parse(e.da))})};this.delete=function(a){const d=this;return l(function*(){var e=d.i("/files/").concat(a.H);yield G(d,e,"DELETE",204,a,null,null);return 0})};this.sa=function(a,d){const e=this;return l(function*(){var f={U:a.S,G:a.G};a.N&&(f.v=a.N);f=yield e.X(f);return 0<f.length?yield e.s(a,d,f[0].j):yield e.s(a,d)})};this.Ea=function(a){return l(function*(){if(0<=
[200,201].indexOf(a.status))return Va;if(0>[308].indexOf(a.status))return Wa;var d=a.headers.get("range");if(d){var e=d.indexOf("-");if(0<e)return parseInt(d.slice(e+1),10)+1}return Xa})};this.ra=function(a){const d=this;return l(function*(){var e=d.i("/files/").concat(a.j),f={aa:a.j};a.G&&(f.G=a.G);if(f=yield d.ca(f))f.j=d.l().concat(encodeURI(e)).concat(y({alt:"media"})),d.g.l&&(f.M="1");return f})};this.kb=function(a,d){d?a.append("Authorization",d):a.append("Authorization",this.h?this.h:"")};
this.ib=function(a){return a.ok||308==a.status};this.l=function(){return"https://www.googleapis.com"};this.ua=function(a){const d=this;return l(function*(){var e=!0,f=new Headers;f.append("Content-Type","application/json;charset=UTF-8");var g=d.i("/files/").concat(a.H);a.La&&a.v&&(g=g.concat(y({addParents:a.v,removeParents:a.La})),e=!1);var k={};a.$&&(k.name=a.$,e=!1);if(e)throw Error("No property to be updated.");yield G(d,g,"PATCH",200,a,f,JSON.stringify(k));return 0})};this.s=function(a,d,e){const f=
this;return l(function*(){var g={},k="POST",m="/files?uploadType=resumable";e?(k="PATCH",m="/files/"+e+"?uploadType=resumable"):(g.name=a.S,a.N&&(g.parents=[a.N]));g={W:"/upload".concat(f.i(m)),Aa:k,G:a.G,za:new Headers({"X-Upload-Content-Length":d,"X-Upload-Content-Type":"application/octet-stream","Content-Type":"application/json; charset=UTF-8"}),Ja:JSON.stringify(g)};g=yield Ka(f,g);if(g.ok)return g.headers.get("location")||"";g=yield Ra(g);throw Error(g.da);})};this.i=function(a){return"/drive/v3".concat(a)};
this.ea=function(a){var d={j:a.id,o:a.name,O:a.size,na:a.modifiedTime,M:"2"};a.parents&&0<a.parents.length&&(d.J=a.parents[0]);this.A(a.mimeType)&&(d.M="1");return d};this.A=function(a){return"application/vnd.google-apps.folder"==a}});function Ya(b,c){this.I=c;this.P=b;this.h=null;this.i=this.size=0;this.l="";this.F=this.u=0;this.D=1600;b.V&&(this.D=b.V);this.B=function(a){const d=this;return l(function*(){var e=yield d.I.ra(d.P);if(e)d.size=e.O||0,e=yield d.I.F(d.P.j),d.h=e,d.h.sort(function(f,g){return f.la-g.la}),d.Y(a);else throw Error("Failed to prepare reader.");})};this.ba=function(){return this.D};this.m=function(){return this.i};this.g=function(){return this.size};this.s=function(){return this.h?this.u>=this.h.length:
!0};this.C=function(a){const d=this;return l(function*(){if(!d.l){var e=yield d.I.D(d.h[d.u].j);d.l=window.atob(va(e))}return yield d.Z(a)})};this.R=function(){this.h=null;this.l=""};this.Y=function(a){if(a){if(a>=this.g())throw Error("offset can not be bigger than input size.");this.i=a;var d=0;for(a=0;a<this.h.length&&!(d+=this.h[a].O,this.i<d);a++)this.F=d;if(a<this.h.length)this.u=a;else throw Error("offset can not be bigger than input size.");}else this.u=this.F=this.i=0;this.l=""};this.Z=function(a){const d=
this;return l(function*(){var e=d.i-d.F,f=d.l.length-e;a?a<f&&(f=a):d.D<f&&(f=d.D);var g=xa(d.l.substring(e,e+f));d.i+=f;d.l.length==e+f&&(d.l="",d.u++,d.F=d.i);return g.buffer})}}
function Za(b,c){this.I=c;this.g=b;this.data={j:"",o:"",O:0,J:"",M:"2"};this.m=this.h=0;this.i=function(a){const d=this;return l(function*(){d.h=a;d.data.o=d.g.S;d.g.N&&(d.data.J=d.g.N);d.data.j=yield d.I.sa(d.g,a)})};this.write=function(a){const d=this;return l(function*(){d.data.O+=a.byteLength;var e=B(wa(d.l(a)));d.m++;yield d.I.saveData(d.data.j,d.m,a.byteLength,e);d.data.O>=d.h&&(yield d.I.C(d.data))})};this.cancel=function(){const a=this;return l(function*(){yield a.I.delete({H:a.data.j})})};
this.B=function(){return this.h};this.l=function(a){return a instanceof Uint8Array?a:new Uint8Array(a)}}
Ua("idxdb","Loacal Indexed DB",function(b,c){this.ka(b,c);this.m=function(){return"idxdb"};this.Fa=function(){return new Promise(function(){this.xb()})};this.Pa=function(){return l(function*(){location.reload()})};this.wa=function(){const a=this;return l(function*(){var d={Na:0,Ma:0,oa:0};yield a.i(function(e){e.getAll().onsuccess=function(f){f.target.result.forEach(function(g){"2"==g.type&&(d.oa+=parseInt(g.size,10))})}});return d})};this.X=function(a){const d=this;return l(function*(){return yield d.A(void 0,
a.v,a.U)})};this.ca=function(a){const d=this;return l(function*(){var e=yield d.A(a.aa);return e&&0<e.length?e[0]:null})};this.ia=function(a){const d=this;return l(function*(){if(!a||!a.K)throw Error("Name of new folder is not specified.");var e={j:"",o:a.K,O:0,J:"",M:"1"};a.v&&(e.J=a.v);e.j=yield d.B(e.J);yield d.C(e);return e})};this.delete=function(a){const d=this;return l(function*(){function e(k){var m;for(m=0;m<f.length;m++)f[m].j==k?f[m].Ka=!0:f[m].J==k&&("1"==f[m].M?e(f[m].j):f[m].Ka=!0)}
var f=[],g=0;yield d.i(function(k){k.getAll().onsuccess=function(m){m.target.result.forEach(function(n){f.push({j:n.key,o:"",J:n.pid})})}});e(a.H);yield d.i(function(k){f.forEach(function(m){m.Ka&&k.delete(m.j)})});yield d.s(function(k){var m=[];f.forEach(function(n){n.Ka&&"2"==n.M&&m.push(n.j)});0>m.indexOf(a.H)&&m.push(a.H);k.getAllKeys().onsuccess=function(n){n.target.result.forEach(function(p){var z=p.indexOf(":");0<=m.indexOf(p.substring(0,z))&&(k.delete(p),g+=parseInt(p.substring(p.indexOf("_",
z+1)+1),10))})}});return g})};this.Ia=function(a){return new Za(a,this)};this.sa=function(a){const d=this;return l(function*(){var e="";a.N&&(e=a.N);return yield d.B(e)})};this.Ea=function(){return l(function*(){return Xa})};this.Oa=function(){return l(function*(){})};this.va=function(a){return new Ya(a,this)};this.ra=function(a){const d=this;return l(function*(){return yield d.ca({aa:a.j})})};this.l=function(){return""};this.ua=function(a){const d=this;return l(function*(){if(!a||!a.H)throw Error("fid is not specified.");
yield d.i(function(e){e.get(a.H).onsuccess=function(f){if(f=f.target.result){var g=!1;a.$&&f.name!=a.$&&(f.name=a.$,g=!0);a.v&&f.pid!=a.v&&(f.pid=a.v,g=!0);g&&e.put(f)}}});return 0})};this.C=function(a){const d=this;return l(function*(){a.na=d.R();var e={key:a.j,name:a.o,size:a.O,tms:a.na,type:a.M};a.J&&(e.pid=a.J);yield d.i(function(f){f.put(e)})})};this.saveData=function(a,d,e,f){const g=this;return l(function*(){yield g.s(function(k){k.put({key:a+":"+d+"_"+e,data:f})})})};this.F=function(a){const d=
this;return l(function*(){var e=[];yield d.s(function(f){f.getAllKeys().onsuccess=function(g){g.target.result.forEach(function(k){var m=k.indexOf(":");if(k.substring(0,m)==a){var n=k.substring(m+1);m=n.indexOf("_");e.push({j:k,la:parseInt(n.substring(0,m),10),O:parseInt(n.substring(m+1),10)})}})}});return e})};this.D=function(a){const d=this;return l(function*(){var e="";yield d.s(function(f){f.get(a).onsuccess=function(g){e=g.target.result.data}});return e})};this.xb=function(){new Promise(function(a,
d){if(window.indexedDB){var e=window.indexedDB.open("zgalocaldb");e.onerror=function(f){d(f.target.error)};e.onupgradeneeded=function(f){f=f.target.result;f.createObjectStore("items",{keyPath:"key"});f.createObjectStore("datas",{keyPath:"key"})};e.onsuccess=function(f){f.target.result.close();a()}}else d(Error("IndexedDB is not supported in your browser settings."))})};this.i=function(a){return new Promise(function(d){window.indexedDB.open("zgalocaldb").onsuccess=function(e){var f=e.target.result;
e=f.transaction("items","readwrite");e.oncomplete=function(){f.close();d()}.bind(this);e=e.objectStore("items");a&&a(e)}.bind(this)})};this.s=function(a){return new Promise(function(d){window.indexedDB.open("zgalocaldb").onsuccess=function(e){var f=e.target.result;e=f.transaction("datas","readwrite");e.oncomplete=function(){f.close();d()}.bind(this);e=e.objectStore("datas");a&&a(e)}.bind(this)}.bind(this))};this.A=function(a,d,e){const f=this;return l(function*(){var g=[];yield f.i(function(k){k.getAll().onsuccess=
function(m){m.target.result.forEach(function(n){var p=!0;a&&(p=a==n.key);p&&d&&(p=d==n.pid);p&&e&&(p=e==n.name);p&&g.push({j:n.key,o:n.name,O:n.size,na:n.tms,M:n.type,J:n.pid})})}});return g})};this.R=function(){var a;a||(a=new Date);var d=[],e=[];d.push(a.getFullYear());d.push(a.getMonth()+1);d.push(a.getDate());e.push("0".concat(a.getHours()).slice(-2));e.push("0".concat(a.getMinutes()).slice(-2));e.push("0".concat(a.getSeconds()).slice(-2));return d.join("-")+" "+e.join(":")};this.B=function(a){const d=
this;return l(function*(){var e=-1;yield d.i(function(f){f.getAllKeys().onsuccess=function(g){g.target.result.forEach(function(k){var m=k.indexOf("_");a&&0<m?k.substring(m+1)==a&&(m=parseInt(k.substring(0,m),10),m>e&&(e=m)):!a&&0>m&&(m=parseInt(k,10),m>e&&(e=m))})}});e++;return a?e+"_"+a:e.toString()})}});function $a(b,c){var a=I;this.h=this.g=null;this.B=a;this.i=1;this.u=b;this.l=c;this.m=0;this.s=function(){const d=this;return l(function*(){var e={type:0,wtype:d.i,size:d.g.g()};d.l(e);var f=new Da({ab:1==d.i,ma:d.B,cb:d.g,fb:d.h});e=function(){var m={type:1,wtype:this.i,begin:this.m,spd:f.l(),posn:this.g.m(),size:this.g.g()};this.l(m);return this.u()?!1:!0}.bind(d);d.m=Date.now();var g=null,k=yield f.start(0,e).catch(function(m){g=m});e={type:2,wtype:d.i,begin:d.m,posn:d.g.m(),size:d.h.B()};g?e.errr=
g.message||g.Bb:k?d.h.u&&(e.blob=d.h.u()):e.type=3;d.l(e)})};this.A=function(d){var e=C;const f=this;return l(function*(){f.i=1;f.g=e.va({j:d,V:16E5});f.h=new Aa;yield f.s()})};this.C=function(d,e,f){var g=C;const k=this;return l(function*(){k.i=2;k.g=new Ba({xa:e,V:16E5});k.h=g.Ia({S:d,N:f});yield k.s()})}};var J=null,C=null,K=[],L=0,I=null,M=[],N=0,Q=[];function R(b,c){N&&(window.clearTimeout(N),N=0);var a=r("#divMessage");if(0==b)a.style.display||(a.style.opacity="0",N=window.setTimeout(function(){N=0;v(a)},150));else{var d=q("span",a);1==b?(a.className="zb-notice",d[0].innerText="Notice"):(a.className="zb-alert",d[0].innerText="Error");d[1].innerText=c?c:"";a.style.opacity&&(u(a),N=window.setTimeout(function(){N=0;a.style.opacity=""},50))}}
function S(b){var c="";"string"===typeof b?window.msgs&&b&&window.msgs[b]?c=window.msgs[b]:c=b:b&&(c=JSON.stringify(b));R(2,c)}function T(b){var c=b;window.msgs&&b&&window.msgs[b]&&(c=window.msgs[b]);R(1,c)}function ab(b){T(b);N=setTimeout(function(){N=0;R(0)},3E3)}
function bb(b){return new Promise(function(c){function a(e){(e.target||e.srcElement).remove();c("error"!=e.type)}var d=document.createElement("script");d.setAttribute("type","text/javascript");d.setAttribute("src",b);d.addEventListener("load",a);d.addEventListener("error",a);document.body.appendChild(d)})}
function cb(b){return l(function*(){if(J.Y())if(r("#chkSaveKey").checked){var c=yield db().catch(function(d){S(d)});if(c){var a="";c&&c.lsauth&&(c=za(!0,b,c.lsauth),a=B(c));yield J.C("key_words",a,!0)}}else yield J.C("key_words",null,!0)})}function eb(){return l(function*(){yield J.Ua();yield C.Pa()})}
function db(){return l(function*(){var b=new FormData;b.append("drive_type","localstorage");b=yield fetch("https://zgayard.f5.si/grantauth.php",{method:"POST",body:b,credentials:"include",redirect:"follow"});if(200==b.status)if(b=yield b.json()){if(b.error)throw"["+b.error+"] "+b.error_description;if(!b.lsauth)throw"lsFailed";}else throw"lsFailed";else throw(yield b.text())+" ("+b.status+")";return b})}
function fb(){return l(function*(){var b=J.Wa();b||(J.Xa(),b=J.Wa(!0));if(!b){b=navigator.language;var c=b.indexOf("-");0<c&&(b=b.substring(0,c))}yield gb(b);r("#txtRelay").value=J.Ra();b=J.mb();if(c=J.Va())r("#chkOwnSecret").click(),r("#txtClientId").value=c.ya,r("#txtClientSecret").value=c.fa;c=r("#selDrive");var a=oa(),d;for(d in Ga){var e=document.createElement("option");e.value=d;e.innerText=Ga[d].A();b?b==d&&(e.selected=!0):a&&a.state==Ga[d].j&&(b=d,e.selected=!0);c.appendChild(e)}J.Y()?(J.l&&
(r("#chkSkipLogin").checked=!0),J.B("key_words")&&(r("#chkSaveKey").checked=!0)):(v("#divSkipLogin"),v("#divSaveKey"));b?yield hb(b):ib()})}function ib(b){var c=r("#divSet"),a=r("#selDrive"),d=r("btnLogout",c,"button.iid");b?(a.disabled=!0,u(d),v(".zb-nav-tools"),v("#divMain")):(a.disabled=!1,v(d));u(c)}
function gb(b){return l(function*(){if(!window.msgs||window.msgs.lang!=b){var c=window.msgs;window.msgs=null;yield bb("msg/"+b+".js");window.msgs?(window.msgs.lang=b,J.Z(b),jb()):(console.log("Message file of '"+b+"' is missing."),c?window.msgs=c:(yield bb("msg/en.js"),window.msgs?(window.msgs.lang="en",J.Z(window.msgs.lang),jb()):S("Message file is missing.")))}})}
function jb(){var b=window.msgs;b.lblConfNotice=b.lblConfNotice.replace("{0}","_zgayard_.conf");var c=q("*"),a;for(a=0;a<c.length;a++){var d=c[a],e=null;d.hasAttribute("iid")&&(e=b[d.getAttribute("iid")])&&(d.innerText=e);!e&&d.hasAttribute("vid")&&(e=b[d.getAttribute("vid")])&&(d.value=e);!e&&d.id&&(e=b[d.id]);e&&("button"==d.type?d.value=e:d.innerText=e);d.hasAttribute("tid")&&(e=b[d.getAttribute("tid")])&&(d.title=e)}c=r("#seLang");a="";for(a in ba)d=document.createElement("option"),d.value=a,
d.innerText=ba[a],a==b.lang&&(d.selected=!0),c.appendChild(d)}function hb(b){return l(function*(){T("loading");var c=Ga[b];if(c){C=new c.g(J,"https://zgayard.f5.si/grantauth.php");var a=yield C.Fa(!0);a?"redirect"!=a&&(yield J.Ua(),S(window.msgs.loginFailed.replace("{0}",a))):(yield J.Ya(),a=r("img",t("div",r("#spanQuota"))),a.src="img/"+b+".png",a.alt=c.A(),(c=yield C.X({U:"_zgayard_.conf"}).catch(function(d){S(JSON.stringify(d))}))&&(0==c.length?kb(!0):yield lb(c[0].j)))}else S("unkDrive")})}
function mb(){return l(function*(){if(r("#chkAgreeTos").checked){var b="",c="";if(r("#chkOwnSecret").checked&&(b=r("#txtClientId").value,c=r("#txtClientSecret").value,!b||!c)){S("noClientIdS");return}var a=r("#selDrive"),d=!1;a.disabled||(d=J.Za(a.value));var e=null;r("#chkOwnSecret").checked&&(e={ya:b,fa:c});J.P(e);J.$a(r("#chkSkipLogin").checked);J.Sa(r("#txtRelay").value);yield gb(r("#seLang").value);d?(J.ba(),yield hb(a.value)):yield J.Ya();nb()}else S("noAgreeTos")})}
function nb(){var b=r("#selDrive");v("#divSet");b.disabled&&(u(".zb-nav-tools"),u("#divMain"))}function ob(b,c){var a=r("#divPwd"),d=!1;b?(a.setAttribute("addroot","1"),d=!0):a.removeAttribute("addroot");b=q("*",a);for(a=0;a<b.length;a++){var e=b[a];e.classList.contains("addroot")?d?u(e):v(e):e.classList.contains("firstep")?d&&c?u(e):v(e):e.classList.contains("chgroot")&&(d?v(e):u(e));"password"==e.type&&(e.value="")}pb()}
function qb(){return l(function*(){if(window.confirm(window.msgs.delConfirm)){T("deleting");var b=r("#selRoot"),c=b.value,a=-1;K.forEach(function(g,k){g.root==c&&(a=k)});if(0<=a){var d=yield C.X({U:K[a].root}).catch(function(g){console.error(g)});d&&(0<d.length&&(yield C.delete({H:d[0].j}).catch(function(g){S(g)})),K.splice(a,1),yield rb())}if(a==L)window.location.reload();else{d=q("option",b);var e=0;for(e=0;e<d.length;e++){var f=d[e];if(f.value==c){b.removeChild(f);break}}a<L&&L--;ab("delrootDone")}}})}
function kb(b){b?"boolean"===typeof b?ob(!0,!0):(ob(),v(".zb-nav-tools"),v("#divMain")):ob();u("#divPwd");R(0)}function sb(b){v("#divPwd");b&&0<M.length&&(u(".zb-nav-tools"),u("#divMain"))}function tb(){var b=w(t("div")),c=b.children[0].cloneNode(!0);c.value="";b.appendChild(c)}function pb(){var b=r("#divfKey");b=q("file",b,"input.type");var c;for(c=b.length-1;0<c;c--)b[c].remove();b[0].value=""}
function ub(){return l(function*(){T("loading");var b=r("#divPwd").hasAttribute("addroot"),c=r("#pwdKey").value,a=q("input",r("#divfKey")),d=[],e,f;for(e=0;e<a.length;e++){var g=a[e].files;for(f=0;f<g.length;f++)d.push(g[f])}if(c||0<d.length){if(b){e=r("#pwdKeyRe").value;if((c||e)&&c!=e){S("diffPwd");return}if(!r("#txtRoot").value){S("noRoot");return}}a="";c&&(a=forge.util.encodeUtf8(c));if(0<d.length){c=ta();f=forge.hmac.create();f.start("sha512","zb12");for(e=0;e<d.length;)g=yield ua(c,d[e].slice(0,
1023)),f.update(wa(new Uint8Array(g))),e++;a+=f.digest().getBytes()}yield vb(a,b)}else S("noPwd")})}
function vb(b,c){return l(function*(){var a=forge.hmac.create();a.start("md5","zgayard");a.update(b);a=B(a.digest().getBytes()).substring(0,8);var d="";if(c){var e={root:r("#txtRoot").value};r("#chkEncryFname").checked&&(e.encfname=!0);var f=!1;K.forEach(function(m){m.root==e.root&&(f=!0)});f?S("dupRoot"):(yield J.C("root",e.root),yield cb(b),d=forge.random.getBytesSync(1024),I=ya(d),e.iv=a.concat(wb(!0,d,b)),L=K.length,K.push(e),xb(e,!0),yield rb(),yield yb())}else{var g=r("#selRoot").value,k=-1;
K.forEach(function(m,n){m.root==g&&(k=n)});0<=k&&K[k].iv&&a==K[k].iv.slice(0,a.length)?(L=k,yield J.C("root",g),yield cb(b),d=wb(!1,K[L].iv.slice(a.length),b),I=ya(d),yield yb()):ka(r("#divPwd"))?S("pwdError"):kb()}})}function wb(b,c,a){a=ya(a);c=b?c:window.atob(va(c));c=za(b,c,a);return b?B(c):c}
function rb(){var b=K;return l(function*(){var c=forge.util.text.utf8.encode(JSON.stringify(b));c=new Ba({xa:new Blob([c],{type:"application/octet-binary"}),V:262144});var a=C.Ia({S:"_zgayard_.conf"});yield Ea(c,a)})}
function lb(b){return l(function*(){var c=new Aa;yield Ea(C.va({j:b}),c);c=forge.util.decodeUtf8(wa(c.A()));c=JSON.parse(c);Array.isArray(c)?K=c:K.push(c);var a=-1,d=J.B("root"),e=r("#selRoot");e.innerHTML="";K.forEach(function(g,k){var m=!1;d&&g.root==d&&(m=!0);xb(g,m,e);m&&(a=k)});if(0<=a){if(L=a,c=J.B("key_words")){var f=yield db().catch(function(g){S(g)});if(f&&f&&f.lsauth&&!f.newkey){c=za(!1,window.atob(va(c)),f.lsauth);yield vb(c);return}}}else L=0;kb()})}
function xb(b,c,a){a=a||r("#selRoot");var d=document.createElement("option");d.value=b.root;d.innerText=b.root;c&&(d.selected=!0);a.appendChild(d)}function zb(){return l(function*(){window.confirm(window.msgs.dropConfirm)&&(yield J.ob().catch(function(b){S(b)}),yield C.Pa())})};var Ab=3;function Bb(b){return new Promise(function(c,a){switch(b){case "new":var d="spanNew";break;case "upload":d="spanUpload";break;case "selfldr":d="spanSelFldr";break;default:return}var e=r("#divModal"),f=r("#spanModal");f.innerText=window.msgs[d];d=q("div",w(f));var g;for(g=0;g<d.length;g++)f=d[g],f.hasAttribute("type")&&(f.getAttribute("type")==b?u(f):v(f));e.h=c;e.l=a;u(e)})}function Cb(b){if(b=t("zb-modal",r(b),"div.class"))b.h&&(b.h(),delete b.h,delete b.l),v(b)}
function Db(b){return l(function*(){var c="",a=q("div",w(r("#spanModal"))),d;for(d=0;d<a.length;d++){var e=a[d];if(e.hasAttribute("type")&&ka(e)){c=e.getAttribute("type");break}}a=!1;switch(c){case "new":a=yield Eb();break;case "upload":c=[];e=r("#upfiles").files;for(d=0;d<e.length;d++)c.push(e[d]);e=r("#upfolder").files;for(d=0;d<e.length;d++)c.push(e[d]);0>=c.length?S("noFiles"):(a=!0,Fb(c));break;case "selfldr":d=r("#divModal"),c=Gb(d),c=la(c,"li",!0).getAttribute("uid"),c!=M[M.length-1].j&&(Cb(b),
d=d.getAttribute("uid"),yield Hb(c,d))}a&&Cb(b)})}function Gb(b){return r(".zb-main-header",b).children[0]}function Ib(b){return r("zb-main-list",b,"ul.class")}function Jb(b){return r("fnm",b,"span.name")}function Kb(b){if(K[L].encfname){var c=I;b=forge.util.encodeUtf8(b);c=za(!0,b,c);c=B(c)}else c=b;return c}function Lb(b){if(K[L].encfname)try{var c=I,a=window.atob(va(b)),d=za(!1,a,c);return forge.util.decodeUtf8(d)}catch(e){console.error(e)}return b}
function Mb(){l(function*(){J=new Fa;yield J.qb().catch(function(){S("IndexedDB is not supported in your browser settings.")});yield fb()})}
function yb(){return l(function*(){[Gb("#divMain"),r("ul","#divHistory")].forEach(function(a){var d=q("li",a);for(a=0;a<d.length;a++)d[a].classList.contains("template")||d[a].remove()});Nb(!1);sb();u(".zb-nav-tools");u("#divMain");var b=yield C.wa({}).catch(function(a){S(a)});if(b){var c=r("#spanQuota");c.setAttribute("total",b.Ma);c.setAttribute("trash",b.Na);Ob(b.oa);b=K[L].root;if((c=yield C.X({U:b}).catch(function(a){S(JSON.stringify(a))}))&&0<c.length)M=[],M.push(c[0]),yield Pb(),yield V(),yield Qb();
else if(b=yield C.ia({K:b}).catch(function(a){S(JSON.stringify(a))}))M=[],M.push(b),yield Pb(),yield V()}})}function Ob(b,c){var a=r("#spanQuota");"string"==typeof b&&(b=parseInt(b,10));var d=x(a,"total"),e=x(a,"trash"),f=0;a.hasAttribute("used")&&(f=x(a,"used"));if(c){if(f-=b,a.setAttribute("used",f),0<d){a.setAttribute("trash",e+b);return}}else f+=b,a.setAttribute("used",f);a.innerText=0<d?window.msgs.quotaInfo.replace("{0}",pa(d-f-e)):window.msgs.quotaInfoU.replace("{0}",pa(f))}
function Nb(b){function c(d,e){d=r(d,a,"div.class");e=r("menuHistory",d,e.concat(".iid"));e=t("li",e);b?u(e):v(e)}var a=r("nav");c("zb-nav-tools","span");c("zb-nav-menu","label")}function Qb(){return l(function*(){if(Q=J.pb()){for(var b=r("ul","#divHistory"),c=0;c<Q.length;){var a=Q[c],d=yield C.ca({aa:a.H}).catch(function(){});d&&(d.J&&(a.K=d.J),Rb(c,Lb(d.o),b));c++}0<Q.length&&Nb(!0)}})}
function Rb(b,c,a){a||(a=r("ul","#divHistory"));b=Q[b];var d=null,e=r(b.K,a,"li.parentId");if(null==e){e=r("template",a,"li.class").cloneNode(!0);e.classList.remove("template");var f=q("span",e),g;for(g=0;g<f.length;g++){var k=f[g];switch(k.getAttribute("name")){case "delete":k.addEventListener("click",Sb);break;case "file":k.addEventListener("click",Tb);d=k;break;case "next":k.addEventListener("click",Ub)}}e.setAttribute("parentId",b.K);a.appendChild(e)}else d=r("file",e,"span.name");d.innerText=
c;b.ha&&(d.innerText=d.innerText.concat(" [").concat(qa(Math.floor(b.ha))).concat("]"))}
function V(b,c,a){return l(function*(){var d=0;if(!a){if(0>=M.length)return null;d=M.length-1;a=M[d]}var e="#divMain";c&&(e="#divModal");var f=0;f=r(e);e=Gb(f);var g=Ib(f);T("loading");var k=W(g);for(f=0;f<k.length;f++)g.removeChild(k[f]);(f=la(e,void 0,!0))&&f.classList.contains("template")&&(f=null);b?f&&f.classList.remove("normal"):(f&&(0!=d||c)&&f.classList.add("normal"),Vb(e,a,d));if(d=yield C.X({v:a.j}).catch(function(p){S(p)})){var m=[],n=0;d.forEach(function(p){var z=0,E=m.length;p.o=Lb(p.o);
for(var F=p.o.split(""),O="",P=0;P<F.length;P++){var U=F[P],D=fa[U];D||(0<=ha.indexOf(U)?D="":(D=U.charCodeAt(0),D=65313<=D&&65338>=D?String.fromCharCode(D-65313+65):65345<=D&&65370>=D?String.fromCharCode(D-65345+65):65296<=D&&65305>=D?String.fromCharCode(D-65296+48):U.toUpperCase()));O+=D}p.Ba=O;for(X(p)?E=n++:z=n;z<E&&!(p.Ba<m[z].Ba)&&!(p.Ba==m[z].Ba&&p.o<m[z].o);)z++;z<m.length?m.splice(z,0,p):m.push(p)});m.forEach(function(p){c&&!X(p)||Wb(g,p)});c||(e=r("#chkAll"),f=t("li",e),r("checkbox",f,"input.type").checked=
!1,v(r("chkbox",f,"span.name")),0<d.length?u(e):v(e));R(0);return m}return null})}function Vb(b,c,a,d){var e=r("template",b,"li.class").cloneNode(!0);r("span",e).innerText=c.o;e.setAttribute("name","folder");e.setAttribute("uid",c.j);e.setAttribute("idx",a);e.addEventListener("click",Xb);e.classList.remove("template");d&&e.classList.add("normal");u(e);b.appendChild(e)}
function Wb(b,c){var a=c.o,d="",e="",f=r("template",b,"li.class").cloneNode(!0);f.classList.remove("template");f.setAttribute("uid",c.j);f.setAttribute("utype",c.M);var g=q("span",f),k;for(k=0;k<g.length;k++){var m=g[k];switch(m.getAttribute("name")){case "fnm":m.innerText=a;m.addEventListener("click",Yb);break;case "icon":if(X(c))A(m,"folder","#FFD679");else{var n=ra(a);ca[n]?A(m,"image","#E7FFE7"):ea[n]?A(m,"video","#FFE7F3"):da[n]?A(m,"audio","#DBFBFD"):A(m,"file","#FFFFB0")}m.addEventListener("click",
Zb);break;case "chkbox":m.addEventListener("click",Zb);v(m);break;case "edit":m.addEventListener("click",$b);break;case "size":d||(d=pa(c.O));m.innerText=d;break;case "tms":e||((e=c.na)?(n=new Date(e),e=n.getFullYear()+"-",e+=n.getMonth()+1+"-",e+=n.getDate()+" ",e+=("0"+n.getHours()).slice(-2)+":",e+=("0"+n.getMinutes()).slice(-2)+":",e+=("0"+n.getSeconds()).slice(-2)):e=""),m.innerText=e}}u(f);b.appendChild(f)}
function ac(b,c){var a=r("checkbox",b,"input.type");1==c?a.checked=!0:-1==c?a.checked=!1:(a.checked=!a.checked,c=a.checked?1:-1);0<c?u(r("chkbox",b,"span.name")):v(r("chkbox",b,"span.name"))}function Zb(){ac(t("li"))}
function Yb(b,c,a){return l(function*(){var d=null,e=!1;if("string"==typeof b)var f=b;else d=t("li"),f=d.getAttribute("uid"),e="selfldr"==t("div",d).getAttribute("type");if(c||!d)d=bc(f,c,a),f=d.getAttribute("uid");f={j:f,o:Jb(d).innerText,M:d.getAttribute("utype")};X(d)?e?yield V(!1,!0,f):(M.push(f),yield V()):cc(f.j,f.o)})}
function Xb(){return l(function*(){for(var b=t("li"),c=t("ul",b),a="selfldr"==t("div",c).getAttribute("type"),d=0,e=w(b);e;)e.tagName==b.tagName&&d++,e=w(e);if(0<d)for(e=0;e<d;e++)c.removeChild(c.lastElementChild);a?yield V(!0,!0,{o:r("span",b).innerText,j:b.getAttribute("uid")}):(d=x(b,"idx"),d<M.length-1&&M.splice(d+1),yield V(!0))})}function X(b){return"1"==(b instanceof HTMLElement?b.getAttribute("utype"):"string"==typeof b?b:b.M)}
function dc(){var b=t("li"),c=r("checkbox",b,"input.type");ac(b);var a=-1;c.checked&&(a=1);b=q("li",t("ul",b));for(c=0;c<b.length;c++)b[c].classList.contains("header")||b[c].classList.contains("template")||ac(b[c],a)}
function $b(b){var c=t("span"),a=c.getBoundingClientRect();c=t("li",c);var d=r("#ulIteMenu");if(d.hasAttribute("ofwid"))var e=parseInt(d.getAttribute("ofwid"),10);else d.style.display="block",e=d.offsetWidth,d.setAttribute("ofwid",e);d.style.left=a.right+e>document.body.offsetWidth?a.left-e+"px":a.right+"px";d.style.top=(document.documentElement.scrollTop||document.body.scrollTop)+a.top+"px";d.setAttribute("uid",c.getAttribute("uid"));d.setAttribute("utype",c.getAttribute("utype"));b.qa=Ab}
function bc(b,c,a){if(!b)return null;var d=Ib("#divMain");d=W(d);var e;for(e=0;e<d.length&&d[e].getAttribute("uid")!=b;e++);if(e>=d.length)return null;switch(c){case 1:for(;0<=e;){e--;if(0>e){if(a)return null;a=!0;e=d.length-1}if(!X(d[e]))break}break;case 2:for(;e<d.length;){e++;if(e>=d.length){if(a)return null;a=!0;e=0}if(!X(d[e]))break}}return d[e]}
function ec(b){return l(function*(){var c=t("li"),a=t("ul",c),d=a.getAttribute("uid");if(d)switch(r("label",c).getAttribute("iid")){case "menuDownload":X(a)?S("noDownFolder"):fc(d);break;case "menuRename":c=r("#divInpName");a=r("input",c);var e=bc(d);d=Jb(e);var f=d.getBoundingClientRect();e=r("edit",e,"span.name").getBoundingClientRect();a.value=d.innerText;c.style.left=f.left+"px";c.style.top=(document.documentElement.scrollTop||document.body.scrollTop)+f.top-2+"px";a.style.width=e.left-f.left+
"px";a.style.height=f.height+2+"px";u(c);a.focus();b.qa=4;break;case "menuMove":yield hc(d);break;case "menuDelete":yield ic(d)}})}function fc(b){var c=bc(b);b={o:Jb(c).innerText,j:b};jc([b])}function hc(b){return l(function*(){var c=r("#divModal");if(b)c.setAttribute("uid",b);else if(kc())c.removeAttribute("uid");else return;c=Gb(c);var a=W(c),d;for(d=0;d<a.length;d++)c.removeChild(a[d]);yield V(!1,!0,M[0]);yield Bb("selfldr")})}
function lc(b){if(13===b.keyCode){if(b.shiftKey||b.ctrlKey||b.altKey)return!0}else return 27===b.keyCode?(v(t("div")),!1):!0;mc();return!1}function mc(){return l(function*(){var b=t("div"),c=r("input",b);if(c.value){var a=r("#ulIteMenu").getAttribute("uid"),d=bc(a);if(d&&(d=Jb(d),c.value!=d.innerText)){var e=Kb(c.value);a={H:a,$:e};try{yield Na(a),d.innerText=c.value,ab("renDone")}catch(f){S(f)}}v(b)}else S("noNewName")})}
function Hb(b,c){return l(function*(){var a=[];c?a.push({j:c,o:""}):a=kc();if(0!=a.length){T("moving");for(var d=!0,e=0;d&&e<a.length;)yield Oa({H:a[e].j,v:b,La:M[M.length-1].j}).catch(function(f){S(f);d=!1}),e++;d&&(yield V(!0,!1),ab("moveDone"))}})}
function ic(b){return l(function*(){var c=null;b?c=[{j:b,o:""}]:c=kc();if(c&&confirm(window.msgs.delConfirm)){T("deleting");for(var a=!0,d=0;a&&d<c.length;){var e=yield C.delete({H:c[d].j}).catch(function(f){S(f);a=!1});e&&Ob(e,!0);d++}a&&(yield V(!0,!1),ab("delDone"))}})}
function Eb(){return l(function*(){var b=r("#fldnm").value;if(!b)return S("noFldName"),!1;var c=r("#chkFInto").checked,a={K:Kb(b)};0<M.length&&(a.v=M[M.length-1].j);return(a=yield C.ia(a).catch(function(d){S(d.da)}))?(a.o=b,c?(M.push(a),yield V(!1,!1)):(Wb(Ib("#divMain"),a),ab("flDone")),!0):!1})}
function kc(b){var c=[],a=W(Ib("#divMain")),d;for(d=0;d<a.length;d++)if(r("checkbox",a[d],"input.type").checked){if(b&&X(a[d]))return S("noDownFolder"),null;c.push({o:Jb(a[d]).innerText,j:a[d].getAttribute("uid")})}return 0>=c.length?(S("noChecks"),null):c}
function cc(b,c){l(function*(){var a=r("#diViewer"),d=t("zb-viewer",a,"div.class"),e=r("title",d,"span.name"),f=r("span",a),g=r("img",a),k=yield nc("video",a),m=yield nc("audio",a);f.innerText=window.msgs.loading;u(f);v(w(f));v(g);e.innerText=c;g.src="";a.setAttribute("uid",b);u(t("zb-modal",d,"div.class"));e=ra(c);a=ca[e];d=ea[e];e=da[e];if(navigator.serviceWorker&&navigator.serviceWorker.controller&&d)k.fid=b,k.g=c,k.src="sw/"+b,u(k),v(f);else if(navigator.serviceWorker&&navigator.serviceWorker.controller&&
e)m.fid=b,m.g=c,m.src="sw/"+b,u(m),g.src="img/logo.png",u(g),v(f);else if(a){k=new Aa;m=new Da({ab:!0,ma:I,cb:C.va({j:b,V:16E4}),fb:k});try{if(yield m.start()){var n=k.A();n instanceof Uint8Array||(n=new Uint8Array(n));a&&(g.src=window.URL.createObjectURL(new Blob([n],{type:a})),u(g),v(f))}else console.log("Not done!")}catch(p){console.log(p)}}else f.innerText=window.msgs.cantView,u(w(f))})}
function oc(b){var c=r(b?b:"#diViewer");c=w(c,"div");var a="";if(b){if(c.style.opacity)return;a="1"}for(;c;)c.style.opacity=a,c=w(c,"div");b&&window.setTimeout(oc,5E3)}function pc(){var b=r("#diViewer").getAttribute("uid");b&&Yb(b,1)}function qc(){var b=r("#diViewer").getAttribute("uid");b&&Yb(b,2)}function rc(b){return l(function*(){yield nc("video",r("#diViewer"));yield nc("audio",r("#diViewer"));Cb(b)})}function sc(){var b=r();b&&b.src&&window.URL.revokeObjectURL(b.src)}
function nc(b,c){return l(function*(){var a=r(b,c),d=a.currentTime;a.src&&(a.removeAttribute("src"),a.load());if(a.fid){navigator.serviceWorker&&navigator.serviceWorker.controller.postMessage({action:3,fid:a.fid});var e=M[M.length-1].j,f=a.g,g;Q||(Q=[]);for(g=0;g<Q.length;g++)if(Q[g].K==e){Q[g].H=a.fid;Q[g].ha=d;break}g==Q.length&&Q.push({H:a.fid,K:e,ha:d});delete a.fid;delete a.g;yield J.lb(Q[g],g);Rb(g,f);Nb(!0)}v(a);return a})}
function tc(b){if((b=b.getAttribute("parentId"))&&Q){var c;for(c=0;c<Q.length;c++)if(Q[c].K==b)return c}return-1}
function Tb(b,c){return l(function*(){r("close","#divHistory","span.name").click();var a=r(b);a=t("li",a);a=tc(a);if(!(0>a)){var d=Q[a];a=d.H;var e=d.K;d=d.ha;T("loading");for(var f=[];e&&e!=M[0].j;){var g=yield C.ca({aa:e}).catch(function(){});g?(g.o=Lb(g.o),f.unshift(g),g.J==M[0].J?e=void 0:e=g.J):e=void 0}if(e==M[0].j){f.unshift(M[0]);e=Gb("#divMain");g=0;var k=q("li",e);for(g=0;g<k.length;g++)k[g].classList.contains("template")||k[g].remove();for(g=0;g<f.length;g++)Vb(e,f[g],g,!0);M=f;if(f=yield V(!0,
!1)){for(e=e=0;e<f.length&&f[e].j!=a;e++);e<f.length&&(c?Yb(a,2):(d&&r("#diViewer").setAttribute("ctime",d),Yb(a)))}}else T("cantPlayRecent")}})}function Ub(b){Tb(b,!0)}function uc(b){b=r(b);var c=t("div",b),a=c.getAttribute("ctime");a&&(c.removeAttribute("ctime"),b.currentTime=a)}function Sb(b){return l(function*(){var c=r(b);c=t("li",c);var a=tc(c);0>a||(c.remove(),Q.splice(a,1),yield J.rb(a),0==Q.length&&Nb(!1))})};const vc=window.Worker?!0:!1;var Y=null;function wc(b){this.h=b;this.g=[];this.l=function(c){return this.h.j==c.j};this.s=function(c){return this.h.o==c};this.m=function(c){var a;for(a=0;a<this.g.length;a++)if(this.g[a].s(c))return this.g[a];return null};this.i=function(c){var a;for(a=0;a<this.g.length;a++)if(this.g[a].l(c))return this.g[a];c=new wc(c);this.g.push(c);return c}}var xc=null;
function W(b,c){var a=[],d=b.getElementsByTagName("li");for(b=0;b<d.length;b++){var e=d[b];if(!e.classList.contains("header")&&!e.classList.contains("template"))if(c){var f=c(e);2!=f&&-2!=f||a.push(e);if(0>f)break}else a.push(e)}return a}function yc(b){b=r(b);v(b);Y?(b=t("li",b),b={type:9,rowIdx:x(b,"rowIdx")},Y.postMessage(b)):b.setAttribute("canceled","1")}
function zc(b,c,a){var d=0,e=0;c||(c=r(".zb-qbutton"));!a&&c.hasAttribute("count")&&(a=x(c,"count"));c.hasAttribute("fincount")&&(d=x(c,"fincount"));c.hasAttribute("stopcount")&&(e=x(c,"stopcount"));switch(b){case 1:d++;c.setAttribute("fincount",d);break;case 3:c.setAttribute("haserr","1");case 2:e++,c.setAttribute("stopcount",e)}0<a?r("div",c).style.width=Math.floor(100*d/a)+"%":r("div",c).style.width="0%";a==d+e&&(c.hasAttribute("haserr")?c.classList.add("error"):c.classList.add("done"))}
function Ac(b){var c=r(".zb-qbutton"),a=0;c.hasAttribute("count")&&(a=x(c,"count"));a+=b;c.setAttribute("count",a);zc(0,c,a);c.classList.contains("error")&&c.classList.remove("error");c.classList.contains("done")&&c.classList.remove("done");u(c)}
function Bc(b){b=t(".zb-queue",r(b));var c=r(".zb-qbutton");b.style.top="100%";if(c.classList.contains("done")||c.classList.contains("error")){v(c);c.removeAttribute("count");c.removeAttribute("fincount");c.removeAttribute("stopcount");c.removeAttribute("haserr");b=r("ul",b);c=W(b);var a;for(a=c.length-1;0<=a;a--)b.removeChild(c[a]);b.removeAttribute("rowCount")}}
function Cc(b,c,a){var d=0;b.hasAttribute("rowCount")&&(d=x(b,"rowCount"));var e=r("template",b,"li.class").cloneNode(!0);e.classList.remove("template");e.setAttribute("rowIdx",d);a&&e.setAttribute("downFl",1);b.setAttribute("rowCount",d+1);d=q("span",e);var f;for(f=0;f<d.length;f++){var g=d[f];switch(g.getAttribute("name")){case "cancel":g.addEventListener("click",yc);break;case "icon":r("label",g).innerText=c;a?A(g,"download"):A(g,"upload");break;case "elTime":la(g,"label").innerText=window.msgs.elTime;
break;case "esTime":la(g,"label").innerText=window.msgs.esTime;break;case "speed":g.innerText=window.msgs.waiting}}b.appendChild(e);return e}function Dc(b,c){c||(c=r("ul","#divQueue"));c=W(c,function(a){return a.getAttribute("rowIdx")==b?-2:1});return 0<c.length?c[0]:null}function Ec(b,c){var a=0;if(1==b)a=1;else if(2!=b)return;b=q("svg",".zb-qbutton")[a];c?b.classList.add("pulse"):b.classList.remove("pulse")}
function Fc(b,c){var a=null,d=q("span",b),e="";switch(c.type){case 0:e="0%";Ec(c.wtype,!0);break;case 1:e=Math.round(100*c.posn/c.size)+"%";break;case 2:e="100%";case 3:Ec(c.wtype)}var f;for(f=0;f<d.length;f++){var g=d[f];switch(g.getAttribute("name")){case "icon":a=g;break;case "percent":switch(c.type){case 0:case 1:g.innerText=e;break;case 2:c.errr||(g.innerText=e)}break;case "elTime":switch(c.type){case 1:case 2:case 3:g.innerText=qa(Math.floor((Date.now()-c.begin)/1E3))}break;case "esTime":switch(c.type){case 1:g.innerText=
qa(Math.round((c.size-c.posn)/c.spd))}break;case "speed":switch(c.type){case 1:g.innerText=pa(c.spd)+"/s";break;case 2:case 3:c.errr||(b.classList.add("done"),g.innerText=window.msgs.avspeed.replace("{0}",pa(1E3*c.posn/(Date.now()-c.begin))))}break;case "cancel":switch(c.type){case 0:u(g);break;case 2:case 3:var k=r("svg",g);k.removeChild(k.firstElementChild);c.errr||3==c.type?(A(g,"multi"),zc(c.errr?3:2)):(A(g,"chkbox",void 0,"#10B981"),zc(1));u(g)}break;default:if((k=t("div",g))&&k.classList.contains("zb-progressbar"))switch(c.type){case 0:case 1:g.style.width=
e;break;case 2:c.errr?(b.classList.add("error"),k.innerText=c.errr):g.style.width=e}}}return a}function Gc(b,c){switch(c.type){case 0:case 1:Fc(b,c);break;case 2:c.fined&&Y&&Hc();b=Fc(b,c);c.errr||(2==c.wtype?Ob(c.size):1==c.wtype&&c.blob&&(b=r("label",b).innerText,ma(c.blob,b,r("#lnkDown"))));window.gc&&window.gc();break;case 3:c.fined&&Y&&Hc(),Fc(b,c),window.gc&&window.gc()}}function Hc(){var b=Y;xc=Y=null;b.terminate();b.g&&V(!0)}
function Ic(b){Y||(Y=new Worker("worker.js"),Y.h={gtoken:C.h?C.h:"",iv:B(I.iv),key:B(I.key),drvid:C.m(),encfname:K[L].encfname?!0:!1},Y.addEventListener("message",function(c){c=c.data;var a=Dc(c.rowIdx);Gc(a,c)}));b.cominf=Y.h;2!=b.type||Y.g||(Y.g=!0);Y.postMessage(b)}function Jc(b){var c=x(b,"rowIdx"),a=r("cancel",b,"span.name");return new $a(function(){return a.getAttribute("canceled")?!0:!1},function(d){d.rowIdx=c;Gc(b,d)})}
function jc(b){l(function*(){var c=r("ul","#divQueue"),a;Ac(b.length);for(a=0;a<b.length;a++){var d=Cc(c,b[a].o,!0);vc?Ic({type:1,rowIdx:x(d,"rowIdx"),downinf:{targetId:b[a].j}}):b[a].J=d.getAttribute("rowIdx")}if(!vc)for(a=0;a<b.length;)d=Dc(parseInt(b[a].J,10),c),yield Jc(d).A(b[a].j),a++})}
function Fb(b){l(function*(){var c=r("ul","#divQueue"),a=[],d;Ac(b.length);for(d=0;d<b.length;d++){var e=b[d].webkitRelativePath?b[d].webkitRelativePath:b[d].name;var f=Cc(c,e);a.push({sb:e,bb:b[d],la:x(f,"rowIdx")})}xc||(xc=new wc(M[0]));e=xc;for(d=1;d<M.length;d++)e=e.i(M[d]);for(d=0;d<a.length;){f=a[d];var g=yield Kc(e,f.sb);d++;if(vc)Ic({type:2,rowIdx:f.la,upinf:{fname:g.S,file:f.bb,ptid:g.N}});else{var k=Dc(f.la,c);yield Jc(k).C(g.S,f.bb,g.N)}}vc||V(!0)})}
function Kc(b,c){return l(function*(){var a=c.split("/"),d=Kb(a.pop()),e=b;if(0==a.length)return{S:d,N:e.h.j};for(var f=0;f<a.length;){var g=a[f],k=Kb(g);f++;var m=e.m(g);m?e=m:(m=yield C.X({U:k,v:e.h.j}),0==m.length?(k=yield C.ia({K:k,v:e.h.j}),k.o=g,e=e.i(k)):(m[0].o=g,e=e.i(m[0])))}return{S:d,N:e.h.j}})};function Lc(b){return l(function*(){var c=b.data;switch(c.action){case 1:c.cominf={gtoken:C.h?C.h:"",iv:B(I.iv),key:B(I.key),drvid:C.m(),encfname:K[L].encfname?!0:!1};navigator.serviceWorker.controller.postMessage(c);break;case 2:c.msg&&(console.error(c.msg),S(c.msg))}})}
function Pb(){return l(function*(){if(navigator.serviceWorker){yield navigator.serviceWorker.register("sw.js");yield navigator.serviceWorker.ready;navigator.serviceWorker.addEventListener("message",Lc);var b=r("btnUnregSw",void 0,"button.iid");u(b);return!0}return!1})}
function Mc(){return l(function*(){if(!navigator.serviceWorker)return console.error("no service worker"),!1;var b=yield navigator.serviceWorker.getRegistration();if(!b)return console.error("no service worker registration"),!1;if(!window.confirm(window.msgs.unswConfirm))return!1;(b=yield b.unregister())&&console.debug("service worker uninstalled.");var c=r("btnUnregSw",void 0,"button.iid");v(c);return b})};var Z=null;function Nc(b){switch(b){case 1:b=r(".zb-nav-tools");b={T:r("button",b),L:w(b)};break;case 2:b=r("button",r(".zb-main-header","#divMain"));b={T:b,L:w(b)};break;case Ab:b={L:r("#ulIteMenu")};break;default:return null}return b}function Oc(b){var c=Nc(b);c&&(c.L.style.display="none",c.L.style.maxHeight="0px",c.T&&c.T.addEventListener("click",function(a){a.qa=b}))}
function Pc(b,c){var a=Nc(c);a&&(a.L.style.display?a.L.style.maxHeight&&b.qa==c&&(u(a.L),a.T&&(v(a.T.children[0]),u(a.T.children[1])),window.setTimeout(function(){a.L.style.maxHeight="";a.L.style.paddingTop="";a.L.style.paddingBottom=""},50)):a.L.style.maxHeight||b.qa==c&&!a.T||(a.L.style.paddingBottom="0px",a.L.style.maxHeight="0px",window.setTimeout(function(){a.T&&(u(a.T.children[0]),v(a.T.children[1]));a.L.style.paddingTop="0px";v(a.L)},500)))}
function Qc(b){Pc(b,1);Pc(b,2);Pc(b,Ab);4!=b.qa&&v("#divInpName")}function Rc(b){b=b.target||b.srcElement;"INPUT"!=b.tagName&&(b=r("input",t("div",b)),b.focus(),b.click())}function Sc(b){var c=t("li",b);switch(b.getAttribute("iid")){case "menuGeneral":c.addEventListener("click",ib);break;case "menuDrive":c.addEventListener("click",kb);break;case "menuHistory":c.addEventListener("click",function(){r("#divHistory").style.top=""})}}
function Tc(){return l(function*(){var b=r("label",t("li")),c=b.getAttribute("iid");b=w(b);switch(c){case "menuNewFldr":b&&b.classList.add("rotate-90");yield Bb("new");b&&b.classList.remove("rotate-90");break;case "menuUpload":b&&b.classList.add("rotate-90");yield Bb("upload");r("#upfiles").value=null;r("#upfolder").value=null;b&&b.classList.remove("rotate-90");break;case "menuMovefs":b&&b.classList.add("rotate-90");yield hc();b&&b.classList.remove("rotate-90");break;case "menuDownfs":(b=kc(!0))&&
jc(b);break;case "menuDelfs":yield ic()}})}function Uc(b,c){b=r(b,c);b.addEventListener("canplay",uc);b.addEventListener("ended",function(){Yb(t("div").getAttribute("uid"),2,!0)})}
window.addEventListener("load",function(){var b=RegExp("android","i").test(navigator.userAgent),c=r("#divMessage"),a=q("span",c);a[a.length-1].children[0].addEventListener("click",function(){R(0)});document.addEventListener("click",Qc);Oc(1);Oc(2);Oc(Ab);var d=0;c=0;a=q("span",r(".zb-nav-tools"));for(d=0;d<a.length;d++)Sc(a[d]);a=q("label",r(".zb-nav-menu"));for(d=0;d<a.length;d++)Sc(a[d]);a=q(".zb-settings");for(d=0;d<a.length;d++){var e=q(".checkbox",a[d]);for(c=0;c<e.length;c++)e[c].addEventListener("click",
Rc)}r("#chkOwnSecret").addEventListener("click",function(f){f=f.target||f.srcElement;var g=q(".ownsecret","#divSet"),k;for(k=0;k<g.length;k++)f.checked?u(g[k]):v(g[k])});c=r("#divSet");a=q("button",c);for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("iid")){case "btnLogout":c.addEventListener("click",eb);break;case "btnCancel":c.addEventListener("click",nb);break;case "btnOk":c.addEventListener("click",mb)}a=q("span",r("#divPwd"));for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("tid")){case "spanAddRoot":c.addEventListener("click",
ob);break;case "spanDeleteRoot":c.addEventListener("click",qb);break;case "spanMoreKey":b?c.addEventListener("click",tb):c.style.display="none";break;case "spanClearKey":b?c.addEventListener("click",pb):c.style.display="none"}a=q("button",r("#divPwd"));for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("iid")){case "btnCancel":c.addEventListener("click",sb);break;case "btnOk":c.addEventListener("click",ub);break;case "btnDropDb":c.addEventListener("click",zb);break;case "btnUnregSw":c.addEventListener("click",
Mc)}c=r("#divModal");c.addEventListener("click",Cb);c.children[0].addEventListener("click",function(f){f.stopPropagation()});a=q("button",c);for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("iid")){case "btnCancel":c.addEventListener("click",Cb);break;case "btnOk":c.addEventListener("click",Db)}a=q(".zb-main-menu");for(d=0;d<a.length;d++)for(b=q("li",a[d]),c=0;c<b.length;c++)b[c].addEventListener("click",Tc);c=r("#chkAll");c.addEventListener("click",dc);w(c).addEventListener("click",dc);a=q("li",
"#ulIteMenu");for(d=0;d<a.length;d++)a[d].addEventListener("click",ec);c=r("#divInpName");c.addEventListener("click",function(f){f.stopPropagation()});r("input",c).addEventListener("keyup",lc);r("span",c).addEventListener("click",mc);c=r("#diViewer");c.addEventListener("click",oc);c.addEventListener("touchstart",function(f){Z||1!=f.changedTouches.length||(f=f.changedTouches[0],Z={j:f.identifier,vb:f.screenX,wb:f.screenY})});c.addEventListener("touchend",function(f){if(Z){var g=null,k;for(k=0;k<f.changedTouches.length;k++)if(f.changedTouches[k].identifier==
Z.j){g=f.changedTouches[k];break}g&&(f=g.screenX-Z.vb,g=g.screenY-Z.wb,10>g&&-10<g&&(50<f?pc():-50>f&&qc()));Z=null}});r("button",c).addEventListener("click",function(){fc(t("div").getAttribute("uid"))});r("img",c).addEventListener("load",sc);Uc("audio",c);Uc("video",c);document.addEventListener("fullscreenchange",function(){document.fullscreen?r("#diViewer").classList.add("full"):r("#diViewer").classList.remove("full")});c=t("zb-viewer",c,"div.class");a=q("span",c);for(d=0;d<a.length;d++)switch(a[d].getAttribute("name")){case "close":a[d].addEventListener("click",
rc);break;case "previous":a[d].addEventListener("click",pc);break;case "next":a[d].addEventListener("click",qc);break;case "fullscreen":a[d].addEventListener("click",function(){t("div","#diViewer",void 0,!0).requestFullscreen()})}c=t("zb-modal",c,"div.class");c.addEventListener("click",rc);c.children[0].addEventListener("click",function(f){f.stopPropagation()});r(".zb-qbutton").addEventListener("click",function(){r("#divQueue").style.top=""});r("close","#divQueue","span.name").addEventListener("click",
Bc);r("close","#divHistory","span.name").addEventListener("click",function(){r("#divHistory").style.top="100%"});Mb()});
