var h;function aa(b){function c(d){return b.next(d)}function a(d){return b.throw(d)}return new Promise(function(d,e){function f(g){g.done?d(g.value):Promise.resolve(g.value).then(c,a).then(f,e)}f(b.next())})}function k(b){return aa(b())};const ba={en:"English",ja:"日本語"},da={bmp:"image/bmp",gif:"image/gif",jpe:"image/jpeg",jpeg:"image/jpeg",jpg:"image/jpeg",png:"image/png",webp:"image/webp"},ea={aac:"audio/aac",mp3:"audio/mpeg",wav:"audio/wav"},fa={avi:"video/x-msvideo",mp4:"video/mp4",mpeg:"video/mpeg"};function ha(b,c){var a="",d="";if(c){d=c.indexOf(".");0<=d&&(a=c.substring(0,d).toUpperCase(),c=c.slice(d+1));switch(c.toLowerCase()){case "id":c="#";break;case "class":c="."}d=b}else c=b.charAt(0),"#"==c||"."==c?d=b.slice(1):(c="",a=b.toUpperCase());return{ga:a,o:c,pa:d}}function ia(b,c){return"#"==c.o?b.id==c.pa:"."==c.o?b.classList.contains(c.pa):c.o?b.getAttribute(c.o)==c.pa:!0}
function q(b,c,a){var d=[],e=document;c&&("string"==typeof c?(c=q(c),0<c.length&&(e=c[0])):e=c);a=ha(b,a);if(!a.ga)if("#"==a.o)d.push(document.getElementById(a.pa));else if("."==a.o)for(c=e.getElementsByClassName(a.pa),b=0;b<c.length;b++)d.push(c[b]);else a.ga="*";if(a.ga)for(e=e.getElementsByTagName(a.ga.toLowerCase()),b=0;b<e.length;b++)ia(e[b],a)&&d.push(e[b]);return d}
function r(b,c,a){var d=null;b?"string"==typeof b?(b=q(b,c,a),0<b.length&&(d=b[0])):b instanceof Event?d=b.currentTarget||b.srcElement||b.target:d=b:d=window.event.currentTarget||window.event.srcElement||window.event.target;return d}function t(b,c,a,d){var e=null;c?"string"==typeof c?e=r(c):e=c:e=r();d&&(e=e.parentElement);for(b=ha(b,a);e&&(e.tagName!=b.ga&&b.ga||!ia(e,b));)e=e.parentElement;return e}function ja(b){return!!(b.offsetWidth||b.offsetHeight||b.getClientRects().length)}
function u(b){(b=r(b))&&b.style.display&&(b.style.display="")}function v(b){if(b=r(b))b.style.display="none"}function w(b,c){if((b=b.nextElementSibling)&&c)switch(c.charAt(0)){case "#":for(c=c.slice(1);b&&b.id!=c;)b=b.nextElementSibling;break;default:for(c=c.toUpperCase();b&&b.tagName!=c;)b=b.nextElementSibling}return b}
function ka(b,c,a){if((b=a?b.lastElementChild:b.previousElementSibling)&&c)switch(c.charAt(0)){case "#":for(c=c.slice(1);b&&b.id!=c;)b=b.previousElementSibling;break;default:for(c=c.toUpperCase();b&&b.tagName!=c;)b=b.previousElementSibling}return b}function x(b,c){return parseInt(b.getAttribute(c),10)}
function la(b,c,a){if(window.navigator.msSaveBlob)window.navigator.msSaveBlob(b,c);else if(a)a.download=c,a.href=window.URL.createObjectURL(b),a.click();else throw Error("Element for download is not specified.");}function ma(b){if(!b)return null;var c=b.charAt(0);if("?"==c||"#"==c)b=b.substring(1);var a={};b.split("&").forEach(function(d){var e=d.indexOf("=");0>e?a[decodeURIComponent(d)]="":a[decodeURIComponent(d.substring(0,e))]=decodeURIComponent(d.substring(e+1))});return a}
function na(){var b=ma(window.location.search),c=ma(window.location.hash);c&&(b=b?Object.assign(b,c):c);return b}function y(b,c){var a=[],d;for(d in b)c?a.push(d.concat("=").concat(b[d])):a.push(encodeURIComponent(d).concat("=").concat(encodeURIComponent(b[d])));return 0<a.length?"?".concat(a.join("&")):""}
function A(b,c,a,d){var e=r("svg",b),f=document.createElementNS("http://www.w3.org/2000/svg","use");f.setAttributeNS("http://www.w3.org/1999/xlink","xlink:href","#".concat(c));e||(e=document.createElementNS("http://www.w3.org/2000/svg","svg"),b.appendChild(e));e.appendChild(f);a&&(e.style.fill=a);d&&(e.style.stroke=d)}
function B(b){if(b)if(1024>b)var c="B";else 1048576>b?(c="KB",b=Math.round(b/102.4)/10):1073741824>b?(c="MB",b=Math.round(b/104857.6)/10):(c="GB",b=Math.round(b/1.073741824E8)/10);else c="B",b=0;var a=b.toString();b=a.indexOf(".");var d=a.split(""),e=[];0<=b?e.push(a.slice(b)):b=d.length;for(a=0;0<b;)3==a++&&(e.unshift(","),a=1),e.unshift(d[--b]);return e.join("").concat(c)}
function oa(b){var c=b%60;b=(b-c)/60;var a=b%60;b=(b-a)/60;var d=[];0<b&&d.push(b.toString(10));d.push("0".concat(a).slice(-2));d.push("0".concat(c).slice(-2));return d.join(":")}function pa(b){var c=b.lastIndexOf("."),a="";0<=c&&(a=b.slice(c+1));return a.toLowerCase()}function qa(){return new Promise(function(b){setTimeout(b,500)})};function ra(){var b=new FileReader;b.addEventListener("load",function(c){c.target.m&&c.target.m(c.target.result)});b.addEventListener("error",function(c){c.target.i&&c.target.i(c.target.error)});return b}FileReader.prototype.m=void 0;FileReader.prototype.i=void 0;function sa(b,c){return new Promise(function(a,d){b.m=a;b.i=d;b.readAsArrayBuffer(c)})}function ta(b){b=b.replace(/-/g,"+").replace(/_/g,"/");var c=b.length%4;0<c&&(b+="====".slice(c));return b}
function C(b){return window.btoa(b).replace(/\+/g,"-").replace(/\//g,"_").replace(/=*$/g,"")}function ua(b){for(var c=[],a=0;a<b.length;)c.push(String.fromCharCode(b[a])),a++;return c.join("")}function va(b){for(var c=new Uint8Array(b.length),a=0;a<b.length;a++)c[a]=b.charCodeAt(a);return c}
function E(b){var c=forge.md.md5.create();c.update(b);c=c.digest().getBytes();for(var a=forge.md.md5.create(),d=new forge.util.ByteStringBuffer,e="";48>d.length();)a.start(),e&&a.update(e),a.update(b),a.update(c),e=a.digest().getBytes(),d.putBytes(e);d.truncate(d.length()-48);return{key:d.getBytes(32),iv:d.getBytes()}}
function wa(b,c,a){var d=a;"string"==typeof a&&(d=E(a));if(!(d&&d.iv&&d.key))throw Error("Need iv and key. They can be generated by computeEvpKDF from password and salt.");a=forge.util.createBuffer(d.key);b=b?forge.cipher.createCipher("AES-CBC",a):forge.cipher.createDecipher("AES-CBC",a);b.start({iv:d.iv});b.update(forge.util.createBuffer(c));b.finish();return b.output.getBytes()}
function xa(){this.h=0;this.g=null;this.i=function(b){const c=this;return k(function*(){c.h=b})};this.write=function(b){const c=this;return k(function*(){c.g||(c.g=[]);c.g.push(b);b=null})};this.cancel=function(){return k(function*(){})};this.A=function(){if(this.g&&0<this.g.length&&(this.g[0]instanceof ArrayBuffer||this.g[0]instanceof Uint8Array)){for(var b=0,c=0;c<this.g.length;c++)b+=this.g[c].byteLength;b=new Uint8Array(b);var a=0;for(c=0;c<this.g.length;++c){var d=this.g[c];d instanceof ArrayBuffer&&
(d=new Uint8Array(d));b.set(d,a);a+=d.byteLength}return b}return null};this.u=function(){var b=this.A();b instanceof Uint8Array||(b=new Uint8Array(b));return new Blob([b],{type:"application/octet-binary"})};this.download=function(b){var c=this.u();la(c,b,null)};this.B=function(){return this.h}}
function ya(b){this.blob=null;if(b.xa)if(b.xa instanceof Blob)this.blob=b.xa;else throw Error("blob is not a Blob.");else throw Error("blob must be specified.");this.l=1600;b.V&&(this.l=b.V);this.h=0;this.i=null;this.B=function(c){const a=this;return k(function*(){if(c){if(c>=a.g())throw Error("offset can not be bigger than input size.");a.h=c}else a.h=0;a.i=ra()})};this.ba=function(){return this.l};this.m=function(){return this.h};this.g=function(){return this.blob.size};this.s=function(){return this.h>=
this.g()};this.C=function(c){const a=this;return k(function*(){if(1==a.i.readyState)return null;var d=a.h;a.h=c?a.h+c:a.h+a.l;return yield sa(a.i,a.blob.slice(d,a.h))})};this.R=function(){this.blob=this.i=null}}
function za(b){this.s=!0;this.g=b.bb;this.iv=this.key="";this.m=null;this.h="";this.l=this.i=0;b.$a&&(this.s=!1);if(!this.g)throw Error("reader must be specified.");if(b.ma)b="string"==typeof b.ma?E(b.ma):b.ma,this.key=b.key,this.iv=b.iv;else throw Error("keycfg must be specified.");this.P=function(){const c=this;return k(function*(){if(c.l)return c.l;if(c.s)return c.l=16*Math.ceil((c.g.g()+1)/16),c.l;0==c.g.g()&&(yield c.u());var a=c.g.g()-16,d=yield c.F(a);c.l=a+d.length;return c.l})};this.u=function(c){const a=
this;return k(function*(){var d=c||0;if(c){if(a.s)throw Error("Can NOT set offset for encryption.");c-=c%16+16;0>c&&(c=0)}yield a.g.B(c);var e=a.iv;d&&(e=yield a.B(16));var f=forge.util.createBuffer(a.key);a.m=a.s?forge.cipher.createCipher("AES-CBC",f):forge.cipher.createDecipher("AES-CBC",f);a.m.start({iv:e});a.i=d;a.h=""})};this.F=function(c){const a=this;return k(function*(){var d=a.g.ba(),e="",f=0<=c?c:a.g.m();if(a.i==f&&a.h){if(d<=a.h.length)return a.i+=d,e=a.h.substring(0,d),a.h=a.h.substring(d),
e;e=a.h;f+=a.h.length;a.i+=a.h.length;d-=a.h.length}var g=16*Math.ceil((f%16+d)/16);a.m&&a.i==f||(yield a.u(f));var l=yield a.B(g);a.m.update(forge.util.createBuffer(l));a.g.s()&&a.m.finish();g=a.m.output.getBytes();f<a.g.m()?(f-=a.g.m()-l.length,0<f&&(g=g.substring(f)),g.length>d&&(a.h=g.substring(d),g=g.substring(0,d)),a.i+=d):g="";e?g&&(e=e.concat(g)):g&&(e=g);return e})};this.C=function(){return this.g.m()};this.D=function(){return this.g.s()};this.R=function(){this.g.R();this.m=this.g=null};
this.A=function(){return this.g.A()};this.B=function(c){const a=this;return k(function*(){var d=yield a.g.C(c);return ua(new Uint8Array(d))})}}
function Aa(b){this.g=new za(b);this.h=b.eb;this.speed=this.m=this.i=0;if(!this.h)throw Error("writer must be specified.");this.start=function(c,a){const d=this;return k(function*(){var e=c||0,f=yield d.g.P();yield d.h.i(f);yield d.g.u(c);d.i=Date.now()+1E3;d.m=e;for(e=d.g.D()?2:0;0==e;)(f=yield d.g.F())&&(yield d.h.write(va(f))),d.g.D()?e=2:a&&!a()&&(e=1);1==e&&(yield d.h.cancel());d.h=null;d.g.R();d.g=null;return 2==e})};this.l=function(){Date.now()>this.i&&(this.speed=1E3*(this.g.C()-this.m)/(Date.now()-
this.i+1E3),this.i=Date.now()+1E3,this.m=this.g.C());return this.speed}}function Ba(b,c){return k(function*(){yield b.B(0);yield c.i(b.g());for(var a=0;0==a;){var d=yield b.C();yield c.write(d);b.s()&&(a=2)}return 1==a?(yield c.cancel(),!1):!0})};function Ca(){this.A=!0;this.h=this.g=null;this.l=this.D=!1;this.m=-1;this.Y=function(){return null!=this.g};this.ba=function(b){if(this.A)try{var c=window.sessionStorage.getItem("language"),a=window.sessionStorage.getItem("relay_url"),d=window.sessionStorage.getItem("drive"),e=window.sessionStorage.getItem("drive_extra"),f=window.sessionStorage.getItem("skipLogin");window.sessionStorage.clear();c&&window.sessionStorage.setItem("language",c);a&&!b&&window.sessionStorage.setItem("relay_url",a);d&&
!b&&window.sessionStorage.setItem("drive",d);e&&!b&&window.sessionStorage.setItem("drive_extra",e);f&&!b&&window.sessionStorage.setItem("skipLogin",f)}catch(g){this.A=!1,console.error(g)}};this.s=function(b){var c=null;if(this.A)try{c=window.sessionStorage.getItem(b)}catch(a){this.A=!1,console.error(a)}return c};this.Sa=function(b){var c=this.s("login_state");return c&&b==c?!0:!1};this.u=function(b,c){if(this.A)try{return window.sessionStorage.setItem(b,c.toString()),!0}catch(a){this.A=!1,console.error(a)}return!1};
this.F=function(b){if(this.A)try{window.sessionStorage.removeItem(b)}catch(c){this.A=!1,console.error(c)}};this.Wa=function(){var b=this.s("language"),c=this.s("relay_url"),a=this.s("drive"),d=this.s("drive_extra"),e=this.s("skipLogin");this.h={};b&&(this.h.language=b,this.Z(b));c&&(this.h.ta=c,this.Ra(c));a&&(this.h.I=a,this.Ya(a));d&&(this.h.gb=d,this.P(d));e&&this.Za(e)};this.lb=function(){var b=this.i("drive");b||(this.h||this.Wa(),b=this.h.I);return b};this.Ya=function(b){return this.Ga("drive",
b)?(this.g[b]||(this.g[b]={}),!0):this.g?!1:!0};this.Za=function(b){b?this.l=this.Y():(this.l=!1,this.mb()&&(this.D=!0));this.u("skipLogin",this.l)};this.Va=function(b){var c=this.i("language");!c&&b&&this.h&&(c=this.h.language);return c};this.Z=function(b){this.Ga("language",b)};this.Qa=function(){var b=this.i("relay_url");!b&&this.h&&(b=this.h.ta);return b?b:""};this.Ra=function(b){this.Ga("relay_url",b)};this.Ua=function(){var b=null,c=this.B("extra_info");!c&&this.h&&this.h.gb&&(c=this.h.gb);
c&&(b=JSON.parse(c));return b&&2==b.length?{ya:b[0],fa:b[1]}:null};this.P=function(b){b?(b="string"===typeof b?b:JSON.stringify([b.ya,b.fa]),this.u("drive_extra",b),this.C("extra_info",b)):(this.F("drive_extra"),this.C("extra_info",null))};this.pb=function(){var b=this;return new Promise(function(c,a){if(window.indexedDB){var d=window.indexedDB.open("zgayard1946");d.onerror=function(e){a(e.target.error)};d.onupgradeneeded=function(e){e.target.result.createObjectStore("settings",{keyPath:"key"})};
d.onsuccess=function(e){var f=e.target.result;e=f.transaction("settings","readwrite");e.oncomplete=function(){f.close();c()};e.objectStore("settings").getAll().onsuccess=function(g){b.g={};g.target.result.forEach(function(l){b.g[l.key]=l.value});g=b.g.drive;b.l=g&&b.g[g]&&b.g[g].refresh_token?!0:!1}}}else a(Error("IndexedDB is not supported in your browser settings."))})};this.nb=function(){var b=this;return new Promise(function(c,a){var d=window.indexedDB.deleteDatabase("zgayard1946");d.onerror=
function(e){console.error("Failed to dropt IndexedDB.");a(e.target.error)};d.onsuccess=function(){b.ba(!0);b.g=null;b.l=!1;console.log("IndexedDB has been dropped.");c()}})};this.Xa=function(){const b=this;return k(function*(){b.D&&b.g&&(yield b.R(function(c){c.clear().onsuccess=function(){for(var a in b.g)c.put({key:a,value:b.g[a]})}}),b.D=!1)})};this.B=function(b){var c=this.i("drive");return c&&(c=this.g[c])?c[b]:null};this.mb=function(){var b=this.i("drive");return b&&(b=this.g[b])&&b.refresh_token?
(delete b.refresh_token,!0):!1};this.C=function(b,c,a){const d=this;return k(function*(){if(d.g){var e=d.i("drive");if(c)d.g[e]||(d.g[e]={}),d.g[e][b]=c;else if(d.g[e]&&d.g[e][b])delete d.g[e][b];else return;a?yield d.R(function(f){f.put({key:e,value:d.g[e]})}):d.D=!0}})};this.Ta=function(){const b=this;return k(function*(){b.ba(!0);if(b.g){var c=b.i("drive");delete b.g[c].refresh_token;delete b.g.drive;yield b.R(function(a){a.put({key:c,value:b.g[c]});a.delete("drive")})}})};this.kb=function(b,c){const a=
this;return k(function*(){var d=a.i("recent");d||(d=[]);0>a.m&&(d.push({drive:a.i("drive"),root:a.B("root"),played:[]}),a.m=d.length-1);var e=d[a.m],f={fid:b.H,time:b.ha};0<=c&&c<e.played.length?e.played[c]=f:e.played.push(f);yield a.saveData("recent",d)})};this.ob=function(){var b=this.i("recent");this.m=-1;if(b){var c=0;for(c=0;c<b.length;c++){var a=b[c];if(a.drive==this.i("drive")&&a.root==this.B("root")){this.m=c;break}}}if(0<=this.m){var d=[];b[this.m].played.forEach(function(e){d.push({H:e.fid,
K:"",ha:e.time})});return d}return null};this.qb=function(b){const c=this;return k(function*(){var a=c.i("recent");if(a&&!(0>c.m)){var d=a[c.m].played;b<d.length&&(d.splice(b,1),yield c.saveData("recent",a))}})};this.R=function(b){return new Promise(function(c,a){var d=window.indexedDB.open("zgayard1946");d.onerror=function(e){a(e.target.error)};d.onsuccess=function(e){var f=e.target.result;e=f.transaction("settings","readwrite");e.oncomplete=function(){f.close();c()};e=e.objectStore("settings");
b&&b(e)}})};this.Ga=function(b,c){if(c){if(this.u(b,c),this.g&&this.g[b]!=c)return this.g[b]=c,this.D=!0}else if(this.F(b),this.g&&this.g[b])return delete this.g[b],this.D=!0;return!1};this.i=function(b){return this.g&&this.g[b]?this.g[b]:null};this.saveData=function(b,c){const a=this;return k(function*(){a.g&&(a.g[b]=c);yield a.R(function(d){d.put({key:b,value:c})})})}};var Da={};function Ea(b,c,a){this.j=b;this.o=c;this.g=a}Ea.prototype.A=function(){return this.o};function Ga(b,c){this.ta=null;this.u=c;this.h=null;this.g=b;this.ka||(this.ka=function(){})}function Ha(b){null==b.ta&&(b.ta=b.g.Qa());return b.ta}
function Ia(b,c){return k(function*(){var a="POST",d=b.l().concat(encodeURI(c.W)),e=new Headers;if(c&&c.G)e.append("Authorization",c.G);else if(c&&c.Ba){var f="Bearer";c&&c.Ca&&(f=c.Ca);e.append("Authorization",f+" "+c.Ba)}else e.append("Authorization",b.h);if(c&&c.za)for(var g of c.za.entries())e.append(g[0],g[1]);c&&c.Aa&&(a=c.Aa);a=yield fetch(d,{method:a,body:c.Ia,headers:e,redirect:"follow"});401==a.status&&b.g.l&&!c.tb&&(a=yield Ja(b,c));return a})}h=Ga.prototype;
h.Ea=function(b){const c=this;return k(function*(){if(b&&(c.h=c.g.s("access_token"),c.h))return null;var a=c.g.l,d={},e=na();if(e&&e.token_type&&e.access_token){c.h=e.token_type+" "+e.access_token;c.g.u("access_token",c.h);if(e&&e.state)if(c.g.Sa(e.state))c.g.F("login_state");else return"Unauthorized access to this url.";return null}e&&e.code?d.code=e.code:a&&(d.Pa=c.g.B("refresh_token"));var f=c.g.Ua();f&&(d.clientId=f.ya,d.fb=f.fa);if(d.code||d.Pa){if(e&&e.state)if(c.g.Sa(e.state))c.g.F("login_state");
else return"Unauthorized access to this url.";if((d=yield Ka(c,d))&&d.token_type&&d.access_token)return f&&d.client_secret_enc&&(f.fa=d.client_secret_enc,c.g.P(f)),c.h=d.token_type+" "+d.access_token,c.g.u("access_token",c.h),a&&d.refresh_token&&c.g.C("refresh_token",d.refresh_token),d.logout&&c.g.u("logout_url",d.logout),null}else if(a&&(d.ib=!0),(d=yield Ka(c,d))&&d.url)return f&&d.client_secret_enc&&(f.fa=d.client_secret_enc,c.g.P(f)),d.state&&(c.g.u("login_state",d.state)||(d.state=c.m())),d.logout&&
c.g.u("logout_url",d.logout),window.location.href=d.url.concat("&state=".concat(encodeURIComponent(d.state))),"redirect";return d&&d.error?"["+d.error+"] "+d.error_description:"Unknown error occured when doing authorization."})};
h.Oa=function(){const b=this;return k(function*(){b.h=null;b.g.F("access_token");var c=b.g.s("logout_url");c?window.location.href=c:(c=new FormData,c.append("drive_type",b.m()),c.append("action","logout"),c=yield fetch(b.u,{method:"POST",credentials:"include",body:c,redirect:"follow"}),c.ok&&(c=yield c.text(),(c=JSON.parse(c))&&c.logout&&(window.location.href=c.logout)))})};h.wa=function(){return k(function*(){})};h.X=function(){return k(function*(){})};h.ca=function(){return k(function*(){})};
h.ia=function(){return k(function*(){})};function La(b){return k(function*(){if(!b||!b.$)throw Error("newname is not specified.");return yield F.ua(b)})}function Ma(b){return k(function*(){if(!b||!b.v)throw Error("parentid is not specified.");if(!b||!b.Ka)throw Error("oldparentid is not specified.");return yield F.ua(b)})}h.delete=function(){return k(function*(){})};h.sa=function(){return k(function*(){})};h.Da=function(){return k(function*(){})};h.Na=function(){return k(function*(){})};
h.Ha=function(b){return new Na(b,this)};h.ra=function(){return k(function*(){})};h.jb=function(){};h.va=function(b){return new Oa(b,this)};function Pa(b){return k(function*(){return{cb:b.status,da:yield b.text()}})}function G(b,c,a,d,e,f,g){return k(function*(){var l={W:c,Aa:a};Qa(e,l);f&&(l.za=f);g&&(l.Ia=g);l=yield Ia(b,l);var m=yield Pa(l);if(d&&l.status!=d)throw Error(JSON.stringify(m));return m})}function H(b,c,a){return k(function*(){return(yield G(b,c,"GET",200,a,null,null)).da})}
function Qa(b,c){b.Ca&&(c.Ca=b.Ca);b.Ba&&(c.Ba=b.Ba);b.G&&(c.G=b.G)}h.ua=function(){return k(function*(){})};
function Ka(b,c){return k(function*(){if(!c)throw Error("Options are not specified when auth onedrive.");var a=new FormData;a.append("drive_type",b.m());c.clientId&&a.append("client_id",c.clientId);c.yb&&a.append("redirect_uri",c.yb);c.fb&&a.append("client_secret",c.fb);c.code?a.append("code",c.code):c.Pa?a.append("refresh_token",c.Pa):c.ib&&a.append("need_code",c.ib);a=yield fetch(b.u,{method:"POST",body:a,credentials:"include",redirect:"follow"});if(200==a.status)return yield a.json();var d=yield a.text();
throw Error(d+" ("+a.status+")");})}function Ja(b,c){return k(function*(){console.log("Retry to send ajax.");if(c)c.tb=!0;else return null;var a=yield b.Ea();if(a)return console.error(a),null;c.G=b.h;return yield Ia(b,c)})}h.hb=function(b){return b.ok};
function Ra(b){b.Fa=Ga;if("function"===typeof Object.create)b.prototype=Object.create(Ga.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});else{var c=function(){};c.prototype=Ga.prototype;b.prototype=new c;b.prototype.constructor=b}b.prototype.xb||(b.prototype.xb=function(){return this.constructor.Fa});b.prototype.ka||(b.prototype.ka=function(...a){return this.constructor.Fa.call(this,...a)});b.prototype.zb||(b.prototype.zb=function(a,...d){return a?this.constructor.Fa.prototype[a].call(this,
...d):this.constructor.Fa.call(this,...d)})}function Sa(b,c,a){Ra(a);Da[b]=new Ea(b,c,a)}var Ta=-1,Ua=-9,Va=0;
function Na(b,c){this.I=c;this.s=b;this.C="";this.g=this.l=0;this.h=null;if(!this.s||!this.s.S)throw Error("fnm is not specified.");this.i=function(a){const d=this;return k(function*(){d.l=a;d.C=yield d.I.sa(d.s,a)})};this.write=function(a){const d=this;return k(function*(){var e=null;if(d.h){var f=d.h.byteLength;0<f?(e=new Uint8Array(f+a.byteLength),e.set(d.m(d.h),0),e.set(d.m(a),f)):e=d.m(a);d.h=null}else e=d.m(a);var g=new Blob([e],{type:"application/octet-binary"}),l="bytes "+d.g+"-";d.g+=g.size;
l+=d.g-1+"/"+d.l;var m=0,n=function(){const p=this;return k(function*(){var z=new Headers;z.append("Content-Range",l);try{var D=yield fetch(p.C,{method:"PUT",headers:z,body:g,redirect:"follow"});z="";if(c.hb(D)){var J=yield p.I.Da(D);if(J==Ua)throw a=null,z=yield D.text(),Error(z+" ("+D.status+")");if(J!=Ta&&J!=Va&&J<p.g){var U=a.byteLength;U-=p.g-J;if(0<U){var ca=a.slice(U);a=null;p.g>=p.l?yield p.write(ca):(p.h=ca,p.g=J)}else throw a=null,Error("Can NOT continue to upload buffer.");}}else throw a=
null,z=yield D.text(),Error(z+" ("+D.status+")");}catch(Fa){if(1>m)m++,yield qa(),yield n();else throw g=a=null,Fa;}})}.bind(d);yield n()})};this.cancel=function(){const a=this;return k(function*(){yield a.I.Na(a.C)})};this.B=function(){return this.l};this.m=function(a){return a instanceof Uint8Array?a:new Uint8Array(a)}}
function Oa(b,c){this.I=c;this.D=b;this.url="";this.name=null;this.F=this.i=this.h=this.size=0;this.Z=!1;this.P=16E3;b.V&&(this.P=b.V);this.u=this.l=0;this.B=function(a){const d=this;return k(function*(){if(d.Z)if(d.i&&(d.F=d.i,d.i=0),a){if(a>=d.g())throw console.log("offset:"+a+",size:"+d.g()),Error("offset can not be bigger than input size.");d.h=a}else d.h=0;else{var e=yield d.I.ra(d.D);d.Z=!0;if(e){if(d.size=e.O||0,d.url=e.j,d.name=e.o,d.u="1"==e.M?1:0,a){if(a>=d.g())throw Error("offset can not be bigger than input size.");
d.h=a}}else throw Error("Failed to prepare reader.");}})};this.A=function(){return this.name};this.ba=function(){return this.P};this.m=function(){return this.h};this.g=function(){return this.size};this.s=function(){return this.h>=this.g()};this.C=function(a){const d=this;return k(function*(){a||(a=d.P);return yield d.Y(a)})};this.R=function(){};this.Y=function(a){const d=this;return k(function*(){if(a&&d.i)return null;if(a)d.i=a;else if(d.i)a=d.i;else throw Error("size must be specified.");if(d.F)return null;
var e=d.h+a-1,f=function(){const g=this;return k(function*(){var l=g.url,m=new Headers;10<=g.l&&(l=Ha(g.I),m.append("Zb-Url",g.url));g.I.jb(m,g.D.G);m.append("Range","bytes="+g.h+"-"+e);try{var n=yield fetch(l,{method:"GET",headers:m,redirect:"follow"});if(g.F){if(g.F=0,g.i)return yield g.Y()}else{g.i=0;g.l=10>g.l?1:11;if(200==n.status||206==n.status){2==g.u&&(g.u=1);var p=parseInt(n.headers.get("content-length"),10);if(p)g.h+=p;else{var z=n.headers.get("content-range");if(z){var D=z.indexOf("-");
if(0>D)var J=0;else{D++;var U=z.indexOf("/",D);J=U<=D?0:parseInt(z.slice(D,U),10)}}else J=0;g.h=J?J+1:e+1}200==n.status&&g.h<g.g()?g.h=g.g():g.h>g.g()&&(g.h=g.g());return yield n.arrayBuffer()}if(401==n.status&&1==g.u){console.log("Retry auth.");g.u=2;var ca=yield g.I.Ea();if(ca)console.error(ca);else return g.D.G&&delete g.D.G,yield f()}else{var Fa=yield n.text();throw Error(Fa+" ("+n.status+")");}}}catch(kc){if(0==g.l&&Ha(g.I))return g.l=10,yield f();if(1==g.l||11==g.l)return g.l++,yield qa(),yield f();
throw kc;}})}.bind(d);return yield f()})}};Sa("onedrive","Microsoft OneDrive",function(b,c){this.ka(b,c);this.m=function(){return"onedrive"};this.wa=function(a){const d=this;return k(function*(){var e=yield H(d,"/me/drive",a);e=JSON.parse(e).quota;return{Ma:e.deleted,La:e.total,oa:e.used}})};this.X=function(a){const d=this;return k(function*(){var e="/me/drive/root/children";if(a){if(a.U){e=function(l){const m=this;return k(function*(){var n={aa:""};Qa(a,n);n=yield m.i(n,l);var p=[];n&&p.push(n);return p})}.bind(d);if(a.v){var f={aa:a.v};
Qa(a,f);if(f=yield d.i(f))return yield e(f.sb.concat("/").concat(f.o).concat("/").concat(a.U))}else return yield e("/drive/root:/".concat(a.U));return null}a.v&&(e="/me/drive/items/"+a.v+"/children")}e=yield H(d,e.concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),a);var g=[];e&&JSON.parse(e).value.forEach(function(l){g.push(this.ea(l))},d);return g})};this.ca=function(a){const d=this;return k(function*(){return yield d.i(a)})};this.ia=function(a){const d=this;
return k(function*(){if(!a||!a.K)throw Error("Name of new folder is not specified.");var e=new Headers;e.append("Content-Type","application/json;charset=UTF-8");var f="/me/drive/root/children";a.v&&(f="/me/drive/items/"+a.v+"/children");var g=JSON.stringify({name:a.K,folder:{},"@microsoft.graph.conflictBehavior":"fail"});e=yield G(d,f,"POST",201,a,e,g);return d.ea(JSON.parse(e.da))})};this.delete=function(a){const d=this;return k(function*(){var e="/me/drive/items/".concat(a.H);yield G(d,e,"DELETE",
204,a,null,null);return 0})};this.sa=function(a){const d=this;return k(function*(){var e={W:"/me",Aa:"POST",G:a.G,za:new Headers({"Content-Type":"application/json;charset=UTF-8","Cache-Control":"no-cache",Pragma:"no-cache"})};e.W=a.N?"/me/drive/items/"+a.N+":/":e.W+"/drive/root:/";e.W+=a.S;e.W+=":/createUploadSession";e.Ia=JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"replace",name:a.S}});e=yield Ia(d,e);var f=yield Pa(e),g="";e.ok&&(g=JSON.parse(f.da).uploadUrl);return g})};this.Da=
function(a){return k(function*(){if(0<=[200,201].indexOf(a.status))return Ta;if(0>[202].indexOf(a.status))return Ua;var d=yield a.text();if((d=JSON.parse(d).nextExpectedRanges)&&d.length){var e=d[0].indexOf("-");if(0<e)return parseInt(d[0].substring(0,e),10)}return Va})};this.Na=function(a){return k(function*(){var d=yield fetch(a,{method:"DELETE",redirect:"follow"});if(!d.ok)throw(yield d.text())+" ("+d.status+")";})};this.ra=function(a){const d=this;return k(function*(){var e="/me/drive/items/".concat(a.j),
f={};a.G&&(f.G=a.G);e=yield H(d,e.concat(y({select:"name,size,@microsoft.graph.downloadUrl"},!0)),f);f=null;e&&(e=JSON.parse(e),f={j:e["@microsoft.graph.downloadUrl"],o:e.name,O:e.size});return f})};this.l=function(){return"https://graph.microsoft.com/v1.0"};this.ua=function(a){const d=this;return k(function*(){if(!a||!a.H)throw Error("fid is not specified.");var e=new Headers;e.append("Content-Type","application/json;charset=UTF-8");var f="/me/drive/items/".concat(a.H),g={};a.$&&(g.name=a.$);a.v&&
(g.parentReference={id:a.v});g=JSON.stringify(g);if("{}"==g)throw Error("No property to be updated.");yield G(d,f,"PATCH",200,a,e,g);return 0})};this.i=function(a,d){const e=this;return k(function*(){var f=d?d.startsWith("/me")?d:"/me".concat(d):"/me/drive/items/"+a.aa;f=yield G(e,f.concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),"GET",0,a,null,null);if(200==f.cb)return e.ea(JSON.parse(f.da));if(404==f.cb&&d)return null;throw Error(JSON.stringify(f));})};this.ea=
function(a){var d={j:a.id,o:a.name,O:a.size,na:a.lastModifiedDateTime,sb:a.parentReference.path,J:a.parentReference.id,M:"0"};a.folder?d.M="1":a.file&&(d.M="2");return d}});Sa("googledrive","Google Drive",function(b,c){this.ka(b,c);this.m=function(){return"googledrive"};this.wa=function(a){const d=this;return k(function*(){var e=d.i("/about").concat(y({fields:"storageQuota"}));e=yield H(d,e,a);e=JSON.parse(e).storageQuota;return{Ma:e.usageInDriveTrash,La:e.limit,oa:e.usage}})};this.X=function(a){const d=this;return k(function*(){var e=d.i("/files"),f="'"+(a.v?a.v:"root")+"' in parents";a.U&&(f=f.concat(" and name = '"+a.U+"'"));e=yield H(d,e.concat(y({fields:"files(id,name,mimeType,parents,modifiedTime,size)",
q:f},!0)),a);var g=[];JSON.parse(e).files.forEach(function(l){g.push(this.ea(l))},d);return g})};this.ca=function(a){const d=this;return k(function*(){var e=d.i("/files/").concat(a.aa);e=yield H(d,e.concat(y({fields:"id,name,mimeType,parents,modifiedTime,size"},!0)),a);return d.ea(JSON.parse(e))})};this.ia=function(a){const d=this;return k(function*(){if(!a||!a.K)throw Error("Name of new folder is not specified.");var e=new Headers;e.append("Content-Type","application/json;charset=UTF-8");var f=d.i("/files");
e=yield G(d,f,"POST",200,a,e,JSON.stringify({mimeType:"application/vnd.google-apps.folder",name:a.K,parents:[a.v?a.v:"root"]}));return d.ea(JSON.parse(e.da))})};this.delete=function(a){const d=this;return k(function*(){var e=d.i("/files/").concat(a.H);yield G(d,e,"DELETE",204,a,null,null);return 0})};this.sa=function(a,d){const e=this;return k(function*(){var f={U:a.S,G:a.G};a.N&&(f.v=a.N);f=yield e.X(f);return 0<f.length?yield e.s(a,d,f[0].j):yield e.s(a,d)})};this.Da=function(a){return k(function*(){if(0<=
[200,201].indexOf(a.status))return Ta;if(0>[308].indexOf(a.status))return Ua;var d=a.headers.get("range");if(d){var e=d.indexOf("-");if(0<e)return parseInt(d.slice(e+1),10)+1}return Va})};this.ra=function(a){const d=this;return k(function*(){var e=d.i("/files/").concat(a.j),f={aa:a.j};a.G&&(f.G=a.G);if(f=yield d.ca(f))f.j=d.l().concat(encodeURI(e)).concat(y({alt:"media"})),d.g.l&&(f.M="1");return f})};this.jb=function(a,d){d?a.append("Authorization",d):a.append("Authorization",this.h?this.h:"")};
this.hb=function(a){return a.ok||308==a.status};this.l=function(){return"https://www.googleapis.com"};this.ua=function(a){const d=this;return k(function*(){var e=!0,f=new Headers;f.append("Content-Type","application/json;charset=UTF-8");var g=d.i("/files/").concat(a.H);a.Ka&&a.v&&(g=g.concat(y({addParents:a.v,removeParents:a.Ka})),e=!1);var l={};a.$&&(l.name=a.$,e=!1);if(e)throw Error("No property to be updated.");yield G(d,g,"PATCH",200,a,f,JSON.stringify(l));return 0})};this.s=function(a,d,e){const f=
this;return k(function*(){var g={},l="POST",m="/files?uploadType=resumable";e?(l="PATCH",m="/files/"+e+"?uploadType=resumable"):(g.name=a.S,a.N&&(g.parents=[a.N]));g={W:"/upload".concat(f.i(m)),Aa:l,G:a.G,za:new Headers({"X-Upload-Content-Length":d,"X-Upload-Content-Type":"application/octet-stream","Content-Type":"application/json; charset=UTF-8"}),Ia:JSON.stringify(g)};g=yield Ia(f,g);if(g.ok)return g.headers.get("location")||"";g=yield Pa(g);throw Error(g.da);})};this.i=function(a){return"/drive/v3".concat(a)};
this.ea=function(a){var d={j:a.id,o:a.name,O:a.size,na:a.modifiedTime,M:"2"};a.parents&&0<a.parents.length&&(d.J=a.parents[0]);this.A(a.mimeType)&&(d.M="1");return d};this.A=function(a){return"application/vnd.google-apps.folder"==a}});function Wa(b,c){this.I=c;this.P=b;this.h=null;this.i=this.size=0;this.l="";this.F=this.u=0;this.D=1600;b.V&&(this.D=b.V);this.B=function(a){const d=this;return k(function*(){var e=yield d.I.ra(d.P);if(e)d.size=e.O||0,e=yield d.I.F(d.P.j),d.h=e,d.h.sort(function(f,g){return f.la-g.la}),d.Y(a);else throw Error("Failed to prepare reader.");})};this.ba=function(){return this.D};this.m=function(){return this.i};this.g=function(){return this.size};this.s=function(){return this.h?this.u>=this.h.length:
!0};this.C=function(a){const d=this;return k(function*(){if(!d.l){var e=yield d.I.D(d.h[d.u].j);d.l=window.atob(ta(e))}return yield d.Z(a)})};this.R=function(){this.h=null;this.l=""};this.Y=function(a){if(a){if(a>=this.g())throw Error("offset can not be bigger than input size.");this.i=a;var d=0;for(a=0;a<this.h.length&&!(d+=this.h[a].O,this.i<d);a++)this.F=d;if(a<this.h.length)this.u=a;else throw Error("offset can not be bigger than input size.");}else this.u=this.F=this.i=0;this.l=""};this.Z=function(a){const d=
this;return k(function*(){var e=d.i-d.F,f=d.l.length-e;a?a<f&&(f=a):d.D<f&&(f=d.D);var g=va(d.l.substring(e,e+f));d.i+=f;d.l.length==e+f&&(d.l="",d.u++,d.F=d.i);return g.buffer})}}
function Xa(b,c){this.I=c;this.g=b;this.data={j:"",o:"",O:0,J:"",M:"2"};this.m=this.h=0;this.i=function(a){const d=this;return k(function*(){d.h=a;d.data.o=d.g.S;d.g.N&&(d.data.J=d.g.N);d.data.j=yield d.I.sa(d.g,a)})};this.write=function(a){const d=this;return k(function*(){d.data.O+=a.byteLength;var e=C(ua(d.l(a)));d.m++;yield d.I.saveData(d.data.j,d.m,a.byteLength,e);d.data.O>=d.h&&(yield d.I.C(d.data))})};this.cancel=function(){const a=this;return k(function*(){yield a.I.delete({H:a.data.j})})};
this.B=function(){return this.h};this.l=function(a){return a instanceof Uint8Array?a:new Uint8Array(a)}}
Sa("idxdb","Loacal Indexed DB",function(b,c){this.ka(b,c);this.m=function(){return"idxdb"};this.Ea=function(){return new Promise(function(){this.wb()})};this.Oa=function(){return k(function*(){location.reload()})};this.wa=function(){const a=this;return k(function*(){var d={Ma:0,La:0,oa:0};yield a.i(function(e){e.getAll().onsuccess=function(f){f.target.result.forEach(function(g){"2"==g.type&&(d.oa+=parseInt(g.size,10))})}});return d})};this.X=function(a){const d=this;return k(function*(){return yield d.A(void 0,
a.v,a.U)})};this.ca=function(a){const d=this;return k(function*(){var e=yield d.A(a.aa);return e&&0<e.length?e[0]:null})};this.ia=function(a){const d=this;return k(function*(){if(!a||!a.K)throw Error("Name of new folder is not specified.");var e={j:"",o:a.K,O:0,J:"",M:"1"};a.v&&(e.J=a.v);e.j=yield d.B(e.J);yield d.C(e);return e})};this.delete=function(a){const d=this;return k(function*(){function e(l){var m;for(m=0;m<f.length;m++)f[m].j==l?f[m].Ja=!0:f[m].J==l&&("1"==f[m].M?e(f[m].j):f[m].Ja=!0)}
var f=[],g=0;yield d.i(function(l){l.getAll().onsuccess=function(m){m.target.result.forEach(function(n){f.push({j:n.key,o:"",J:n.pid})})}});e(a.H);yield d.i(function(l){f.forEach(function(m){m.Ja&&l.delete(m.j)})});yield d.s(function(l){var m=[];f.forEach(function(n){n.Ja&&"2"==n.M&&m.push(n.j)});0>m.indexOf(a.H)&&m.push(a.H);l.getAllKeys().onsuccess=function(n){n.target.result.forEach(function(p){var z=p.indexOf(":");0<=m.indexOf(p.substring(0,z))&&(l.delete(p),g+=parseInt(p.substring(p.indexOf("_",
z+1)+1),10))})}});return g})};this.Ha=function(a){return new Xa(a,this)};this.sa=function(a){const d=this;return k(function*(){var e="";a.N&&(e=a.N);return yield d.B(e)})};this.Da=function(){return k(function*(){return Va})};this.Na=function(){return k(function*(){})};this.va=function(a){return new Wa(a,this)};this.ra=function(a){const d=this;return k(function*(){return yield d.ca({aa:a.j})})};this.l=function(){return""};this.ua=function(a){const d=this;return k(function*(){if(!a||!a.H)throw Error("fid is not specified.");
yield d.i(function(e){e.get(a.H).onsuccess=function(f){if(f=f.target.result){var g=!1;a.$&&f.name!=a.$&&(f.name=a.$,g=!0);a.v&&f.pid!=a.v&&(f.pid=a.v,g=!0);g&&e.put(f)}}});return 0})};this.C=function(a){const d=this;return k(function*(){a.na=d.R();var e={key:a.j,name:a.o,size:a.O,tms:a.na,type:a.M};a.J&&(e.pid=a.J);yield d.i(function(f){f.put(e)})})};this.saveData=function(a,d,e,f){const g=this;return k(function*(){yield g.s(function(l){l.put({key:a+":"+d+"_"+e,data:f})})})};this.F=function(a){const d=
this;return k(function*(){var e=[];yield d.s(function(f){f.getAllKeys().onsuccess=function(g){g.target.result.forEach(function(l){var m=l.indexOf(":");if(l.substring(0,m)==a){var n=l.substring(m+1);m=n.indexOf("_");e.push({j:l,la:parseInt(n.substring(0,m),10),O:parseInt(n.substring(m+1),10)})}})}});return e})};this.D=function(a){const d=this;return k(function*(){var e="";yield d.s(function(f){f.get(a).onsuccess=function(g){e=g.target.result.data}});return e})};this.wb=function(){new Promise(function(a,
d){if(window.indexedDB){var e=window.indexedDB.open("zgalocaldb");e.onerror=function(f){d(f.target.error)};e.onupgradeneeded=function(f){f=f.target.result;f.createObjectStore("items",{keyPath:"key"});f.createObjectStore("datas",{keyPath:"key"})};e.onsuccess=function(f){f.target.result.close();a()}}else d(Error("IndexedDB is not supported in your browser settings."))})};this.i=function(a){return new Promise(function(d){window.indexedDB.open("zgalocaldb").onsuccess=function(e){var f=e.target.result;
e=f.transaction("items","readwrite");e.oncomplete=function(){f.close();d()}.bind(this);e=e.objectStore("items");a&&a(e)}.bind(this)})};this.s=function(a){return new Promise(function(d){window.indexedDB.open("zgalocaldb").onsuccess=function(e){var f=e.target.result;e=f.transaction("datas","readwrite");e.oncomplete=function(){f.close();d()}.bind(this);e=e.objectStore("datas");a&&a(e)}.bind(this)}.bind(this))};this.A=function(a,d,e){const f=this;return k(function*(){var g=[];yield f.i(function(l){l.getAll().onsuccess=
function(m){m.target.result.forEach(function(n){var p=!0;a&&(p=a==n.key);p&&d&&(p=d==n.pid);p&&e&&(p=e==n.name);p&&g.push({j:n.key,o:n.name,O:n.size,na:n.tms,M:n.type,J:n.pid})})}});return g})};this.R=function(){var a;a||(a=new Date);var d=[],e=[];d.push(a.getFullYear());d.push(a.getMonth()+1);d.push(a.getDate());e.push("0".concat(a.getHours()).slice(-2));e.push("0".concat(a.getMinutes()).slice(-2));e.push("0".concat(a.getSeconds()).slice(-2));return d.join("-")+" "+e.join(":")};this.B=function(a){const d=
this;return k(function*(){var e=-1;yield d.i(function(f){f.getAllKeys().onsuccess=function(g){g.target.result.forEach(function(l){var m=l.indexOf("_");a&&0<m?l.substring(m+1)==a&&(m=parseInt(l.substring(0,m),10),m>e&&(e=m)):!a&&0>m&&(m=parseInt(l,10),m>e&&(e=m))})}});e++;return a?e+"_"+a:e.toString()})}});function Ya(b,c){var a=I;this.h=this.g=null;this.B=a;this.i=1;this.u=b;this.l=c;this.m=0;this.s=function(){const d=this;return k(function*(){var e={type:0,wtype:d.i,size:d.g.g()};d.l(e);var f=new Aa({$a:1==d.i,ma:d.B,bb:d.g,eb:d.h});e=function(){var m={type:1,wtype:this.i,begin:this.m,spd:f.l(),posn:this.g.m(),size:this.g.g()};this.l(m);return this.u()?!1:!0}.bind(d);d.m=Date.now();var g=null,l=yield f.start(0,e).catch(function(m){g=m});e={type:2,wtype:d.i,begin:d.m,posn:d.g.m(),size:d.h.B()};g?e.errr=
g.message||g.Ab:l?d.h.u&&(e.blob=d.h.u()):e.type=3;d.l(e)})};this.A=function(d){var e=F;const f=this;return k(function*(){f.i=1;f.g=e.va({j:d,V:16E5});f.h=new xa;yield f.s()})};this.C=function(d,e,f){var g=F;const l=this;return k(function*(){l.i=2;l.g=new ya({xa:e,V:16E5});l.h=g.Ha({S:d,N:f});yield l.s()})}};var K=null,F=null,L=[],M=0,I=null,N=[],O=0,P=[];function Q(b,c){O&&(window.clearTimeout(O),O=0);var a=r("#divMessage");if(0==b)a.style.display||(a.style.opacity="0",O=window.setTimeout(function(){O=0;v(a)},150));else{var d=q("span",a);1==b?(a.className="zb-notice",d[0].innerText="Notice"):(a.className="zb-alert",d[0].innerText="Error");d[1].innerText=c?c:"";a.style.opacity&&(u(a),O=window.setTimeout(function(){O=0;a.style.opacity=""},50))}}
function R(b){var c="";"string"===typeof b?window.msgs&&b&&window.msgs[b]?c=window.msgs[b]:c=b:b&&(c=JSON.stringify(b));Q(2,c)}function S(b){var c=b;window.msgs&&b&&window.msgs[b]&&(c=window.msgs[b]);Q(1,c)}function Za(b){S(b);O=setTimeout(function(){O=0;Q(0)},3E3)}
function $a(b){return new Promise(function(c){function a(e){(e.target||e.srcElement).remove();c("error"!=e.type)}var d=document.createElement("script");d.setAttribute("type","text/javascript");d.setAttribute("src",b);d.addEventListener("load",a);d.addEventListener("error",a);document.body.appendChild(d)})}
function ab(b){return k(function*(){if(K.Y())if(r("#chkSaveKey").checked){var c=yield bb().catch(function(d){R(d)});if(c){var a="";c&&c.lsauth&&(c=wa(!0,b,c.lsauth),a=C(c));yield K.C("key_words",a,!0)}}else yield K.C("key_words",null,!0)})}function cb(){return k(function*(){yield K.Ta();yield F.Oa()})}
function bb(){return k(function*(){var b=new FormData;b.append("drive_type","localstorage");b=yield fetch("https://zgayard.f5.si/grantauth.php",{method:"POST",body:b,credentials:"include",redirect:"follow"});if(200==b.status)if(b=yield b.json()){if(b.error)throw"["+b.error+"] "+b.error_description;if(!b.lsauth)throw"lsFailed";}else throw"lsFailed";else throw(yield b.text())+" ("+b.status+")";return b})}
function db(){return k(function*(){var b=K.Va();b||(K.Wa(),b=K.Va(!0));if(!b){b=navigator.language;var c=b.indexOf("-");0<c&&(b=b.substring(0,c))}yield eb(b);r("#txtRelay").value=K.Qa();b=K.lb();if(c=K.Ua())r("#chkOwnSecret").click(),r("#txtClientId").value=c.ya,r("#txtClientSecret").value=c.fa;c=r("#selDrive");var a=na(),d;for(d in Da){var e=document.createElement("option");e.value=d;e.innerText=Da[d].A();b?b==d&&(e.selected=!0):a&&a.state==Da[d].j&&(b=d,e.selected=!0);c.appendChild(e)}K.Y()?(K.l&&
(r("#chkSkipLogin").checked=!0),K.B("key_words")&&(r("#chkSaveKey").checked=!0)):(v("#divSkipLogin"),v("#divSaveKey"));b?yield fb(b):gb()})}function gb(b){var c=r("#divSet"),a=r("#selDrive"),d=r("btnLogout",c,"button.iid");b?(a.disabled=!0,u(d),v(".zb-nav-tools"),v("#divMain")):(a.disabled=!1,v(d));u(c)}
function eb(b){return k(function*(){if(!window.msgs||window.msgs.lang!=b){var c=window.msgs;window.msgs=null;yield $a("msg/"+b+".js");window.msgs?(window.msgs.lang=b,K.Z(b),hb()):(console.log("Message file of '"+b+"' is missing."),c?window.msgs=c:(yield $a("msg/en.js"),window.msgs?(window.msgs.lang="en",K.Z(window.msgs.lang),hb()):R("Message file is missing.")))}})}
function hb(){var b=window.msgs;b.lblConfNotice=b.lblConfNotice.replace("{0}","_zgayard_.conf");var c=q("*"),a;for(a=0;a<c.length;a++){var d=c[a],e=null;d.hasAttribute("iid")&&(e=b[d.getAttribute("iid")])&&(d.innerText=e);!e&&d.hasAttribute("vid")&&(e=b[d.getAttribute("vid")])&&(d.value=e);!e&&d.id&&(e=b[d.id]);e&&("button"==d.type?d.value=e:d.innerText=e);d.hasAttribute("tid")&&(e=b[d.getAttribute("tid")])&&(d.title=e)}c=r("#seLang");a="";for(a in ba)d=document.createElement("option"),d.value=a,
d.innerText=ba[a],a==b.lang&&(d.selected=!0),c.appendChild(d)}function fb(b){return k(function*(){S("loading");var c=Da[b];if(c){F=new c.g(K,"https://zgayard.f5.si/grantauth.php");var a=yield F.Ea(!0);a?"redirect"!=a&&(yield K.Ta(),R(window.msgs.loginFailed.replace("{0}",a))):(yield K.Xa(),a=r("img",t("div",r("#spanQuota"))),a.src="img/"+b+".png",a.alt=c.A(),(c=yield F.X({U:"_zgayard_.conf"}).catch(function(d){R(JSON.stringify(d))}))&&(0==c.length?ib(!0):yield jb(c[0].j)))}else R("unkDrive")})}
function kb(){return k(function*(){if(r("#chkAgreeTos").checked){var b="",c="";if(r("#chkOwnSecret").checked&&(b=r("#txtClientId").value,c=r("#txtClientSecret").value,!b||!c)){R("noClientIdS");return}var a=r("#selDrive"),d=!1;a.disabled||(d=K.Ya(a.value));var e=null;r("#chkOwnSecret").checked&&(e={ya:b,fa:c});K.P(e);K.Za(r("#chkSkipLogin").checked);K.Ra(r("#txtRelay").value);yield eb(r("#seLang").value);d?(K.ba(),yield fb(a.value)):yield K.Xa();lb()}else R("noAgreeTos")})}
function lb(){var b=r("#selDrive");v("#divSet");b.disabled&&(u(".zb-nav-tools"),u("#divMain"))}function mb(b,c){var a=r("#divPwd"),d=!1;b?(a.setAttribute("addroot","1"),d=!0):a.removeAttribute("addroot");b=q("*",a);for(a=0;a<b.length;a++){var e=b[a];e.classList.contains("addroot")?d?u(e):v(e):e.classList.contains("firstep")?d&&c?u(e):v(e):e.classList.contains("chgroot")&&(d?v(e):u(e));"password"==e.type&&(e.value="")}nb()}
function ob(){return k(function*(){if(window.confirm(window.msgs.delConfirm)){S("deleting");var b=r("#selRoot"),c=b.value,a=-1;L.forEach(function(g,l){g.root==c&&(a=l)});if(0<=a){var d=yield F.X({U:L[a].root}).catch(function(g){console.error(g)});d&&(0<d.length&&(yield F.delete({H:d[0].j}).catch(function(g){R(g)})),L.splice(a,1),yield pb())}if(a==M)window.location.reload();else{d=q("option",b);var e=0;for(e=0;e<d.length;e++){var f=d[e];if(f.value==c){b.removeChild(f);break}}a<M&&M--;Za("delrootDone")}}})}
function ib(b){b?"boolean"===typeof b?mb(!0,!0):(mb(),v(".zb-nav-tools"),v("#divMain")):mb();u("#divPwd");Q(0)}function qb(b){v("#divPwd");b&&0<N.length&&(u(".zb-nav-tools"),u("#divMain"))}function rb(){var b=w(t("div")),c=b.children[0].cloneNode(!0);c.value="";b.appendChild(c)}function nb(){var b=r("#divfKey");b=q("file",b,"input.type");var c;for(c=b.length-1;0<c;c--)b[c].remove();b[0].value=""}
function sb(){return k(function*(){S("loading");var b=r("#divPwd").hasAttribute("addroot"),c=r("#pwdKey").value,a=q("input",r("#divfKey")),d=[],e,f;for(e=0;e<a.length;e++){var g=a[e].files;for(f=0;f<g.length;f++)d.push(g[f])}if(c||0<d.length){if(b){e=r("#pwdKeyRe").value;if((c||e)&&c!=e){R("diffPwd");return}if(!r("#txtRoot").value){R("noRoot");return}}a="";c&&(a=forge.util.encodeUtf8(c));if(0<d.length){c=ra();f=forge.hmac.create();f.start("sha512","zb12");for(e=0;e<d.length;)g=yield sa(c,d[e].slice(0,
1023)),f.update(ua(new Uint8Array(g))),e++;a+=f.digest().getBytes()}yield tb(a,b)}else R("noPwd")})}
function tb(b,c){return k(function*(){var a=forge.hmac.create();a.start("md5","zgayard");a.update(b);a=C(a.digest().getBytes()).substring(0,8);var d="";if(c){var e={root:r("#txtRoot").value};r("#chkEncryFname").checked&&(e.encfname=!0);var f=!1;L.forEach(function(m){m.root==e.root&&(f=!0)});f?R("dupRoot"):(yield K.C("root",e.root),yield ab(b),d=forge.random.getBytesSync(1024),I=E(d),e.iv=a.concat(ub(!0,d,b)),M=L.length,L.push(e),vb(e,!0),yield pb(),yield wb())}else{var g=r("#selRoot").value,l=-1;
L.forEach(function(m,n){m.root==g&&(l=n)});0<=l&&L[l].iv&&a==L[l].iv.slice(0,a.length)?(M=l,yield K.C("root",g),yield ab(b),d=ub(!1,L[M].iv.slice(a.length),b),I=E(d),yield wb()):ja(r("#divPwd"))?R("pwdError"):ib()}})}function ub(b,c,a){a=E(a);c=b?c:window.atob(ta(c));c=wa(b,c,a);return b?C(c):c}
function pb(){var b=L;return k(function*(){var c=forge.util.text.utf8.encode(JSON.stringify(b));c=new ya({xa:new Blob([c],{type:"application/octet-binary"}),V:262144});var a=F.Ha({S:"_zgayard_.conf"});yield Ba(c,a)})}
function jb(b){return k(function*(){var c=new xa;yield Ba(F.va({j:b}),c);c=forge.util.decodeUtf8(ua(c.A()));c=JSON.parse(c);Array.isArray(c)?L=c:L.push(c);var a=-1,d=K.B("root"),e=r("#selRoot");e.innerHTML="";L.forEach(function(g,l){var m=!1;d&&g.root==d&&(m=!0);vb(g,m,e);m&&(a=l)});if(0<=a){if(M=a,c=K.B("key_words")){var f=yield bb().catch(function(g){R(g)});if(f&&f&&f.lsauth&&!f.newkey){c=wa(!1,window.atob(ta(c)),f.lsauth);yield tb(c);return}}}else M=0;ib()})}
function vb(b,c,a){a=a||r("#selRoot");var d=document.createElement("option");d.value=b.root;d.innerText=b.root;c&&(d.selected=!0);a.appendChild(d)}function xb(){return k(function*(){window.confirm(window.msgs.dropConfirm)&&(yield K.nb().catch(function(b){R(b)}),yield F.Oa())})};var yb=3;function zb(b){return new Promise(function(c,a){switch(b){case "new":var d="spanNew";break;case "upload":d="spanUpload";break;case "selfldr":d="spanSelFldr";break;default:return}var e=r("#divModal"),f=r("#spanModal");f.innerText=window.msgs[d];d=q("div",w(f));var g;for(g=0;g<d.length;g++)f=d[g],f.hasAttribute("type")&&(f.getAttribute("type")==b?u(f):v(f));e.h=c;e.l=a;u(e)})}function Ab(b){if(b=t("zb-modal",r(b),"div.class"))b.h&&(b.h(),delete b.h,delete b.l),v(b)}
function Bb(b){return k(function*(){var c="",a=q("div",w(r("#spanModal"))),d;for(d=0;d<a.length;d++){var e=a[d];if(e.hasAttribute("type")&&ja(e)){c=e.getAttribute("type");break}}a=!1;switch(c){case "new":a=yield Cb();break;case "upload":c=[];e=r("#upfiles").files;for(d=0;d<e.length;d++)c.push(e[d]);e=r("#upfolder").files;for(d=0;d<e.length;d++)c.push(e[d]);0>=c.length?R("noFiles"):(a=!0,Db(c));break;case "selfldr":d=r("#divModal"),c=Eb(d),c=ka(c,"li",!0).getAttribute("uid"),c!=N[N.length-1].j&&(Ab(b),
d=d.getAttribute("uid"),yield Fb(c,d))}a&&Ab(b)})}function Eb(b){return r(".zb-main-header",b).children[0]}function Gb(b){return r("zb-main-list",b,"ul.class")}function Hb(b){return r("fnm",b,"span.name")}function Ib(b){if(L[M].encfname){var c=I;b=forge.util.encodeUtf8(b);c=wa(!0,b,c);c=C(c)}else c=b;return c}function Jb(b){if(L[M].encfname)try{var c=I,a=window.atob(ta(b)),d=wa(!1,a,c);return forge.util.decodeUtf8(d)}catch(e){console.error(e)}return b}
function Kb(){k(function*(){K=new Ca;yield K.pb().catch(function(){R("IndexedDB is not supported in your browser settings.")});yield db()})}
function wb(){return k(function*(){[Eb("#divMain"),r("ul","#divHistory")].forEach(function(a){var d=q("li",a);for(a=0;a<d.length;a++)d[a].classList.contains("template")||d[a].remove()});Lb(!1);qb();u(".zb-nav-tools");u("#divMain");var b=yield F.wa({}).catch(function(a){R(a)});if(b){var c=r("#spanQuota");c.setAttribute("total",b.La);c.setAttribute("trash",b.Ma);Mb(b.oa);b=L[M].root;if((c=yield F.X({U:b}).catch(function(a){R(JSON.stringify(a))}))&&0<c.length)N=[],N.push(c[0]),yield Nb(),yield T(),yield Ob();
else if(b=yield F.ia({K:b}).catch(function(a){R(JSON.stringify(a))}))N=[],N.push(b),yield Nb(),yield T()}})}function Mb(b,c){var a=r("#spanQuota");"string"==typeof b&&(b=parseInt(b,10));var d=x(a,"total"),e=x(a,"trash"),f=0;a.hasAttribute("used")&&(f=x(a,"used"));if(c){if(f-=b,a.setAttribute("used",f),0<d){a.setAttribute("trash",e+b);return}}else f+=b,a.setAttribute("used",f);a.innerText=0<d?window.msgs.quotaInfo.replace("{0}",B(d-f-e)):window.msgs.quotaInfoU.replace("{0}",B(f))}
function Lb(b){function c(d,e){d=r(d,a,"div.class");e=r("menuHistory",d,e.concat(".iid"));e=t("li",e);b?u(e):v(e)}var a=r("nav");c("zb-nav-tools","span");c("zb-nav-menu","label")}function Ob(){return k(function*(){if(P=K.ob()){for(var b=r("ul","#divHistory"),c=0;c<P.length;){var a=P[c],d=yield F.ca({aa:a.H}).catch(function(){});d&&(d.J&&(a.K=d.J),Pb(c,Jb(d.o),b));c++}0<P.length&&Lb(!0)}})}
function Pb(b,c,a){a||(a=r("ul","#divHistory"));b=P[b];var d=null,e=r(b.K,a,"li.parentId");if(null==e){e=r("template",a,"li.class").cloneNode(!0);e.classList.remove("template");var f=q("span",e),g;for(g=0;g<f.length;g++){var l=f[g];switch(l.getAttribute("name")){case "delete":l.addEventListener("click",Qb);break;case "file":l.addEventListener("click",Rb);d=l;break;case "next":l.addEventListener("click",Sb)}}e.setAttribute("parentId",b.K);a.appendChild(e)}else d=r("file",e,"span.name");d.innerText=
c;b.ha&&(c=d,a=d.innerText.concat(" ["),d=a.concat,b=Math.floor(b.ha),e=Math.floor(b/3600),b-=3600*e,f=Math.floor(b/60),b-=60*f,g=[],0<e?(g.push(e.toString()),g.push("0".concat(f).slice(-2))):g.push(f.toString()),g.push("0".concat(b).slice(-2)),c.innerText=d.call(a,g.join(":")).concat("]"))}
function T(b,c,a){return k(function*(){var d=0;if(!a){if(0>=N.length)return null;d=N.length-1;a=N[d]}var e="#divMain";c&&(e="#divModal");var f=0;f=r(e);e=Eb(f);var g=Gb(f);S("loading");var l=V(g);for(f=0;f<l.length;f++)g.removeChild(l[f]);(f=ka(e,void 0,!0))&&f.classList.contains("template")&&(f=null);b?f&&f.classList.remove("normal"):(f&&(0!=d||c)&&f.classList.add("normal"),Tb(e,a,d));if(d=yield F.X({v:a.j}).catch(function(p){R(p)})){var m=[],n=0;d.forEach(function(p){var z=0,D=m.length;p.o=Jb(p.o);
for(W(p)?D=n++:z=n;z<D&&!(p.o<m[z].o);)z++;z<m.length?m.splice(z,0,p):m.push(p)});m.forEach(function(p){c&&!W(p)||Ub(g,p)});c||(e=r("#chkAll"),f=t("li",e),r("checkbox",f,"input.type").checked=!1,v(r("chkbox",f,"span.name")),0<d.length?u(e):v(e));Q(0);return m}return null})}
function Tb(b,c,a,d){var e=r("template",b,"li.class").cloneNode(!0);r("span",e).innerText=c.o;e.setAttribute("name","folder");e.setAttribute("uid",c.j);e.setAttribute("idx",a);e.addEventListener("click",Vb);e.classList.remove("template");d&&e.classList.add("normal");u(e);b.appendChild(e)}
function Ub(b,c){var a=c.o,d="",e="",f=r("template",b,"li.class").cloneNode(!0);f.classList.remove("template");f.setAttribute("uid",c.j);f.setAttribute("utype",c.M);var g=q("span",f),l;for(l=0;l<g.length;l++){var m=g[l];switch(m.getAttribute("name")){case "fnm":m.innerText=a;m.addEventListener("click",X);break;case "icon":if(W(c))A(m,"folder","#FFD679");else{var n=pa(a);da[n]?A(m,"image","#E7FFE7"):fa[n]?A(m,"video","#FFE7F3"):ea[n]?A(m,"audio","#DBFBFD"):A(m,"file","#FFFFB0")}m.addEventListener("click",
Wb);break;case "chkbox":m.addEventListener("click",Wb);v(m);break;case "edit":m.addEventListener("click",Xb);break;case "size":d||(d=B(c.O));m.innerText=d;break;case "tms":if(!e)if(e=c.na){e=new Date(e);n=[];var p=[];n.push(e.getFullYear());n.push(e.getMonth()+1);n.push(e.getDate());p.push("0".concat(e.getHours()).slice(-2));p.push("0".concat(e.getMinutes()).slice(-2));p.push("0".concat(e.getSeconds()).slice(-2));e=n.join("-")+" "+p.join(":")}else e="";m.innerText=e}}u(f);b.appendChild(f)}
function Yb(b,c){var a=r("checkbox",b,"input.type");1==c?a.checked=!0:-1==c?a.checked=!1:(a.checked=!a.checked,c=a.checked?1:-1);0<c?u(r("chkbox",b,"span.name")):v(r("chkbox",b,"span.name"))}function Wb(){Yb(t("li"))}
function X(b,c,a){return k(function*(){var d=null,e=!1;if("string"==typeof b)var f=b;else d=t("li"),f=d.getAttribute("uid"),e="selfldr"==t("div",d).getAttribute("type");if(c||!d)d=Zb(f,c,a),f=d.getAttribute("uid");f={j:f,o:Hb(d).innerText,M:d.getAttribute("utype")};W(d)?e?yield T(!1,!0,f):(N.push(f),yield T()):$b(f.j,f.o)})}
function Vb(){return k(function*(){for(var b=t("li"),c=t("ul",b),a="selfldr"==t("div",c).getAttribute("type"),d=0,e=w(b);e;)e.tagName==b.tagName&&d++,e=w(e);if(0<d)for(e=0;e<d;e++)c.removeChild(c.lastElementChild);a?yield T(!0,!0,{o:r("span",b).innerText,j:b.getAttribute("uid")}):(d=x(b,"idx"),d<N.length-1&&N.splice(d+1),yield T(!0))})}function W(b){return"1"==(b instanceof HTMLElement?b.getAttribute("utype"):"string"==typeof b?b:b.M)}
function ac(){var b=t("li"),c=r("checkbox",b,"input.type");Yb(b);var a=-1;c.checked&&(a=1);b=q("li",t("ul",b));for(c=0;c<b.length;c++)b[c].classList.contains("header")||b[c].classList.contains("template")||Yb(b[c],a)}
function Xb(b){var c=t("span"),a=c.getBoundingClientRect();c=t("li",c);var d=r("#ulIteMenu");if(d.hasAttribute("ofwid"))var e=parseInt(d.getAttribute("ofwid"),10);else d.style.display="block",e=d.offsetWidth,d.setAttribute("ofwid",e);d.style.left=a.right+e>document.body.offsetWidth?a.left-e+"px":a.right+"px";d.style.top=(document.documentElement.scrollTop||document.body.scrollTop)+a.top+"px";d.setAttribute("uid",c.getAttribute("uid"));d.setAttribute("utype",c.getAttribute("utype"));b.qa=yb}
function Zb(b,c,a){if(!b)return null;var d=Gb("#divMain");d=V(d);var e;for(e=0;e<d.length&&d[e].getAttribute("uid")!=b;e++);if(e>=d.length)return null;switch(c){case 1:for(;0<=e;){e--;if(0>e){if(a)return null;a=!0;e=d.length-1}if(!W(d[e]))break}break;case 2:for(;e<d.length;){e++;if(e>=d.length){if(a)return null;a=!0;e=0}if(!W(d[e]))break}}return d[e]}
function bc(b){return k(function*(){var c=t("li"),a=t("ul",c),d=a.getAttribute("uid");if(d)switch(r("label",c).getAttribute("iid")){case "menuDownload":W(a)?R("noDownFolder"):cc(d);break;case "menuRename":c=r("#divInpName");a=r("input",c);var e=Zb(d);d=Hb(e);var f=d.getBoundingClientRect();e=r("edit",e,"span.name").getBoundingClientRect();a.value=d.innerText;c.style.left=f.left+"px";c.style.top=(document.documentElement.scrollTop||document.body.scrollTop)+f.top-2+"px";a.style.width=e.left-f.left+
"px";a.style.height=f.height+2+"px";u(c);a.focus();b.qa=4;break;case "menuMove":yield dc(d);break;case "menuDelete":yield ec(d)}})}function cc(b){var c=Zb(b);b={o:Hb(c).innerText,j:b};fc([b])}function dc(b){return k(function*(){var c=r("#divModal");if(b)c.setAttribute("uid",b);else if(hc())c.removeAttribute("uid");else return;c=Eb(c);var a=V(c),d;for(d=0;d<a.length;d++)c.removeChild(a[d]);yield T(!1,!0,N[0]);yield zb("selfldr")})}
function ic(b){if(13===b.keyCode){if(b.shiftKey||b.ctrlKey||b.altKey)return!0}else return 27===b.keyCode?(v(t("div")),!1):!0;jc();return!1}function jc(){return k(function*(){var b=t("div"),c=r("input",b);if(c.value){var a=r("#ulIteMenu").getAttribute("uid"),d=Zb(a);if(d&&(d=Hb(d),c.value!=d.innerText)){var e=Ib(c.value);a={H:a,$:e};try{yield La(a),d.innerText=c.value,Za("renDone")}catch(f){R(f)}}v(b)}else R("noNewName")})}
function Fb(b,c){return k(function*(){var a=[];c?a.push({j:c,o:""}):a=hc();if(0!=a.length){S("moving");for(var d=!0,e=0;d&&e<a.length;)yield Ma({H:a[e].j,v:b,Ka:N[N.length-1].j}).catch(function(f){R(f);d=!1}),e++;d&&(yield T(!0,!1),Za("moveDone"))}})}
function ec(b){return k(function*(){var c=null;b?c=[{j:b,o:""}]:c=hc();if(c&&confirm(window.msgs.delConfirm)){S("deleting");for(var a=!0,d=0;a&&d<c.length;){var e=yield F.delete({H:c[d].j}).catch(function(f){R(f);a=!1});e&&Mb(e,!0);d++}a&&(yield T(!0,!1),Za("delDone"))}})}
function Cb(){return k(function*(){var b=r("#fldnm").value;if(!b)return R("noFldName"),!1;var c=r("#chkFInto").checked,a={K:Ib(b)};0<N.length&&(a.v=N[N.length-1].j);return(a=yield F.ia(a).catch(function(d){R(d.da)}))?(a.o=b,c?(N.push(a),yield T(!1,!1)):(Ub(Gb("#divMain"),a),Za("flDone")),!0):!1})}
function hc(b){var c=[],a=V(Gb("#divMain")),d;for(d=0;d<a.length;d++)if(r("checkbox",a[d],"input.type").checked){if(b&&W(a[d]))return R("noDownFolder"),null;c.push({o:Hb(a[d]).innerText,j:a[d].getAttribute("uid")})}return 0>=c.length?(R("noChecks"),null):c}
function $b(b,c){k(function*(){var a=r("#diViewer"),d=t("zb-viewer",a,"div.class"),e=r("title",d,"span.name"),f=r("span",a),g=r("img",a),l=yield lc("video",a),m=yield lc("audio",a);f.innerText=window.msgs.loading;u(f);v(w(f));v(g);e.innerText=c;g.src="";a.setAttribute("uid",b);u(t("zb-modal",d,"div.class"));e=pa(c);a=da[e];d=fa[e];e=ea[e];if(navigator.serviceWorker&&navigator.serviceWorker.controller&&d)l.fid=b,l.g=c,l.src="sw/"+b,u(l),v(f);else if(navigator.serviceWorker&&navigator.serviceWorker.controller&&
e)m.fid=b,m.g=c,m.src="sw/"+b,u(m),g.src="img/logo.png",u(g),v(f);else if(a){l=new xa;m=new Aa({$a:!0,ma:I,bb:F.va({j:b,V:16E4}),eb:l});try{if(yield m.start()){var n=l.A();n instanceof Uint8Array||(n=new Uint8Array(n));a&&(g.src=window.URL.createObjectURL(new Blob([n],{type:a})),u(g),v(f))}else console.log("Not done!")}catch(p){console.log(p)}}else f.innerText=window.msgs.cantView,u(w(f))})}
function mc(b){var c=r(b?b:"#diViewer");c=w(c,"div");var a="";if(b){if(c.style.opacity)return;a="1"}for(;c;)c.style.opacity=a,c=w(c,"div");b&&window.setTimeout(mc,5E3)}function nc(){var b=r("#diViewer").getAttribute("uid");b&&X(b,1)}function oc(){var b=r("#diViewer").getAttribute("uid");b&&X(b,2)}function pc(b){return k(function*(){yield lc("video",r("#diViewer"));yield lc("audio",r("#diViewer"));Ab(b)})}function qc(){var b=r();b&&b.src&&window.URL.revokeObjectURL(b.src)}
function lc(b,c){return k(function*(){var a=r(b,c),d=a.currentTime;a.src&&(a.removeAttribute("src"),a.load());if(a.fid){navigator.serviceWorker&&navigator.serviceWorker.controller.postMessage({action:3,fid:a.fid});var e=N[N.length-1].j,f=a.g,g;P||(P=[]);for(g=0;g<P.length;g++)if(P[g].K==e){P[g].H=a.fid;P[g].ha=d;break}g==P.length&&P.push({H:a.fid,K:e,ha:d});delete a.fid;delete a.g;yield K.kb(P[g],g);Pb(g,f);Lb(!0)}v(a);return a})}
function rc(b){if((b=b.getAttribute("parentId"))&&P){var c;for(c=0;c<P.length;c++)if(P[c].K==b)return c}return-1}
function Rb(b,c){return k(function*(){r("close","#divHistory","span.name").click();var a=r(b);a=t("li",a);a=rc(a);if(!(0>a)){var d=P[a];a=d.H;var e=d.K;d=d.ha;S("loading");for(var f=[];e&&e!=N[0].j;){var g=yield F.ca({aa:e}).catch(function(){});g?(g.o=Jb(g.o),f.unshift(g),g.J==N[0].J?e=void 0:e=g.J):e=void 0}if(e==N[0].j){f.unshift(N[0]);e=Eb("#divMain");g=0;var l=q("li",e);for(g=0;g<l.length;g++)l[g].classList.contains("template")||l[g].remove();for(g=0;g<f.length;g++)Tb(e,f[g],g,!0);N=f;if(f=yield T(!0,
!1)){for(e=e=0;e<f.length&&f[e].j!=a;e++);e<f.length&&(c?X(a,2):(d&&r("#diViewer").setAttribute("ctime",d),X(a)))}}else S("cantPlayRecent")}})}function Sb(b){Rb(b,!0)}function sc(b){b=r(b);var c=t("div",b),a=c.getAttribute("ctime");a&&(c.removeAttribute("ctime"),b.currentTime=a)}function Qb(b){return k(function*(){var c=r(b);c=t("li",c);var a=rc(c);0>a||(c.remove(),P.splice(a,1),yield K.qb(a),0==P.length&&Lb(!1))})};const tc=window.Worker?!0:!1;var Y=null;function uc(b){this.h=b;this.g=[];this.l=function(c){return this.h.j==c.j};this.s=function(c){return this.h.o==c};this.m=function(c){var a;for(a=0;a<this.g.length;a++)if(this.g[a].s(c))return this.g[a];return null};this.i=function(c){var a;for(a=0;a<this.g.length;a++)if(this.g[a].l(c))return this.g[a];c=new uc(c);this.g.push(c);return c}}var vc=null;
function V(b,c){var a=[],d=b.getElementsByTagName("li");for(b=0;b<d.length;b++){var e=d[b];if(!e.classList.contains("header")&&!e.classList.contains("template"))if(c){var f=c(e);2!=f&&-2!=f||a.push(e);if(0>f)break}else a.push(e)}return a}function wc(b){b=r(b);v(b);Y?(b=t("li",b),b={type:9,rowIdx:x(b,"rowIdx")},Y.postMessage(b)):b.setAttribute("canceled","1")}
function xc(b,c,a){var d=0,e=0;c||(c=r(".zb-qbutton"));!a&&c.hasAttribute("count")&&(a=x(c,"count"));c.hasAttribute("fincount")&&(d=x(c,"fincount"));c.hasAttribute("stopcount")&&(e=x(c,"stopcount"));switch(b){case 1:d++;c.setAttribute("fincount",d);break;case 3:c.setAttribute("haserr","1");case 2:e++,c.setAttribute("stopcount",e)}0<a?r("div",c).style.width=Math.floor(100*d/a)+"%":r("div",c).style.width="0%";a==d+e&&(c.hasAttribute("haserr")?c.classList.add("error"):c.classList.add("done"))}
function yc(b){var c=r(".zb-qbutton"),a=0;c.hasAttribute("count")&&(a=x(c,"count"));a+=b;c.setAttribute("count",a);xc(0,c,a);c.classList.contains("error")&&c.classList.remove("error");c.classList.contains("done")&&c.classList.remove("done");u(c)}
function zc(b){b=t(".zb-queue",r(b));var c=r(".zb-qbutton");b.style.top="100%";if(c.classList.contains("done")||c.classList.contains("error")){v(c);c.removeAttribute("count");c.removeAttribute("fincount");c.removeAttribute("stopcount");c.removeAttribute("haserr");b=r("ul",b);c=V(b);var a;for(a=c.length-1;0<=a;a--)b.removeChild(c[a]);b.removeAttribute("rowCount")}}
function Ac(b,c,a){var d=0;b.hasAttribute("rowCount")&&(d=x(b,"rowCount"));var e=r("template",b,"li.class").cloneNode(!0);e.classList.remove("template");e.setAttribute("rowIdx",d);a&&e.setAttribute("downFl",1);b.setAttribute("rowCount",d+1);d=q("span",e);var f;for(f=0;f<d.length;f++){var g=d[f];switch(g.getAttribute("name")){case "cancel":g.addEventListener("click",wc);break;case "icon":r("label",g).innerText=c;a?A(g,"download"):A(g,"upload");break;case "elTime":ka(g,"label").innerText=window.msgs.elTime;
break;case "esTime":ka(g,"label").innerText=window.msgs.esTime;break;case "speed":g.innerText=window.msgs.waiting}}b.appendChild(e);return e}function Bc(b,c){c||(c=r("ul","#divQueue"));c=V(c,function(a){return a.getAttribute("rowIdx")==b?-2:1});return 0<c.length?c[0]:null}function Cc(b,c){var a=0;if(1==b)a=1;else if(2!=b)return;b=q("svg",".zb-qbutton")[a];c?b.classList.add("pulse"):b.classList.remove("pulse")}
function Dc(b,c){var a=null,d=q("span",b),e="";switch(c.type){case 0:e="0%";Cc(c.wtype,!0);break;case 1:e=Math.round(100*c.posn/c.size)+"%";break;case 2:e="100%";case 3:Cc(c.wtype)}var f;for(f=0;f<d.length;f++){var g=d[f];switch(g.getAttribute("name")){case "icon":a=g;break;case "percent":switch(c.type){case 0:case 1:g.innerText=e;break;case 2:c.errr||(g.innerText=e)}break;case "elTime":switch(c.type){case 1:case 2:case 3:g.innerText=oa(Math.floor((Date.now()-c.begin)/1E3))}break;case "esTime":switch(c.type){case 1:g.innerText=
oa(Math.round((c.size-c.posn)/c.spd))}break;case "speed":switch(c.type){case 1:g.innerText=B(c.spd)+"/s";break;case 2:case 3:c.errr||(b.classList.add("done"),g.innerText=window.msgs.avspeed.replace("{0}",B(1E3*c.posn/(Date.now()-c.begin))))}break;case "cancel":switch(c.type){case 0:u(g);break;case 2:case 3:var l=r("svg",g);l.removeChild(l.firstElementChild);c.errr||3==c.type?(A(g,"multi"),xc(c.errr?3:2)):(A(g,"chkbox",void 0,"#10B981"),xc(1));u(g)}break;default:if((l=t("div",g))&&l.classList.contains("zb-progressbar"))switch(c.type){case 0:case 1:g.style.width=
e;break;case 2:c.errr?(b.classList.add("error"),l.innerText=c.errr):g.style.width=e}}}return a}function Ec(b,c){switch(c.type){case 0:case 1:Dc(b,c);break;case 2:c.fined&&Y&&Fc();b=Dc(b,c);c.errr||(2==c.wtype?Mb(c.size):1==c.wtype&&c.blob&&(b=r("label",b).innerText,la(c.blob,b,r("#lnkDown"))));window.gc&&window.gc();break;case 3:c.fined&&Y&&Fc(),Dc(b,c),window.gc&&window.gc()}}function Fc(){var b=Y;vc=Y=null;b.terminate();b.g&&T(!0)}
function Gc(b){Y||(Y=new Worker("worker.js"),Y.h={gtoken:F.h?F.h:"",iv:C(I.iv),key:C(I.key),drvid:F.m(),encfname:L[M].encfname?!0:!1},Y.addEventListener("message",function(c){c=c.data;var a=Bc(c.rowIdx);Ec(a,c)}));b.cominf=Y.h;2!=b.type||Y.g||(Y.g=!0);Y.postMessage(b)}function Hc(b){var c=x(b,"rowIdx"),a=r("cancel",b,"span.name");return new Ya(function(){return a.getAttribute("canceled")?!0:!1},function(d){d.rowIdx=c;Ec(b,d)})}
function fc(b){k(function*(){var c=r("ul","#divQueue"),a;yc(b.length);for(a=0;a<b.length;a++){var d=Ac(c,b[a].o,!0);tc?Gc({type:1,rowIdx:x(d,"rowIdx"),downinf:{targetId:b[a].j}}):b[a].J=d.getAttribute("rowIdx")}if(!tc)for(a=0;a<b.length;)d=Bc(parseInt(b[a].J,10),c),yield Hc(d).A(b[a].j),a++})}
function Db(b){k(function*(){var c=r("ul","#divQueue"),a=[],d;yc(b.length);for(d=0;d<b.length;d++){var e=b[d].webkitRelativePath?b[d].webkitRelativePath:b[d].name;var f=Ac(c,e);a.push({rb:e,ab:b[d],la:x(f,"rowIdx")})}vc||(vc=new uc(N[0]));e=vc;for(d=1;d<N.length;d++)e=e.i(N[d]);for(d=0;d<a.length;){f=a[d];var g=yield Ic(e,f.rb);d++;if(tc)Gc({type:2,rowIdx:f.la,upinf:{fname:g.S,file:f.ab,ptid:g.N}});else{var l=Bc(f.la,c);yield Hc(l).C(g.S,f.ab,g.N)}}tc||T(!0)})}
function Ic(b,c){return k(function*(){var a=c.split("/"),d=Ib(a.pop()),e=b;if(0==a.length)return{S:d,N:e.h.j};for(var f=0;f<a.length;){var g=a[f],l=Ib(g);f++;var m=e.m(g);m?e=m:(m=yield F.X({U:l,v:e.h.j}),0==m.length?(l=yield F.ia({K:l,v:e.h.j}),l.o=g,e=e.i(l)):(m[0].o=g,e=e.i(m[0])))}return{S:d,N:e.h.j}})};function Jc(b){return k(function*(){var c=b.data;switch(c.action){case 1:c.cominf={gtoken:F.h?F.h:"",iv:C(I.iv),key:C(I.key),drvid:F.m(),encfname:L[M].encfname?!0:!1};navigator.serviceWorker.controller.postMessage(c);break;case 2:c.msg&&(console.error(c.msg),R(c.msg))}})}
function Nb(){return k(function*(){if(navigator.serviceWorker){yield navigator.serviceWorker.register("sw.js");yield navigator.serviceWorker.ready;navigator.serviceWorker.addEventListener("message",Jc);var b=r("btnUnregSw",void 0,"button.iid");u(b);return!0}return!1})}
function Kc(){return k(function*(){if(!navigator.serviceWorker)return console.error("no service worker"),!1;var b=yield navigator.serviceWorker.getRegistration();if(!b)return console.error("no service worker registration"),!1;if(!window.confirm(window.msgs.unswConfirm))return!1;(b=yield b.unregister())&&console.debug("service worker uninstalled.");var c=r("btnUnregSw",void 0,"button.iid");v(c);return b})};var Z=null;function Lc(b){switch(b){case 1:b=r(".zb-nav-tools");b={T:r("button",b),L:w(b)};break;case 2:b=r("button",r(".zb-main-header","#divMain"));b={T:b,L:w(b)};break;case yb:b={L:r("#ulIteMenu")};break;default:return null}return b}function Mc(b){var c=Lc(b);c&&(c.L.style.display="none",c.L.style.maxHeight="0px",c.T&&c.T.addEventListener("click",function(a){a.qa=b}))}
function Nc(b,c){var a=Lc(c);a&&(a.L.style.display?a.L.style.maxHeight&&b.qa==c&&(u(a.L),a.T&&(v(a.T.children[0]),u(a.T.children[1])),window.setTimeout(function(){a.L.style.maxHeight="";a.L.style.paddingTop="";a.L.style.paddingBottom=""},50)):a.L.style.maxHeight||b.qa==c&&!a.T||(a.L.style.paddingBottom="0px",a.L.style.maxHeight="0px",window.setTimeout(function(){a.T&&(u(a.T.children[0]),v(a.T.children[1]));a.L.style.paddingTop="0px";v(a.L)},500)))}
function Oc(b){Nc(b,1);Nc(b,2);Nc(b,yb);4!=b.qa&&v("#divInpName")}function Pc(b){b=b.target||b.srcElement;"INPUT"!=b.tagName&&(b=r("input",t("div",b)),b.focus(),b.click())}function Qc(b){var c=t("li",b);switch(b.getAttribute("iid")){case "menuGeneral":c.addEventListener("click",gb);break;case "menuDrive":c.addEventListener("click",ib);break;case "menuHistory":c.addEventListener("click",function(){r("#divHistory").style.top=""})}}
function Rc(){return k(function*(){var b=r("label",t("li")),c=b.getAttribute("iid");b=w(b);switch(c){case "menuNewFldr":b&&b.classList.add("rotate-90");yield zb("new");b&&b.classList.remove("rotate-90");break;case "menuUpload":b&&b.classList.add("rotate-90");yield zb("upload");r("#upfiles").value=null;r("#upfolder").value=null;b&&b.classList.remove("rotate-90");break;case "menuMovefs":b&&b.classList.add("rotate-90");yield dc();b&&b.classList.remove("rotate-90");break;case "menuDownfs":(b=hc(!0))&&
fc(b);break;case "menuDelfs":yield ec()}})}function Sc(b,c){b=r(b,c);b.addEventListener("canplay",sc);b.addEventListener("ended",function(){X(t("div").getAttribute("uid"),2,!0)})}
window.addEventListener("load",function(){var b=RegExp("android","i").test(navigator.userAgent),c=r("#divMessage"),a=q("span",c);a[a.length-1].children[0].addEventListener("click",function(){Q(0)});document.addEventListener("click",Oc);Mc(1);Mc(2);Mc(yb);var d=0;c=0;a=q("span",r(".zb-nav-tools"));for(d=0;d<a.length;d++)Qc(a[d]);a=q("label",r(".zb-nav-menu"));for(d=0;d<a.length;d++)Qc(a[d]);a=q(".zb-settings");for(d=0;d<a.length;d++){var e=q(".checkbox",a[d]);for(c=0;c<e.length;c++)e[c].addEventListener("click",
Pc)}r("#chkOwnSecret").addEventListener("click",function(f){f=f.target||f.srcElement;var g=q(".ownsecret","#divSet"),l;for(l=0;l<g.length;l++)f.checked?u(g[l]):v(g[l])});c=r("#divSet");a=q("button",c);for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("iid")){case "btnLogout":c.addEventListener("click",cb);break;case "btnCancel":c.addEventListener("click",lb);break;case "btnOk":c.addEventListener("click",kb)}a=q("span",r("#divPwd"));for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("tid")){case "spanAddRoot":c.addEventListener("click",
mb);break;case "spanDeleteRoot":c.addEventListener("click",ob);break;case "spanMoreKey":b?c.addEventListener("click",rb):c.style.display="none";break;case "spanClearKey":b?c.addEventListener("click",nb):c.style.display="none"}a=q("button",r("#divPwd"));for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("iid")){case "btnCancel":c.addEventListener("click",qb);break;case "btnOk":c.addEventListener("click",sb);break;case "btnDropDb":c.addEventListener("click",xb);break;case "btnUnregSw":c.addEventListener("click",
Kc)}c=r("#divModal");c.addEventListener("click",Ab);c.children[0].addEventListener("click",function(f){f.stopPropagation()});a=q("button",c);for(d=0;d<a.length;d++)switch(c=a[d],c.getAttribute("iid")){case "btnCancel":c.addEventListener("click",Ab);break;case "btnOk":c.addEventListener("click",Bb)}a=q(".zb-main-menu");for(d=0;d<a.length;d++)for(b=q("li",a[d]),c=0;c<b.length;c++)b[c].addEventListener("click",Rc);c=r("#chkAll");c.addEventListener("click",ac);w(c).addEventListener("click",ac);a=q("li",
"#ulIteMenu");for(d=0;d<a.length;d++)a[d].addEventListener("click",bc);c=r("#divInpName");c.addEventListener("click",function(f){f.stopPropagation()});r("input",c).addEventListener("keyup",ic);r("span",c).addEventListener("click",jc);c=r("#diViewer");c.addEventListener("click",mc);c.addEventListener("touchstart",function(f){Z||1!=f.changedTouches.length||(f=f.changedTouches[0],Z={j:f.identifier,ub:f.screenX,vb:f.screenY})});c.addEventListener("touchend",function(f){if(Z){var g=null,l;for(l=0;l<f.changedTouches.length;l++)if(f.changedTouches[l].identifier==
Z.j){g=f.changedTouches[l];break}g&&(f=g.screenX-Z.ub,g=g.screenY-Z.vb,10>g&&-10<g&&(50<f?nc():-50>f&&oc()));Z=null}});r("button",c).addEventListener("click",function(){cc(t("div").getAttribute("uid"))});r("img",c).addEventListener("load",qc);Sc("audio",c);Sc("video",c);document.addEventListener("fullscreenchange",function(){document.fullscreen?r("#diViewer").classList.add("full"):r("#diViewer").classList.remove("full")});c=t("zb-viewer",c,"div.class");a=q("span",c);for(d=0;d<a.length;d++)switch(a[d].getAttribute("name")){case "close":a[d].addEventListener("click",
pc);break;case "previous":a[d].addEventListener("click",nc);break;case "next":a[d].addEventListener("click",oc);break;case "fullscreen":a[d].addEventListener("click",function(){t("div","#diViewer",void 0,!0).requestFullscreen()})}c=t("zb-modal",c,"div.class");c.addEventListener("click",pc);c.children[0].addEventListener("click",function(f){f.stopPropagation()});r(".zb-qbutton").addEventListener("click",function(){r("#divQueue").style.top=""});r("close","#divQueue","span.name").addEventListener("click",
zc);r("close","#divHistory","span.name").addEventListener("click",function(){r("#divHistory").style.top="100%"});Kb()});
