function k(c){function e(b){return c.next(b)}function a(b){return c.throw(b)}return new Promise(function(b,d){function f(g){g.done?b(g.value):Promise.resolve(g.value).then(e,a).then(f,d)}f(c.next())})}function n(c){return k(c())};const t={bmp:"image/bmp",gif:"image/gif",jpe:"image/jpeg",jpeg:"image/jpeg",jpg:"image/jpeg",png:"image/png",webp:"image/webp"},y={aac:"audio/aac",mp3:"audio/mpeg",wav:"audio/wav"},aa={avi:"video/x-msvideo",mp4:"video/mp4",mpeg:"video/mpeg"};function z(c){if(!c)return null;var e=c.charAt(0);if("?"==e||"#"==e)c=c.substring(1);var a={};c.split("&").forEach(function(b){var d=b.indexOf("=");0>d?a[decodeURIComponent(b)]="":a[decodeURIComponent(b.substring(0,d))]=decodeURIComponent(b.substring(d+1))});return a}function B(c,e){var a=[],b;for(b in c)e?a.push(b.concat("=").concat(c[b])):a.push(encodeURIComponent(b).concat("=").concat(encodeURIComponent(c[b])));return 0<a.length?"?".concat(a.join("&")):""}
function ba(){return new Promise(function(c){setTimeout(c,500)})};function F(c){var e=CryptoJS.MD5(c);c=CryptoJS.kdf.OpenSSL.execute(c,8,4,e);c.iv.clamp();c.key.clamp();return c}function G(c){var e=Array(c.sigBytes);c=c.words;for(var a=0,b=0;b<c.length;b++){for(var d=c[b],f=a+4-1;f>=a;f--)f<e.length&&(e[f]=d&255),d>>=8;a+=4;if(a>=e.length)break}return e}
function ca(c){this.u=!0;this.g=c.P;this.h=this.m=this.iv=this.key=null;this.j=this.l=this.i=0;this.o=[];c.ja&&(this.u=!1);if(!this.g)throw Error("reader must be specified.");if(c.J){var e=null;e="string"==typeof c.J?F(c.J):c.J;this.key=e.key;this.iv=e.iv}else throw Error("keycfg must be specified.");this.s=function(a){return new Promise(function(b){switch(this.j){case 1:a&&(this.j=2);this.o.push(b);break;case 2:b(!1);break;default:this.j=a?2:1,b(!0)}}.bind(this))};this.I=function(){0<this.j&&(this.o.length?
this.o.shift()(!0):1==this.j&&(this.j=0))};this.F=function(){const a=this;return n(function*(){if(a.l)return a.l;if(a.u)return a.l=16*Math.ceil((a.g.h()+1)/16),a.l;0==a.g.h()&&(yield a.D());var b=a.g.h()-16,d=yield a.G(b);a.l=b+d.length;return a.l})};this.D=function(a){const b=this;return n(function*(){var d=a||0;if(a){if(b.u)throw Error("Can NOT set offset for encryption.");a-=a%16+16;0>a&&(a=0)}yield b.g.H(a);var f={iv:b.iv,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7};d&&(f.iv=yield b.v(16));
b.m=b.u?CryptoJS.algo.AES.createEncryptor(b.key,f):CryptoJS.algo.AES.createDecryptor(b.key,f);b.i=d;b.h=null})};this.G=function(a,b){const d=this;return n(function*(){var f=b||d.g.$(),g=null,l=0<=a?a:d.g.u();if(d.i==l&&d.h){if(f<=d.h.length)return d.i+=f,g=d.h.slice(0,f),d.h=d.h.slice(f),0==d.h.length&&(d.h=null),g;g=d.h;l+=d.h.length;d.i+=d.h.length;f-=d.h.length}var h=16*Math.ceil((l%16+f)/16);d.m&&d.i==l||(yield d.D(l),h+=16);var m=yield d.v(h);h=G(d.m.process(m));d.g.G()&&(h=h.concat(G(d.m.finalize())));
l<d.g.u()?(l-=d.g.u()-m.sigBytes,0<l&&(h=h.slice(l)),h.length>f&&(d.h=h.slice(f),h=h.slice(0,f)),d.i+=f):h=null;g?h&&(g=g.concat(h)):h&&(g=h);return g})};this.H=function(){this.g.D();this.m=this.g=null};this.C=function(){return this.g.C()};this.v=function(a){const b=this;return n(function*(){var d=yield b.g.I(a);return new CryptoJS.lib.WordArray.init(d)})}};function da(){this.h=!0;this.g=null;this.j=!1;this.G=function(){var c=null;if(this.h)try{c=window.sessionStorage.getItem("login_state")}catch(e){this.h=!1,console.error(e)}return c};this.o=function(c){var e=this.G();return e&&c==e?!0:!1};this.i=function(c,e){if(this.h)try{return window.sessionStorage.setItem(c,e.toString()),!0}catch(a){this.h=!1,console.error(a)}return!1};this.m=function(c){if(this.h)try{window.sessionStorage.removeItem(c)}catch(e){this.h=!1,console.error(e)}};this.s=function(){var c=
this.l("relay_url");return c?c:""};this.D=function(){var c=null,e=this.C("extra_info");e&&(c=JSON.parse(e));return c&&2==c.length?{aa:c[0],S:c[1]}:null};this.v=function(c){c?(c="string"===typeof c?c:JSON.stringify([c.aa,c.S]),this.i("drive_extra",c),this.u("extra_info",c)):(this.m("drive_extra"),this.u("extra_info",null))};this.H=function(c){if(window.indexedDB){var e=window.indexedDB.open("zgayard1946");e.onerror=function(){if(c)c("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");
};e.onupgradeneeded=function(a){a.target.result.createObjectStore("settings",{keyPath:"key"})};e.onsuccess=function(a){var b=a.target.result;a=b.transaction("settings","readwrite");a.oncomplete=function(){b.close();c&&c()};a.objectStore("settings").getAll().onsuccess=function(d){this.g={};d.target.result.forEach(function(f){this.g[f.key]=f.value}.bind(this));this.j=(d=this.g.drive)&&this.g[d]&&this.g[d].refresh_token?!0:!1}.bind(this)}.bind(this)}else if(c)c("IndexedDB is not supported in your browser settings.");
else throw Error("IndexedDB is not supported in your browser settings.");};this.C=function(c){var e=this.l("drive");return e&&(e=this.g[e])?e[c]:null};this.u=function(c,e){if(this.g){var a=this.l("drive");e?(this.g[a]||(this.g[a]={}),this.g[a][c]=e):this.g[a]&&this.g[a][c]&&delete this.g[a][c]}};this.I=function(c,e){window.indexedDB.open("zgayard1946").onsuccess=function(a){var b=a.target.result;a=b.transaction("settings","readwrite");a.oncomplete=function(){b.close();e&&e()};a=a.objectStore("settings");
c&&c(a)}};this.l=function(c){return this.g&&this.g[c]?this.g[c]:null};this.saveData=function(c,e,a){this.g&&(this.g[c]=e);this.I(function(b){b.put({key:c,value:e})}.bind(this),a)}};var H={};function I(c,e,a){this.B=c;this.M=e;this.g=a}I.prototype.C=function(){return this.M};function J(c,e){this.C=null;this.G=e;this.h=null;this.g=c;this.N||(this.N=function(){})}function L(c){null==c.C&&(c.C=c.g.s());return c.C}
function M(c,e){return n(function*(){var a="POST",b=c.l().concat(encodeURI(e.pa)),d=new Headers;if(e&&e.A)d.append("Authorization",e.A);else if(e&&e.V){var f="Bearer";e&&e.W&&(f=e.W);d.append("Authorization",f+" "+e.V)}else d.append("Authorization",c.h);if(e&&e.ma)for(var g of e.ma.entries())d.append(g[0],g[1]);e&&e.ea&&(a=e.ea);a=yield fetch(b,{method:a,body:e.ua,headers:d,redirect:"follow"});401==a.status&&c.g.j&&!e.na&&(a=yield ea(c,e));return a})}
J.prototype.u=function(){const c=this;return n(function*(){var e=c.g.j,a={},b,d=z(window.location.search);(b=z(window.location.hash))&&(d=d?Object.assign(d,b):b);if((b=d)&&b.token_type&&b.access_token){c.h=b.token_type+" "+b.access_token;c.g.i("access_token",c.h);if(b&&b.state)if(c.g.o(b.state))c.g.m("login_state");else return"Unauthorized access to this url.";return null}b&&b.code?a.code=b.code:e&&(a.Z=c.g.C("refresh_token"));if(d=c.g.D())a.clientId=d.aa,a.ha=d.S;if(a.code||a.Z){if(b&&b.state)if(c.g.o(b.state))c.g.m("login_state");
else return"Unauthorized access to this url.";if((a=yield N(c,a))&&a.token_type&&a.access_token)return d&&a.client_secret_enc&&(d.S=a.client_secret_enc,c.g.v(d)),c.h=a.token_type+" "+a.access_token,c.g.i("access_token",c.h),e&&a.refresh_token&&c.g.u("refresh_token",a.refresh_token),a.logout&&c.g.i("logout_url",a.logout),null}else if(e&&(a.ia=!0),(a=yield N(c,a))&&a.url)return d&&a.client_secret_enc&&(d.S=a.client_secret_enc,c.g.v(d)),a.state&&(c.g.i("login_state",a.state)||(a.state=c.m())),a.logout&&
c.g.i("logout_url",a.logout),window.location.href=a.url.concat("&state=".concat(encodeURIComponent(a.state))),"redirect";return a&&a.error?"["+a.error+"] "+a.error_description:"Unknown error occured when doing authorization."})};J.prototype.i=function(){return n(function*(){})};J.prototype.j=function(){return n(function*(){})};J.prototype.D=function(){};J.prototype.v=function(c){return new fa(c,this)};function ha(c){return n(function*(){return{oa:c.status,ga:yield c.text()}})}
function O(c,e,a,b){return n(function*(){var d={pa:e,ea:"GET"};b.W&&(d.W=b.W);b.V&&(d.V=b.V);b.A&&(d.A=b.A);d=yield M(c,d);var f=yield ha(d);if(a&&d.status!=a)throw Error(JSON.stringify(f));return f})}function P(c,e,a){return n(function*(){return(yield O(c,e,200,a)).ga})}
function N(c,e){return n(function*(){if(!e)throw Error("Options are not specified when auth onedrive.");var a=new FormData;a.append("drive_type",c.m());e.clientId&&a.append("client_id",e.clientId);e.sa&&a.append("redirect_uri",e.sa);e.ha&&a.append("client_secret",e.ha);e.code?a.append("code",e.code):e.Z?a.append("refresh_token",e.Z):e.ia&&a.append("need_code",e.ia);a=yield fetch(c.G,{method:"POST",body:a,credentials:"include",redirect:"follow"});if(200==a.status)return yield a.json();var b=yield a.text();
throw Error(b+" ("+a.status+")");})}function ea(c,e){return n(function*(){console.log("Retry to send ajax.");if(e)e.na=!0;else return null;var a=yield c.u();if(a)return console.error(a),null;e.A=c.h;return yield M(c,e)})}
function ia(c){c.X=J;if("function"===typeof Object.create)c.prototype=Object.create(J.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});else{var e=function(){};e.prototype=J.prototype;c.prototype=new e;c.prototype.constructor=c}c.prototype.ra||(c.prototype.ra=function(){return this.constructor.X});c.prototype.N||(c.prototype.N=function(...a){return this.constructor.X.call(this,...a)});c.prototype.ta||(c.prototype.ta=function(a,...b){return a?this.constructor.X.prototype[a].call(this,
...b):this.constructor.X.call(this,...b)})}function Q(c,e,a){ia(a);H[c]=new I(c,e,a)}
function fa(c,e){this.l=e;this.o=c;this.url="";this.name=null;this.v=this.i=this.g=this.size=0;this.R=!1;this.s=16E3;c.Y&&(this.s=c.Y);this.m=this.j=0;this.H=function(a){const b=this;return n(function*(){if(b.R)if(b.i&&(b.v=b.i,b.i=0),a){if(a>=b.h())throw console.log("offset:"+a+",size:"+b.h()),Error("offset can not be bigger than input size.");b.g=a}else b.g=0;else{var d=yield b.l.j(b.o);b.R=!0;if(d){if(b.size=d.K||0,b.url=d.B,b.name=d.M,b.m="1"==d.L?1:0,a){if(a>=b.h())throw Error("offset can not be bigger than input size.");
b.g=a}}else throw Error("Failed to prepare reader.");}})};this.C=function(){return this.name};this.$=function(){return this.s};this.u=function(){return this.g};this.h=function(){return this.size};this.G=function(){return this.g>=this.h()};this.I=function(a){const b=this;return n(function*(){a||(a=b.s);return yield b.F(a)})};this.D=function(){};this.F=function(a){const b=this;return n(function*(){if(a&&b.i)return null;if(a)b.i=a;else if(b.i)a=b.i;else throw Error("size must be specified.");if(b.v)return null;
var d=b.g+a-1,f=function(){const g=this;return n(function*(){var l=g.url,h=new Headers;10<=g.j&&(l=L(g.l),h.append("Zb-Url",g.url));g.l.D(h,g.o.A);h.append("Range","bytes="+g.g+"-"+d);try{var m=yield fetch(l,{method:"GET",headers:h,redirect:"follow"});if(g.v){if(g.v=0,g.i)return yield g.F()}else{g.i=0;g.j=10>g.j?1:11;if(200==m.status||206==m.status){2==g.m&&(g.m=1);var p=parseInt(m.headers.get("content-length"),10);if(p)g.g+=p;else{var q=m.headers.get("content-range");if(q){var r=q.indexOf("-");if(0>
r)var u=0;else{r++;var C=q.indexOf("/",r);u=C<=r?0:parseInt(q.slice(r,C),10)}}else u=0;g.g=u?u+1:d+1}200==m.status&&g.g<g.h()?g.g=g.h():g.g>g.h()&&(g.g=g.h());return yield m.arrayBuffer()}if(401==m.status&&1==g.m){console.log("Retry auth.");g.m=2;var v=yield g.l.u();if(v)console.error(v);else return g.o.A&&delete g.o.A,yield f()}else{var D=yield m.text();throw Error(D+" ("+m.status+")");}}}catch(x){if(0==g.j&&L(g.l))return g.j=10,yield f();if(1==g.j||11==g.j)return g.j++,yield ba(),yield f();throw x;
}})}.bind(b);return yield f()})}};Q("onedrive","Microsoft OneDrive",function(c,e){this.N(c,e);this.m=function(){return"onedrive"};this.i=function(a){const b=this;return n(function*(){return yield b.s(a)})};this.j=function(a){const b=this;return n(function*(){var d="/me/drive/items/".concat(a.B),f={};a.A&&(f.A=a.A);d=yield P(b,d.concat(B({select:"name,size,@microsoft.graph.downloadUrl"},!0)),f);f=null;d&&(d=JSON.parse(d),f={B:d["@microsoft.graph.downloadUrl"],M:d.name,K:d.size});return f})};this.l=function(){return"https://graph.microsoft.com/v1.0"};
this.s=function(a){const b=this;return n(function*(){var d=yield O(b,("/me/drive/items/"+a.U).concat(B({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),0,a);if(200==d.oa)return b.o(JSON.parse(d.ga));throw Error(JSON.stringify(d));})};this.o=function(a){var b={B:a.id,M:a.name,K:a.size,da:a.lastModifiedDateTime,va:a.parentReference.path,fa:a.parentReference.id,L:"0"};a.folder?b.L="1":a.file&&(b.L="2");return b}});Q("googledrive","Google Drive",function(c,e){this.N(c,e);this.m=function(){return"googledrive"};this.i=function(a){const b=this;return n(function*(){var d=b.s().concat(a.U);d=yield P(b,d.concat(B({fields:"id,name,mimeType,parents,modifiedTime,size"},!0)),a);return b.o(JSON.parse(d))})};this.j=function(a){const b=this;return n(function*(){var d=b.s().concat(a.B),f={U:a.B};a.A&&(f.A=a.A);if(f=yield b.i(f))f.B=b.l().concat(encodeURI(d)).concat(B({alt:"media"})),b.g.j&&(f.L="1");return f})};this.D=function(a,
b){b?a.append("Authorization",b):a.append("Authorization",this.h?this.h:"")};this.l=function(){return"https://www.googleapis.com"};this.s=function(){return"/drive/v3".concat("/files/")};this.o=function(a){var b={B:a.id,M:a.name,K:a.size,da:a.modifiedTime,L:"2"};a.parents&&0<a.parents.length&&(b.fa=a.parents[0]);this.F(a.mimeType)&&(b.L="1");return b};this.F=function(a){return"application/vnd.google-apps.folder"==a}});function ja(c,e){this.v=e;this.s=c;this.g=null;this.i=this.size=0;this.j=null;this.o=this.l=0;this.m=1600;c.Y&&(this.m=c.Y);this.H=function(a){const b=this;return n(function*(){var d=yield b.v.j(b.s);if(d)b.size=d.K||0,d=yield b.v.I(b.s.B),b.g=d,b.g.sort(function(f,g){return f.ca-g.ca}),b.F(a);else throw Error("Failed to prepare reader.");})};this.$=function(){return this.m};this.u=function(){return this.i};this.h=function(){return this.size};this.G=function(){return this.g?this.l>=this.g.length:
!0};this.I=function(a){const b=this;return n(function*(){if(!b.j){var d=yield b.v.H(b.g[b.l].B);d=CryptoJS.enc.Base64url.parse(d);b.j=G(d)}return yield b.R(a)})};this.D=function(){this.j=this.g=null};this.F=function(a){if(a){if(a>=this.h())throw Error("offset can not be bigger than input size.");this.i=a;var b=0;for(a=0;a<this.g.length&&!(b+=this.g[a].K,this.i<b);a++)this.o=b;if(a<this.g.length)this.l=a;else throw Error("offset can not be bigger than input size.");}else this.l=this.o=this.i=0;this.j=
null};this.R=function(a){const b=this;return n(function*(){var d=b.i-b.o,f=b.j.length-d;a?a<f&&(f=a):b.m<f&&(f=b.m);var g=new Uint8Array(b.j.slice(d,d+f));b.i+=f;b.j.length==d+f&&(b.j=null,b.l++,b.o=b.i);return g.buffer})}}
Q("idxdb","Loacal Indexed DB",function(c,e){this.N(c,e);this.m=function(){return"idxdb"};this.u=function(){return new Promise(function(a){this.qa(a)})};this.i=function(a){const b=this;return n(function*(){var d=yield b.s(a.U);return d&&0<d.length?d[0]:null})};this.v=function(a){return new ja(a,this)};this.j=function(a){const b=this;return n(function*(){return yield b.i({U:a.B})})};this.l=function(){return""};this.saveData=function(a,b,d,f){const g=this;return n(function*(){yield g.o(function(l){l.put({key:a+
":"+b+"_"+d,data:f})})})};this.I=function(a){const b=this;return n(function*(){var d=[];yield b.o(function(f){f.getAllKeys().onsuccess=function(g){g.target.result.forEach(function(l){var h=l.indexOf(":");if(l.substring(0,h)==a){var m=l.substring(h+1);h=m.indexOf("_");d.push({B:l,ca:parseInt(m.substring(0,h),10),K:parseInt(m.substring(h+1),10)})}})}});return d})};this.H=function(a){const b=this;return n(function*(){var d="";yield b.o(function(f){f.get(a).onsuccess=function(g){d=g.target.result.data}});
return d})};this.qa=function(a){if(window.indexedDB){var b=window.indexedDB.open("zgalocaldb");b.onerror=function(){if(a)a("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");}.bind(this);b.onupgradeneeded=function(d){d=d.target.result;d.createObjectStore("items",{keyPath:"key"});d.createObjectStore("datas",{keyPath:"key"})}.bind(this);b.onsuccess=function(d){d.target.result.close();a&&a()}.bind(this)}else if(a)a("IndexedDB is not supported in your browser settings.");
else throw Error("IndexedDB is not supported in your browser settings.");};this.F=function(a){return new Promise(function(b){window.indexedDB.open("zgalocaldb").onsuccess=function(d){var f=d.target.result;d=f.transaction("items","readwrite");d.oncomplete=function(){f.close();b()}.bind(this);d=d.objectStore("items");a&&a(d)}.bind(this)})};this.o=function(a){return new Promise(function(b){window.indexedDB.open("zgalocaldb").onsuccess=function(d){var f=d.target.result;d=f.transaction("datas","readwrite");
d.oncomplete=function(){f.close();b()}.bind(this);d=d.objectStore("datas");a&&a(d)}.bind(this)}.bind(this))};this.s=function(a){const b=this;return n(function*(){var d=[];yield b.F(function(f){f.getAll().onsuccess=function(g){g.target.result.forEach(function(l){var h=!0;a&&(h=a==l.key);h&&d.push({B:l.key,M:l.name,K:l.size,da:l.tms,L:l.type,fa:l.pid})})}});return d})}});self.importScripts("vendor/crypto-js.js");window=self;var R=null,S=null,T=null;function ka(){return new Promise(function(c,e){var a=new da;a.H(function(b){b?e(b):c(a)})})}function X(c,e){return n(function*(){var a=yield self.clients.get(c);a&&a.postMessage(e)})}
function la(c){return n(function*(){var e="";try{var a={iv:CryptoJS.enc.Base64url.parse(c.iv),key:CryptoJS.enc.Base64url.parse(c.key)};R||(R=yield ka());var b=H[c.drvid];if(b){var d=new b.g(R,"https://zgayard.f5.si/grantauth.php");d.h=c.gtoken;S={ka:d,J:a,la:c.encfname,T:new Map}}else e="Drive's name is invalid."}catch(f){console.error(f),e=f.message||f}return e})}function ma(c){return new Promise(function(e){T?e("A conflict has occurred."):(T=e,X(c,{action:1}))})}
function Y(c,e){return{status:c,statusText:(new Map([[200,"OK"],[206,"Partial Content"],[404,"Not Found"],[409,"Conflict"],[500,"Internal Server Error"],[503,"Service Unavailable"]])).get(c),headers:e}}function Z(c,e,a){a&&X(a,{action:2,msg:e});return new Response(e,Y(c))}
function na(c,e){return n(function*(){if(!e)return Z(404,"Unkown url format.");var a=c.clientId||c.resultingClientId;if(!a)return Z(503,"Missing client id.");if(!S){var b=yield ma(a);if(b)return Z(503,b,a)}try{var d=S.T.get(e);b=null;d?b=d.P:(b=new ca({ja:!0,J:S.J,P:S.ka.v({B:e})}),d={ba:"",O:"",P:b},S.T.set(e,d));if(!(yield b.s()))return Z(409,"The reader will be disposed.");var f=c.request.headers.get("range"),g=0,l=-1;if(f&&"bytes="==f.substring(0,6)){f=f.substring(6);var h=f.indexOf(",");0<h&&
(f=f.substring(0,h));var m=f.split("-");0<m.length&&(g=parseInt(m[0],10),1<m.length&&m[1]&&(l=parseInt(m[1],10)+1))}var p=g;var q=l;var r=yield b.F();if(!d.O){d.O=b.C();if(S.la){f=d;var u=S.J,C=CryptoJS.enc.Base64url.parse(d.O);h=u;"string"==typeof u&&(h=F(u));if(!(h&&h.iv&&h.key))throw Error("Need iv and key. They can be generated by CryptoJS.kdf.OpenSSL.execute from password and salt.");var v={mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7};Object.assign(v,h);var D=CryptoJS.algo.AES.createDecryptor(v.key,
v);var x=D.process(C);x.concat(D.finalize());x.clamp();var E=x.toString(CryptoJS.enc.Utf8);f.O=E}var U=d.O,V=U.lastIndexOf(".");E="";0<=V&&(E=U.slice(V+1));var K=E.toLowerCase();d.ba=aa[K]||y[K]||t[K]||"binary/octet-stream"}q=Math.min(0>q?r:q,p+8E5);var A=yield b.G(p,q-p);b.I();var oa=p+A.length-1,w=new Headers;w.append("Content-Length",A.length.toString());w.append("Content-Type",d.ba);if(0==p&&A.length==r)return new Response(new Uint8Array(A),Y(200,w));w.append("Accept-Ranges","bytes");w.append("Content-Range",
`bytes ${p}-${oa}/${r}`);return new Response(new Uint8Array(A),Y(206,w))}catch(W){return Z(500,W.message||W,a)}})}self.addEventListener("message",function(c){return n(function*(){var e=c.source.id,a=c.data;switch(a.action){case 1:a=yield la(a.cominf);T?(T(a),T=null):a&&(yield X(e,{action:2,msg:a}));break;case 3:if(e=a.fid,S&&e&&(a=S.T.get(e)))S.T.delete(e),(yield a.P.s(!0))&&a.P.H()}})});self.addEventListener("activate",function(c){c.waitUntil(self.clients.claim())});
self.addEventListener("fetch",function(c){var e=c.request.url,a=e.indexOf("/sw/");0>a||(e=e.substring(a+4),c.respondWith(na(c,e)))});
