function h(c){function d(b){return c.next(b)}function a(b){return c.throw(b)}return new Promise(function(b,e){function f(g){g.done?b(g.value):Promise.resolve(g.value).then(d,a).then(f,e)}f(c.next())})}function n(c){return h(c())};const t={bmp:"image/bmp",gif:"image/gif",jpe:"image/jpeg",jpeg:"image/jpeg",jpg:"image/jpeg",png:"image/png",webp:"image/webp"},aa={aac:"audio/aac",mp3:"audio/mpeg",wav:"audio/wav"},ba={avi:"video/x-msvideo",mp4:"video/mp4",mpeg:"video/mpeg"};function x(c){if(!c)return null;var d=c.charAt(0);if("?"==d||"#"==d)c=c.substring(1);var a={};c.split("&").forEach(function(b){var e=b.indexOf("=");0>e?a[decodeURIComponent(b)]="":a[decodeURIComponent(b.substring(0,e))]=decodeURIComponent(b.substring(e+1))});return a}function y(c,d){var a=[],b;for(b in c)d?a.push(b.concat("=").concat(c[b])):a.push(encodeURIComponent(b).concat("=").concat(encodeURIComponent(c[b])));return 0<a.length?"?".concat(a.join("&")):""}
function ca(){return new Promise(function(c){setTimeout(c,500)})};function A(c){c=c.replace(/-/g,"+").replace(/_/g,"/");var d=c.length%4;0<d&&(c+="====".slice(d));return c}function B(c){for(var d=new Uint8Array(c.length),a=0;a<c.length;a++)d[a]=c.charCodeAt(a);return d}
function F(c){var d=forge.md.md5.create();d.update(c);d=d.digest().getBytes();for(var a=forge.md.md5.create(),b=new forge.util.ByteStringBuffer,e="";48>b.length();)a.start(),e&&a.update(e),a.update(c),a.update(d),e=a.digest().getBytes(),b.putBytes(e);b.truncate(b.length()-48);return{key:b.getBytes(32),iv:b.getBytes()}}
function da(c){this.u=!0;this.g=c.P;this.iv=this.key="";this.j=null;this.h="";this.l=this.m=this.i=0;this.o=[];c.ja&&(this.u=!1);if(!this.g)throw Error("reader must be specified.");if(c.J)c="string"==typeof c.J?F(c.J):c.J,this.key=c.key,this.iv=c.iv;else throw Error("keycfg must be specified.");this.s=function(d){return new Promise(function(a){switch(this.l){case 1:d&&(this.l=2);this.o.push(a);break;case 2:a(!1);break;default:this.l=d?2:1,a(!0)}}.bind(this))};this.I=function(){0<this.l&&(this.o.length?
this.o.shift()(!0):1==this.l&&(this.l=0))};this.F=function(){const d=this;return n(function*(){if(d.m)return d.m;if(d.u)return d.m=16*Math.ceil((d.g.h()+1)/16),d.m;0==d.g.h()&&(yield d.D());var a=d.g.h()-16,b=yield d.G(a);d.m=a+b.length;return d.m})};this.D=function(d){const a=this;return n(function*(){var b=d||0;if(d){if(a.u)throw Error("Can NOT set offset for encryption.");d-=d%16+16;0>d&&(d=0)}yield a.g.H(d);var e=a.iv;b&&(e=yield a.v(16));var f=forge.util.createBuffer(a.key);a.j=a.u?forge.cipher.createCipher("AES-CBC",
f):forge.cipher.createDecipher("AES-CBC",f);a.j.start({iv:e});a.i=b;a.h=""})};this.G=function(d,a){const b=this;return n(function*(){var e=a||b.g.$(),f="",g=0<=d?d:b.g.u();if(b.i==g&&b.h){if(e<=b.h.length)return b.i+=e,f=b.h.substring(0,e),b.h=b.h.substring(e),0==b.h.length&&(b.h=""),f;f=b.h;g+=b.h.length;b.i+=b.h.length;e-=b.h.length}var k=16*Math.ceil((g%16+e)/16);b.j&&b.i==g||(yield b.D(g),k+=16);var l=yield b.v(k);b.j.update(forge.util.createBuffer(l));b.g.G()&&b.j.finish();k=b.j.output.getBytes();
g<b.g.u()?(g-=b.g.u()-l.length,0<g&&(k=k.substring(g)),k.length>e&&(b.h=k.substring(e),k=k.substring(0,e)),b.i+=e):k="";f?k&&(f=f.concat(k)):k&&(f=k);return f})};this.H=function(){this.g.D();this.j=this.g=null};this.C=function(){return this.g.C()};this.v=function(d){const a=this;return n(function*(){var b=yield a.g.I(d);b=new Uint8Array(b);for(var e=[],f=0;f<b.length;)e.push(String.fromCharCode(b[f])),f++;return e.join("")})}};function ea(){this.h=!0;this.g=null;this.j=!1;this.G=function(){var c=null;if(this.h)try{c=window.sessionStorage.getItem("login_state")}catch(d){this.h=!1,console.error(d)}return c};this.o=function(c){var d=this.G();return d&&c==d?!0:!1};this.i=function(c,d){if(this.h)try{return window.sessionStorage.setItem(c,d.toString()),!0}catch(a){this.h=!1,console.error(a)}return!1};this.m=function(c){if(this.h)try{window.sessionStorage.removeItem(c)}catch(d){this.h=!1,console.error(d)}};this.s=function(){var c=
this.l("relay_url");return c?c:""};this.D=function(){var c=null,d=this.C("extra_info");d&&(c=JSON.parse(d));return c&&2==c.length?{aa:c[0],S:c[1]}:null};this.v=function(c){c?(c="string"===typeof c?c:JSON.stringify([c.aa,c.S]),this.i("drive_extra",c),this.u("extra_info",c)):(this.m("drive_extra"),this.u("extra_info",null))};this.H=function(c){if(window.indexedDB){var d=window.indexedDB.open("zgayard1946");d.onerror=function(){if(c)c("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");
};d.onupgradeneeded=function(a){a.target.result.createObjectStore("settings",{keyPath:"key"})};d.onsuccess=function(a){var b=a.target.result;a=b.transaction("settings","readwrite");a.oncomplete=function(){b.close();c&&c()};a.objectStore("settings").getAll().onsuccess=function(e){this.g={};e.target.result.forEach(function(f){this.g[f.key]=f.value}.bind(this));this.j=(e=this.g.drive)&&this.g[e]&&this.g[e].refresh_token?!0:!1}.bind(this)}.bind(this)}else if(c)c("IndexedDB is not supported in your browser settings.");
else throw Error("IndexedDB is not supported in your browser settings.");};this.C=function(c){var d=this.l("drive");return d&&(d=this.g[d])?d[c]:null};this.u=function(c,d){if(this.g){var a=this.l("drive");d?(this.g[a]||(this.g[a]={}),this.g[a][c]=d):this.g[a]&&this.g[a][c]&&delete this.g[a][c]}};this.I=function(c,d){window.indexedDB.open("zgayard1946").onsuccess=function(a){var b=a.target.result;a=b.transaction("settings","readwrite");a.oncomplete=function(){b.close();d&&d()};a=a.objectStore("settings");
c&&c(a)}};this.l=function(c){return this.g&&this.g[c]?this.g[c]:null};this.saveData=function(c,d,a){this.g&&(this.g[c]=d);this.I(function(b){b.put({key:c,value:d})}.bind(this),a)}};var G={};function I(c,d,a){this.B=c;this.M=d;this.g=a}I.prototype.C=function(){return this.M};function J(c,d){this.C=null;this.G=d;this.h=null;this.g=c;this.N||(this.N=function(){})}function K(c){null==c.C&&(c.C=c.g.s());return c.C}
function M(c,d){return n(function*(){var a="POST",b=c.l().concat(encodeURI(d.pa)),e=new Headers;if(d&&d.A)e.append("Authorization",d.A);else if(d&&d.V){var f="Bearer";d&&d.W&&(f=d.W);e.append("Authorization",f+" "+d.V)}else e.append("Authorization",c.h);if(d&&d.ma)for(var g of d.ma.entries())e.append(g[0],g[1]);d&&d.ea&&(a=d.ea);a=yield fetch(b,{method:a,body:d.ua,headers:e,redirect:"follow"});401==a.status&&c.g.j&&!d.na&&(a=yield fa(c,d));return a})}
J.prototype.u=function(){const c=this;return n(function*(){var d=c.g.j,a={},b,e=x(window.location.search);(b=x(window.location.hash))&&(e=e?Object.assign(e,b):b);if((b=e)&&b.token_type&&b.access_token){c.h=b.token_type+" "+b.access_token;c.g.i("access_token",c.h);if(b&&b.state)if(c.g.o(b.state))c.g.m("login_state");else return"Unauthorized access to this url.";return null}b&&b.code?a.code=b.code:d&&(a.Z=c.g.C("refresh_token"));if(e=c.g.D())a.clientId=e.aa,a.ha=e.S;if(a.code||a.Z){if(b&&b.state)if(c.g.o(b.state))c.g.m("login_state");
else return"Unauthorized access to this url.";if((a=yield N(c,a))&&a.token_type&&a.access_token)return e&&a.client_secret_enc&&(e.S=a.client_secret_enc,c.g.v(e)),c.h=a.token_type+" "+a.access_token,c.g.i("access_token",c.h),d&&a.refresh_token&&c.g.u("refresh_token",a.refresh_token),a.logout&&c.g.i("logout_url",a.logout),null}else if(d&&(a.ia=!0),(a=yield N(c,a))&&a.url)return e&&a.client_secret_enc&&(e.S=a.client_secret_enc,c.g.v(e)),a.state&&(c.g.i("login_state",a.state)||(a.state=c.m())),a.logout&&
c.g.i("logout_url",a.logout),window.location.href=a.url.concat("&state=".concat(encodeURIComponent(a.state))),"redirect";return a&&a.error?"["+a.error+"] "+a.error_description:"Unknown error occured when doing authorization."})};J.prototype.i=function(){return n(function*(){})};J.prototype.j=function(){return n(function*(){})};J.prototype.D=function(){};J.prototype.v=function(c){return new ha(c,this)};function ia(c){return n(function*(){return{oa:c.status,ga:yield c.text()}})}
function O(c,d,a,b){return n(function*(){var e={pa:d,ea:"GET"};b.W&&(e.W=b.W);b.V&&(e.V=b.V);b.A&&(e.A=b.A);e=yield M(c,e);var f=yield ia(e);if(a&&e.status!=a)throw Error(JSON.stringify(f));return f})}function P(c,d,a){return n(function*(){return(yield O(c,d,200,a)).ga})}
function N(c,d){return n(function*(){if(!d)throw Error("Options are not specified when auth onedrive.");var a=new FormData;a.append("drive_type",c.m());d.clientId&&a.append("client_id",d.clientId);d.sa&&a.append("redirect_uri",d.sa);d.ha&&a.append("client_secret",d.ha);d.code?a.append("code",d.code):d.Z?a.append("refresh_token",d.Z):d.ia&&a.append("need_code",d.ia);a=yield fetch(c.G,{method:"POST",body:a,credentials:"include",redirect:"follow"});if(200==a.status)return yield a.json();var b=yield a.text();
throw Error(b+" ("+a.status+")");})}function fa(c,d){return n(function*(){console.log("Retry to send ajax.");if(d)d.na=!0;else return null;var a=yield c.u();if(a)return console.error(a),null;d.A=c.h;return yield M(c,d)})}
function ja(c){c.X=J;if("function"===typeof Object.create)c.prototype=Object.create(J.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});else{var d=function(){};d.prototype=J.prototype;c.prototype=new d;c.prototype.constructor=c}c.prototype.ra||(c.prototype.ra=function(){return this.constructor.X});c.prototype.N||(c.prototype.N=function(...a){return this.constructor.X.call(this,...a)});c.prototype.ta||(c.prototype.ta=function(a,...b){return a?this.constructor.X.prototype[a].call(this,
...b):this.constructor.X.call(this,...b)})}function Q(c,d,a){ja(a);G[c]=new I(c,d,a)}
function ha(c,d){this.l=d;this.o=c;this.url="";this.name=null;this.v=this.i=this.g=this.size=0;this.R=!1;this.s=16E3;c.Y&&(this.s=c.Y);this.m=this.j=0;this.H=function(a){const b=this;return n(function*(){if(b.R)if(b.i&&(b.v=b.i,b.i=0),a){if(a>=b.h())throw console.log("offset:"+a+",size:"+b.h()),Error("offset can not be bigger than input size.");b.g=a}else b.g=0;else{var e=yield b.l.j(b.o);b.R=!0;if(e){if(b.size=e.K||0,b.url=e.B,b.name=e.M,b.m="1"==e.L?1:0,a){if(a>=b.h())throw Error("offset can not be bigger than input size.");
b.g=a}}else throw Error("Failed to prepare reader.");}})};this.C=function(){return this.name};this.$=function(){return this.s};this.u=function(){return this.g};this.h=function(){return this.size};this.G=function(){return this.g>=this.h()};this.I=function(a){const b=this;return n(function*(){a||(a=b.s);return yield b.F(a)})};this.D=function(){};this.F=function(a){const b=this;return n(function*(){if(a&&b.i)return null;if(a)b.i=a;else if(b.i)a=b.i;else throw Error("size must be specified.");if(b.v)return null;
var e=b.g+a-1,f=function(){const g=this;return n(function*(){var k=g.url,l=new Headers;10<=g.j&&(k=K(g.l),l.append("Zb-Url",g.url));g.l.D(l,g.o.A);l.append("Range","bytes="+g.g+"-"+e);try{var m=yield fetch(k,{method:"GET",headers:l,redirect:"follow"});if(g.v){if(g.v=0,g.i)return yield g.F()}else{g.i=0;g.j=10>g.j?1:11;if(200==m.status||206==m.status){2==g.m&&(g.m=1);var p=parseInt(m.headers.get("content-length"),10);if(p)g.g+=p;else{var q=m.headers.get("content-range");if(q){var r=q.indexOf("-");if(0>
r)var u=0;else{r++;var C=q.indexOf("/",r);u=C<=r?0:parseInt(q.slice(r,C),10)}}else u=0;g.g=u?u+1:e+1}200==m.status&&g.g<g.h()?g.g=g.h():g.g>g.h()&&(g.g=g.h());return yield m.arrayBuffer()}if(401==m.status&&1==g.m){console.log("Retry auth.");g.m=2;var D=yield g.l.u();if(D)console.error(D);else return g.o.A&&delete g.o.A,yield f()}else{var v=yield m.text();throw Error(v+" ("+m.status+")");}}}catch(H){if(0==g.j&&K(g.l))return g.j=10,yield f();if(1==g.j||11==g.j)return g.j++,yield ca(),yield f();throw H;
}})}.bind(b);return yield f()})}};Q("onedrive","Microsoft OneDrive",function(c,d){this.N(c,d);this.m=function(){return"onedrive"};this.i=function(a){const b=this;return n(function*(){return yield b.s(a)})};this.j=function(a){const b=this;return n(function*(){var e="/me/drive/items/".concat(a.B),f={};a.A&&(f.A=a.A);e=yield P(b,e.concat(y({select:"name,size,@microsoft.graph.downloadUrl"},!0)),f);f=null;e&&(e=JSON.parse(e),f={B:e["@microsoft.graph.downloadUrl"],M:e.name,K:e.size});return f})};this.l=function(){return"https://graph.microsoft.com/v1.0"};
this.s=function(a){const b=this;return n(function*(){var e=yield O(b,("/me/drive/items/"+a.U).concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),0,a);if(200==e.oa)return b.o(JSON.parse(e.ga));throw Error(JSON.stringify(e));})};this.o=function(a){var b={B:a.id,M:a.name,K:a.size,da:a.lastModifiedDateTime,va:a.parentReference.path,fa:a.parentReference.id,L:"0"};a.folder?b.L="1":a.file&&(b.L="2");return b}});Q("googledrive","Google Drive",function(c,d){this.N(c,d);this.m=function(){return"googledrive"};this.i=function(a){const b=this;return n(function*(){var e=b.s().concat(a.U);e=yield P(b,e.concat(y({fields:"id,name,mimeType,parents,modifiedTime,size"},!0)),a);return b.o(JSON.parse(e))})};this.j=function(a){const b=this;return n(function*(){var e=b.s().concat(a.B),f={U:a.B};a.A&&(f.A=a.A);if(f=yield b.i(f))f.B=b.l().concat(encodeURI(e)).concat(y({alt:"media"})),b.g.j&&(f.L="1");return f})};this.D=function(a,
b){b?a.append("Authorization",b):a.append("Authorization",this.h?this.h:"")};this.l=function(){return"https://www.googleapis.com"};this.s=function(){return"/drive/v3".concat("/files/")};this.o=function(a){var b={B:a.id,M:a.name,K:a.size,da:a.modifiedTime,L:"2"};a.parents&&0<a.parents.length&&(b.fa=a.parents[0]);this.F(a.mimeType)&&(b.L="1");return b};this.F=function(a){return"application/vnd.google-apps.folder"==a}});function ka(c,d){this.v=d;this.s=c;this.g=null;this.i=this.size=0;this.j="";this.o=this.l=0;this.m=1600;c.Y&&(this.m=c.Y);this.H=function(a){const b=this;return n(function*(){var e=yield b.v.j(b.s);if(e)b.size=e.K||0,e=yield b.v.I(b.s.B),b.g=e,b.g.sort(function(f,g){return f.ca-g.ca}),b.F(a);else throw Error("Failed to prepare reader.");})};this.$=function(){return this.m};this.u=function(){return this.i};this.h=function(){return this.size};this.G=function(){return this.g?this.l>=this.g.length:!0};
this.I=function(a){const b=this;return n(function*(){if(!b.j){var e=yield b.v.H(b.g[b.l].B);b.j=window.atob(A(e))}return yield b.R(a)})};this.D=function(){this.g=null;this.j=""};this.F=function(a){if(a){if(a>=this.h())throw Error("offset can not be bigger than input size.");this.i=a;var b=0;for(a=0;a<this.g.length&&!(b+=this.g[a].K,this.i<b);a++)this.o=b;if(a<this.g.length)this.l=a;else throw Error("offset can not be bigger than input size.");}else this.l=this.o=this.i=0;this.j=""};this.R=function(a){const b=
this;return n(function*(){var e=b.i-b.o,f=b.j.length-e;a?a<f&&(f=a):b.m<f&&(f=b.m);var g=B(b.j.substring(e,e+f));b.i+=f;b.j.length==e+f&&(b.j="",b.l++,b.o=b.i);return g.buffer})}}
Q("idxdb","Loacal Indexed DB",function(c,d){this.N(c,d);this.m=function(){return"idxdb"};this.u=function(){return new Promise(function(a){this.qa(a)})};this.i=function(a){const b=this;return n(function*(){var e=yield b.s(a.U);return e&&0<e.length?e[0]:null})};this.v=function(a){return new ka(a,this)};this.j=function(a){const b=this;return n(function*(){return yield b.i({U:a.B})})};this.l=function(){return""};this.saveData=function(a,b,e,f){const g=this;return n(function*(){yield g.o(function(k){k.put({key:a+
":"+b+"_"+e,data:f})})})};this.I=function(a){const b=this;return n(function*(){var e=[];yield b.o(function(f){f.getAllKeys().onsuccess=function(g){g.target.result.forEach(function(k){var l=k.indexOf(":");if(k.substring(0,l)==a){var m=k.substring(l+1);l=m.indexOf("_");e.push({B:k,ca:parseInt(m.substring(0,l),10),K:parseInt(m.substring(l+1),10)})}})}});return e})};this.H=function(a){const b=this;return n(function*(){var e="";yield b.o(function(f){f.get(a).onsuccess=function(g){e=g.target.result.data}});
return e})};this.qa=function(a){if(window.indexedDB){var b=window.indexedDB.open("zgalocaldb");b.onerror=function(){if(a)a("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");}.bind(this);b.onupgradeneeded=function(e){e=e.target.result;e.createObjectStore("items",{keyPath:"key"});e.createObjectStore("datas",{keyPath:"key"})}.bind(this);b.onsuccess=function(e){e.target.result.close();a&&a()}.bind(this)}else if(a)a("IndexedDB is not supported in your browser settings.");
else throw Error("IndexedDB is not supported in your browser settings.");};this.F=function(a){return new Promise(function(b){window.indexedDB.open("zgalocaldb").onsuccess=function(e){var f=e.target.result;e=f.transaction("items","readwrite");e.oncomplete=function(){f.close();b()}.bind(this);e=e.objectStore("items");a&&a(e)}.bind(this)})};this.o=function(a){return new Promise(function(b){window.indexedDB.open("zgalocaldb").onsuccess=function(e){var f=e.target.result;e=f.transaction("datas","readwrite");
e.oncomplete=function(){f.close();b()}.bind(this);e=e.objectStore("datas");a&&a(e)}.bind(this)}.bind(this))};this.s=function(a){const b=this;return n(function*(){var e=[];yield b.F(function(f){f.getAll().onsuccess=function(g){g.target.result.forEach(function(k){var l=!0;a&&(l=a==k.key);l&&e.push({B:k.key,M:k.name,K:k.size,da:k.tms,L:k.type,fa:k.pid})})}});return e})}});window=self;self.importScripts("vendor/forge.min.js");var R=null,S=null,T=null;function la(){return new Promise(function(c,d){var a=new ea;a.H(function(b){b?d(b):c(a)})})}function U(c,d){return n(function*(){var a=yield self.clients.get(c);a&&a.postMessage(d)})}
function ma(c){return n(function*(){var d="";try{var a={iv:window.atob(A(c.iv)),key:window.atob(A(c.key))};R||(R=yield la());var b=G[c.drvid];if(b){var e=new b.g(R,"https://zgayard.f5.si/grantauth.php");e.h=c.gtoken;S={ka:e,J:a,la:c.encfname,T:new Map}}else d="Drive's name is invalid."}catch(f){console.error(f),d=f.message||f}return d})}function na(c){return new Promise(function(d){T?d("A conflict has occurred."):(T=d,U(c,{action:1}))})}
function Y(c,d){return{status:c,statusText:(new Map([[200,"OK"],[206,"Partial Content"],[404,"Not Found"],[409,"Conflict"],[500,"Internal Server Error"],[503,"Service Unavailable"]])).get(c),headers:d}}function Z(c,d,a){a&&U(a,{action:2,msg:d});return new Response(d,Y(c))}
function oa(c,d){return n(function*(){if(!d)return Z(404,"Unkown url format.");var a=c.clientId||c.resultingClientId;if(!a)return Z(503,"Missing client id.");if(!S){var b=yield na(a);if(b)return Z(503,b,a)}try{var e=S.T.get(d);b=null;e?b=e.P:(b=new da({ja:!0,J:S.J,P:S.ka.v({B:d})}),e={ba:"",O:"",P:b},S.T.set(d,e));if(!(yield b.s()))return Z(409,"The reader will be disposed.");var f=c.request.headers.get("range"),g=0,k=-1;if(f&&"bytes="==f.substring(0,6)){f=f.substring(6);var l=f.indexOf(",");0<l&&
(f=f.substring(0,l));var m=f.split("-");0<m.length&&(g=parseInt(m[0],10),1<m.length&&m[1]&&(k=parseInt(m[1],10)+1))}var p=g;var q=k;var r=yield b.F();if(!e.O){e.O=b.C();if(S.la){f=e;var u=S.J,C=window.atob(A(e.O));l=u;"string"==typeof u&&(l=F(u));if(!(l&&l.iv&&l.key))throw Error("Need iv and key. They can be generated by computeEvpKDF from password and salt.");var D=forge.util.createBuffer(l.key);var v=forge.cipher.createDecipher("AES-CBC",D);v.start({iv:l.iv});v.update(forge.util.createBuffer(C));
v.finish();var H=v.output.getBytes();var E=forge.util.decodeUtf8(H);f.O=E}var V=e.O,W=V.lastIndexOf(".");E="";0<=W&&(E=V.slice(W+1));var L=E.toLowerCase();e.ba=ba[L]||aa[L]||t[L]||"binary/octet-stream"}q=Math.min(0>q?r:q,p+8E5);var z=yield b.G(p,q-p);b.I();var pa=p+z.length-1,w=new Headers;w.append("Content-Length",z.length.toString());w.append("Content-Type",e.ba);if(0==p&&z.length==r)return new Response(B(z),Y(200,w));w.append("Accept-Ranges","bytes");w.append("Content-Range",`bytes ${p}-${pa}/${r}`);
return new Response(B(z),Y(206,w))}catch(X){return Z(500,X.message||X,a)}})}self.addEventListener("message",function(c){return n(function*(){var d=c.source.id,a=c.data;switch(a.action){case 1:a=yield ma(a.cominf);T?(T(a),T=null):a&&(yield U(d,{action:2,msg:a}));break;case 3:if(d=a.fid,S&&d&&(a=S.T.get(d)))S.T.delete(d),(yield a.P.s(!0))&&a.P.H()}})});self.addEventListener("activate",function(c){c.waitUntil(self.clients.claim())});
self.addEventListener("fetch",function(c){var d=c.request.url,a=d.indexOf("/sw/");0>a||(d=d.substring(a+4),c.respondWith(oa(c,d)))});
