self.importScripts("vendor/crypto-js.js");function r(b){if(!b)return null;var c=b.charAt(0);if("?"==c||"#"==c)b=b.substring(1);var a={};b.split("&").forEach(function(d){var f=d.indexOf("=");0>f?a[decodeURIComponent(d)]="":a[decodeURIComponent(d.substring(0,f))]=decodeURIComponent(d.substring(f+1))});return a}function t(){var b=r(window.location.search),c=r(window.location.hash);c&&(b=b?Object.assign(b,c):c);return b}
function v(b,c){var a=[],d;for(d in b)c?a.push(d.concat("=").concat(b[d])):a.push(encodeURIComponent(d).concat("=").concat(encodeURIComponent(b[d])));return 0<a.length?"?".concat(a.join("&")):""}function w(b){if(!b)return 0;var c=b.indexOf("-");if(0>c)return 0;c++;var a=b.indexOf("/",c);return a<=c?0:parseInt(b.slice(c,a),10)};function x(b){var c=CryptoJS.MD5(b);b=CryptoJS.kdf.OpenSSL.execute(b,8,4,c);b.iv.clamp();b.key.clamp();return b}function y(b){var c=Array(b.sigBytes);b=b.words;for(var a=0,d=0;d<b.length;d++){for(var f=b[d],e=a+4-1;e>=a;e--)e<c.length&&(c[e]=f&255),f>>=8;a+=4;if(a>=c.length)break}return c}
function z(){this.h=0;this.g=null;this.u=function(b,c){this.h=b;c&&c()};this.write=function(b,c){Array.isArray(b)?this.g=this.g?this.g.concat(b):b.concat():(this.g||(this.g=[]),this.g.push(b));c&&c()};this.cancel=function(b){b&&b(!1,!0)};this.i=function(){if(this.g&&0<this.g.length&&(this.g[0]instanceof ArrayBuffer||this.g[0]instanceof Uint8Array)){for(var b=0,c=0;c<this.g.length;c++)b+=this.g[c].byteLength;b=new Uint8Array(b);var a=0;for(c=0;c<this.g.length;++c){var d=this.g[c];d instanceof ArrayBuffer&&
(d=new Uint8Array(d));b.set(d,a);a+=d.byteLength}return b}return this.g};this.o=function(){var b=this.i();b instanceof Uint8Array||(b=new Uint8Array(b));return new Blob([b],{type:"application/octet-binary"})};this.download=function(b){var c=this.o();if(window.navigator.msSaveBlob)window.navigator.msSaveBlob(c,b);else throw Error("Element for download is not specified.");};this.A=function(){return this.h}}
function A(b){this.j=null;if(b._blob)if(b._blob instanceof Blob)this.j=b._blob;else throw Error("blob is not a Blob.");else throw Error("blob must be specified.");this.u=1600;b.M&&(this.u=b.M);this.g=0;this.o=this.i=null;this.I=function(c,a){if(c){if(c>=this.h())throw Error("offset can not be bigger than input size.");this.g=c}this.i=new FileReader;this.i.onload=function(d){d=d.target.result;this.o&&this.o(d,this)}.bind(this);a&&a()};this.s=function(){return this.g};this.h=function(){return this.j.size};
this.C=function(){return this.g>=this.h()};this.l=function(c){if(1!=this.i.readyState){var a=this.g;this.g=c?this.g+c:this.g+this.u;this.i.readAsArrayBuffer(this.j.slice(a,this.g))}};this.ba=function(){this.j=this.i=null}}
function B(b){if(!b.fa)if(this.getSuperClass&&"Readable"==this.getSuperClass().name)this.super(void 0),this.h=1;else throw Error("writer must be specified in no stream mode.");this.s=this.B=null;this.u=!0;this.g=null;this.l=b.fa;this.iv=this.key=null;this.i=0;this.o=null;this.A=this.j=0;this.speed="0B/s";b.ha&&(this.u=!1);if(b.ea)this.g=b.ea;else throw Error("reader must be specified.");if(b.U){var c=null;c="string"==typeof b.U?x(b.U):b.U;this.key=c.key;this.iv=c.iv}else throw Error("keycfg must be specified.");
this.start=function(a){if(a){if(this.u)throw Error("Can NOT set offset for encryption.");this.i=a;a-=a%16+16;0>a&&(a=0)}this.g.o=this.D.bind(this);this.g.I(a,function(){var d=16*Math.ceil((this.g.h()+1)/16);this.h||!this.l?this.C():this.l.u(d,this.C.bind(this))}.bind(this))};this.I=function(){if(Date.now()>this.j){var a=1E3*(this.g.s()-this.A)/(Date.now()-this.j+1E3);if(a)if(1024>a)var d="B";else 1048576>a?(d="KB",a=Math.round(a/102.4)/10):1073741824>a?(d="MB",a=Math.round(a/104857.6)/10):(d="GB",
a=Math.round(a/1.073741824E8)/10);else d="B",a=0;var f=a.toString();a=f.indexOf(".");var e=f.split(""),h=[];0<=a?h.push(f.slice(a)):a=e.length;for(f=0;0<a;)3==f++&&(h.unshift(","),f=1),h.unshift(e[--a]);this.speed=h.join("").concat(d)+"/s";this.j=Date.now()+1E3;this.A=this.g.s()}return this.speed};this._read=function(a){1==this.h?this.h=2:3==this.h&&(this.g.C()?this.push(null):this.g.l(a))};this.push=function(a){return this.readable?(a&&!this.L?this.superCall("push",new Uint8Array(a)):this.superCall("push",
a),!0):!1};this.C=function(){this.j=Date.now()+1E3;(this.A=this.i)?this.g.l(16):1==this.h?this.h=3:2==this.h?(this.h=3,this.push([])):this.g.l()};this.D=function(a){try{var d=new CryptoJS.lib.WordArray.init(a);if(!this.o){var f={iv:this.iv,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7};this.i&&(f.iv=d,d=null);this.o=this.u?CryptoJS.algo.AES.createEncryptor(this.key,f):CryptoJS.algo.AES.createDecryptor(this.key,f)}if(d){var e=y(this.o.process(d));this.g.C()&&(e=e.concat(y(this.o.finalize())));
if(this.i<this.g.s()){var h=this.i-(this.g.s()-a.byteLength);0<h&&(e=e.slice(h))}else e=null;this.h?this.push(e):e?this.l&&this.l.write(e,function(){this.g.C()?this.$():this.B?this.B()?this.g.l():this.l.cancel(function(k,l){this.$(k,l)}.bind(this)):this.g.l()}.bind(this)):this.g.l();e=null}else this.h?2==this.h?(this.h=3,this.push([])):this.h=3:this.g.l()}catch(k){if(this.h)throw k;this.$(k)}};this.$=function(a,d){this.g&&(this.g.ba(),this.g=null);this.s&&(a?this.s(a):this.s(!1,d))}};function C(){this.h=!0;this.g=null;this.l=!1;this.B=function(){var b=null;if(this.h)try{b=window.sessionStorage.getItem("login_state")}catch(c){this.h=!1,console.error(c)}return b};this.o=function(b){var c=this.B();return c&&b==c?!0:!1};this.i=function(b,c){if(this.h)try{return window.sessionStorage.setItem(b,c.toString()),!0}catch(a){this.h=!1,console.error(a)}return!1};this.s=function(){if(this.h)try{window.sessionStorage.removeItem("login_state")}catch(b){this.h=!1,console.error(b)}};this.u=function(){var b=
this.j("relay_url");return b?b:""};this.C=function(b){if(window.indexedDB){var c=window.indexedDB.open("zgayard1946");c.onerror=function(){if(b)b("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");};c.onupgradeneeded=function(a){a.target.result.createObjectStore("settings",{keyPath:"key"})};c.onsuccess=function(a){var d=a.target.result;a=d.transaction("settings","readwrite");a.oncomplete=function(){d.close();b&&b()};a.objectStore("settings").getAll().onsuccess=
function(f){this.g={};f.target.result.forEach(function(e){this.g[e.key]=e.value}.bind(this));this.l=(f=this.g.drive)&&this.g[f]&&this.g[f].refresh_token?!0:!1}.bind(this)}.bind(this)}else if(b)b("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");};this.A=function(){var b=this.j("drive");return b&&(b=this.g[b])?b.refresh_token:null};this.D=function(b){if(this.g){var c=this.j("drive");b?(this.g[c]||(this.g[c]={}),this.g[c].refresh_token=
b):this.g[c]&&delete this.g[c].refresh_token}};this.j=function(b){return this.g&&this.g[b]?this.g[b]:null}};var D={};function E(b,c,a){this.F=b;this.O=c;this.g=a}function F(b,c){this.o=null;this.L=c;this.h=null;this.g=b;this.super||(this.super=function(){})}function G(b){null==b.o&&(b.o=b.g.u());return b.o}
function H(b,c){var a="POST",d=b.l().concat(encodeURI(c.H)),f=new XMLHttpRequest;c&&c.V&&(a=c.V);f.open(a,d,!0);c&&c.v?f.setRequestHeader("Authorization",c.v):c&&c.X?(a="Bearer",c&&c.Y&&(a=c.Y),f.setRequestHeader("Authorization",a+" "+c.X)):f.setRequestHeader("Authorization",b.h);if(c&&c.T)for(var e in c.T)f.setRequestHeader(e,c.T[e]);c&&c.m&&(f.onload=function(h){h=h.target;4==h.readyState&&(401==h.status&&this.g.l&&!c.ka?I(this,c):c.m(h))}.bind(b));f.send(c.da)}
function J(b,c){var a=b.g.l,d={},f=t();if(f&&f.token_type&&f.access_token){K(b,f.token_type,f.access_token);if(f&&f.state)if(b.g.o(f.state))b.g.s();else{c("Unauthorized access to this url.");return}c()}else if(f&&f.code?d.code=f.code:a&&(d.aa=b.g.A()),d.code||d.aa){if(f&&f.state)if(b.g.o(f.state))b.g.s();else{c("Unauthorized access to this url.");return}L(b,d,function(e){e&&e.token_type&&e.access_token?(K(this,e.token_type,e.access_token),a&&d.code&&e.refresh_token&&this.g.D(e.refresh_token),e.logout&&
this.g.i("logout_url",e.logout),c()):e&&e.error?c("["+e.error+"] "+e.error_description):c("Unknown error occured when doing authorization.")}.bind(b))}else a&&(d.ga=!0),L(b,d,function(e){e&&e.url?(e.state&&(this.g.i("login_state",e.state)||(e.state=this.j())),e.logout&&this.g.i("logout_url",e.logout),window.location.href=e.url.concat("&state=".concat(encodeURIComponent(e.state)))):e&&e.error?c("["+e.error+"] "+e.error_description):c("Unknown error occured when doing authorization.")}.bind(b))}
F.prototype.u=function(b,c){c&&c(!1)};F.prototype.I=function(){};function M(b){return{G:b.status,P:b.responseText}}function N(b,c,a,d,f){c={H:c,V:"GET",m:function(e){var h=M(e),k=!1;a&&e.status!=a&&(k=!0);if(k)if(d&&d.m)d.m(h);else throw Error(JSON.stringify(h));else f(h)}.bind(b)};O(d,c);H(b,c)}function P(b,c,a,d){N(b,c,200,a,function(f){d(f.P)})}function O(b,c){b.Y&&(c.Y=b.Y);b.X&&(c.X=b.X);b.v&&(c.v=b.v)}function K(b,c,a){b.h=c+" "+a;b.g.i("access_token",b.h)}
function L(b,c,a){if(!c)throw Error("Options are not specified when auth onedrive.");var d=new FormData;d.append("drive_type",b.j());c.clientId&&d.append("client_id",c.clientId);c.ma&&d.append("redirect_uri",c.ma);c.la&&d.append("client_secret",c.la);c.code?d.append("code",c.code):c.aa?d.append("refresh_token",c.aa):c.ga&&d.append("need_code",c.ga);c=new XMLHttpRequest;c.open("POST",b.L,!0);c.withCredentials=!0;c.onload=function(f){f=f.target;if(4==f.readyState)if(200==f.status)a&&a(JSON.parse(f.responseText));
else throw Error(f.responseText+" ("+f.status+")");};c.send(d)}function I(b,c){console.log("Retry to send ajax.");c&&(c.ka=!0,J(b,function(a){a?console.error(a):(c.v=this.h,H(this,c))}.bind(b)))}
function Q(b){b.Z=F;if("function"===typeof Object.create)b.prototype=Object.create(F.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});else{var c=function(){};c.prototype=F.prototype;b.prototype=new c;b.prototype.constructor=b}b.prototype.getSuperClass||(b.prototype.getSuperClass=function(){return this.constructor.Z});b.prototype.super||(b.prototype.super=function(...a){return this.constructor.Z.call(this,...a)});b.prototype.superCall||(b.prototype.superCall=function(a,
...d){return a?this.constructor.Z.prototype[a].call(this,...d):this.constructor.Z.call(this,...d)})}
function R(b,c){this.l=c;this.j=b;this.s="";this.g=this.i=0;this.h=null;if(!this.j||!this.j.N)throw Error("fnm is not specified.");this.u=function(a,d){this.i=a;this.l.C(this.j,a,function(f,e){if(f)this.s=f,d&&d(e);else throw console.error(e),Error(JSON.stringify(e));}.bind(this))};this.write=function(a,d){var f=null;if(this.h){if(this.h instanceof ArrayBuffer){var e=this.h.byteLength;0<e?(f=new Uint8Array(e+a.byteLength),f.set(new Uint8Array(this.h),0),f.set(new Uint8Array(a),e)):f=new Uint8Array(a)}else f=
0<this.h.length?new Uint8Array(this.h.concat(a)):new Uint8Array(a);this.h=null}else f=new Uint8Array(a);var h=new Blob([f],{type:"application/octet-binary"}),k="bytes "+this.g+"-";this.g+=h.size;k+=this.g-1+"/"+this.i;var l=0,u=function(){var q=new XMLHttpRequest;q.open("PUT",this.s,!0);q.setRequestHeader("Content-Range",k);q.onload=function(m){h=null;m=m.target;if(4==m.readyState){var n=this.l.A(m);if(-9==n)throw a=null,Error(m.responseText+" ("+m.status+")");if(-1!=n&&0!=n&&n<this.g){var p=a instanceof
ArrayBuffer?a.byteLength:a.length;p-=this.g-n;if(0<p){p=a.slice(p);a=null;if(this.g>=this.i){this.write(p,d);return}this.h=p;this.g=n}else throw a=null,Error("Can NOT continue to upload buffer.");}d&&d(m.responseText)}}.bind(this);q.onerror=function(){1>l?(l++,setTimeout(function(){u()},500)):h=a=null};q.send(h)}.bind(this);u()};this.cancel=function(a){this.l.u(this.s,a)};this.A=function(){return this.i}}
function S(b,c){this.u=c;this.B=b;this.url="";this.name=null;this.D=this.i=this.g=this.size=0;this.ca=!1;this.S=16E3;b.M&&(this.S=b.M);this.A=this.j=0;this.o=null;this.I=function(a,d){if(this.ca){this.i&&(this.D=this.i,this.i=0);if(a){if(a>=this.h())throw console.log("offset:"+a+",size:"+this.h()),Error("offset can not be bigger than input size.");this.g=a}else this.g=0;d&&d()}else this.u.B(this.B,function(f,e){this.ca=!0;if(f){this.size=f._size;this.url=f.F;this.name=f.O;this.A="1"==f._type?1:0;
if(a){if(a>=this.h())throw Error("offset can not be bigger than input size.");this.g=a}d&&d()}else throw Error(e.P+" ("+e.G+")");}.bind(this))};this.s=function(){return this.g};this.h=function(){return this.size};this.C=function(){return this.g>=this.h()};this.l=function(a){a||(a=this.S);this.L(a)};this.ba=function(){};this.L=function(a){if(!a||!this.i){if(a)this.i=a;else if(this.i)a=this.i;else throw Error("size must be specified.");if(!this.D){var d=this.g+a-1,f=function(){var e=new XMLHttpRequest;
10<=this.j?(e.open("GET",G(this.u),!0),e.setRequestHeader("Zb-Url",this.url)):e.open("GET",this.url,!0);this.u.I(e,this.B.v);e.setRequestHeader("Range","bytes="+this.g+"-"+d);e.responseType="arraybuffer";e.onload=function(h){if(this.D)this.D=0,this.i&&this.L();else if(this.i=0,h=h.target,4==h.readyState)if(this.j=10>this.j?1:11,200==h.status||206==h.status){2==this.A&&(this.A=1);var k=parseInt(h.getResponseHeader("content-length"),10);k?this.g+=k:this.g=(k=w(h.getResponseHeader("content-range")))?
k+1:d+1;200==h.status&&this.g<this.h()?this.g=this.h():this.g>this.h()&&(this.g=this.h());this.o&&this.o(h.response,this);h.response=null}else if(401==h.status&&1==this.A)console.log("Retry auth."),this.A=2,J(this.u,function(l){l?console.error(l):(this.B.v&&delete this.B.v,f())}.bind(this));else throw Error(h.responseText+" ("+h.status+")");}.bind(this);e.onerror=function(){if(0==this.j&&G(this.u))this.j=10,f();else if(1==this.j||11==this.j)this.j++,setTimeout(function(){f()},500)}.bind(this);e.send()}.bind(this);
f()}}}};function T(b,c){this.super(b,c);this.j=function(){return"onedrive"};this.D=function(a){var d="/me/drive/root/children";if(a){if(a._fname){var f=function(e){var h={W:"",m:function(k,l){if(a&&a.m)k?a.m(k):(k=[],l&&k.push(l),a.m(!1,k));else if(k)throw Error(JSON.stringify(k));}};O(a,h);this.i(h,e)}.bind(this);a.K?(d={W:a.K,m:function(e,h){if(e)if(a&&a.m)a.m(e);else throw Error(JSON.stringify(e));else f(h.ja.concat("/").concat(h.O).concat("/").concat(a._fname))}},O(a,d),this.i(d)):f("/drive/root:/".concat(a._fname));
return}a.K&&(d="/me/drive/items/"+a.K+"/children")}P(this,d.concat(v({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),a,function(e){if(a&&a.m){var h=[];e&&JSON.parse(e).value.forEach(function(k){h.push(this.R(k))},this);a.m(!1,h)}}.bind(this))};this.s=function(a){this.i(a)};this.C=function(a,d,f){d={H:"/me",V:"POST",v:a.v,T:{"Content-Type":"application/json;charset=UTF-8","Cache-Control":"no-cache",Pragma:"no-cache"},m:function(e){e=M(e);var h="";200<=e.G&&299>=e.G&&(h=
JSON.parse(e.P).uploadUrl);f(h,e)}.bind(this)};d.H=a.J?"/me/drive/items/"+a.J+":/":d.H+"/drive/root:/";d.H+=a.N;d.H+=":/createUploadSession";d.da=JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"replace",name:a.N}});H(this,d)};this.A=function(a){if(0<=[200,201].indexOf(a.status))return-1;if(0>[202].indexOf(a.status))return-9;if((a=JSON.parse(a.responseText).nextExpectedRanges)&&a.length){var d=a[0].indexOf("-");if(0<d)return parseInt(a[0].substring(0,d),10)}return 0};this.u=function(a,d){var f=
new XMLHttpRequest;f.open("DELETE",a,!0);f.onload=function(e){e=e.target;if(4==e.readyState){var h={G:e.status,P:e.responseText};200<=e.status&&299>=e.status?d&&d(!1,h):(console.log(e.responseText+" ("+e.status+")"),d&&d(h))}}.bind(this);f.send()};this.B=function(a,d){var f="/me/drive/items/".concat(a.F),e={m:function(h,k){var l=null;k&&!h&&(k=JSON.parse(k),l={F:k["@microsoft.graph.downloadUrl"],O:k.name,_size:k.size});d(l,h)}};a.v&&(e.v=a.v);P(this,f.concat(v({select:"name,size,@microsoft.graph.downloadUrl"},
!0)),e,function(h){e.m(!1,h)})};this.l=function(){return"https://graph.microsoft.com/v1.0"};this.i=function(a,d){var f="";f=d?d.startsWith("/me")?d:"/me".concat(d):"/me/drive/items/"+a.W;N(this,f.concat(v({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),0,a,function(e){if(a&&a.m)200==e.G?(e=this.R(JSON.parse(e.P)),a.m(!1,e)):404==e.G&&d?a.m(!1):a.m(e);else if(200!=e.G)throw Error(JSON.stringify(e));}.bind(this))};this.R=function(a){var d={F:a.id,O:a.name,_size:a.size,
ia:a.lastModifiedDateTime,ja:a.parentReference.path,_parentId:a.parentReference.id,_type:"0"};a.folder?d._type="1":a.file&&(d._type="2");return d}}Q(T);D.onedrive=new E("onedrive","Microsoft OneDrive",T);function U(b,c){this.super(b,c);this.j=function(){return"googledrive"};this.D=function(a){var d=this.i("/files"),f="'"+(a.K?a.K:"root")+"' in parents";a._fname&&(f=f.concat(" and name = '"+a._fname+"'"));P(this,d.concat(v({fields:"files(id,name,mimeType,parents,modifiedTime,size)",q:f},!0)),a,function(e){if(a&&a.m){var h=[];JSON.parse(e).files.forEach(function(k){h.push(this.R(k))},this);a.m(!1,h)}}.bind(this))};this.s=function(a){var d=this.i("/files/").concat(a.W);P(this,d.concat(v({fields:"id,name,mimeType,parents,modifiedTime,size"},
!0)),a,function(f){a&&a.m&&(f=this.R(JSON.parse(f)),a.m(!1,f))}.bind(this))};this.C=function(a,d,f){var e=function(k){var l={},u="POST",q="/files?uploadType=resumable";k?(u="PATCH",q="/files/"+k+"?uploadType=resumable"):(l.name=a.N,a.J&&(l.parents=[a.J]));k={H:"/upload".concat(this.i(q)),V:u,v:a.v,T:{"X-Upload-Content-Length":d,"X-Upload-Content-Type":"application/octet-stream","Content-Type":"application/json; charset=UTF-8"},da:JSON.stringify(l),m:function(m){var n=M(m),p="";200<=n.G&&299>=n.G&&
(p=m.getResponseHeader("location"));f(p,n)}.bind(this)};H(this,k)}.bind(this),h={m:function(k,l){k?f("",k):0<l.length?e(l[0].F):e()},_fname:a.N,v:a.v};a.J&&(h.K=a.J);this.D(h)};this.A=function(a){if(0<=[200,201].indexOf(a.status))return-1;if(0>[308].indexOf(a.status))return-9;if(a=a.getResponseHeader("range")){var d=a.indexOf("-");if(0<d)return parseInt(a.slice(d+1),10)+1}return 0};this.B=function(a,d){var f=this.i("/files/").concat(a.F),e={W:a.F,m:function(h,k){var l=null;k&&!h&&(l=k,l.F=this.l().concat(encodeURI(f)).concat(v({alt:"media"})),
this.g.l&&(l._type="1"));d(l,h)}.bind(this)};a.v&&(e.v=a.v);this.s(e)};this.I=function(a,d){d?a.setRequestHeader("Authorization",d):a.setRequestHeader("Authorization",this.h?this.h:"")};this.l=function(){return"https://www.googleapis.com"};this.i=function(a){return"/drive/v3".concat(a)};this.R=function(a){var d={F:a.id,O:a.name,_size:a.size,ia:a.modifiedTime,_type:"2"};a.parents&&0<a.parents.length&&(d._parentId=a.parents[0]);this.S(a.mimeType)&&(d._type="1");return d};this.S=function(a){return"application/vnd.google-apps.folder"==
a}}Q(U);D.googledrive=new E("googledrive","Google Drive",U);function V(b,c,a){this.g=this.h=null;this.u=b;this.i=1;this.s=c;this.l=a;this.j=function(){var d=new B({ha:1==this.i,U:this.u,ea:this.h,fa:this.g});d.B=function(){var f={_type:1,_wtype:this.i,_speed:d.I(),_pos:this.h.s(),_size:this.h.h()};this.l(f);return this.s()?!1:!0}.bind(this);d.s=function(f,e){var h={_type:2,_wtype:this.i,_size:this.g.A()};f?h._err=f.message||f.na:e?h._type=3:this.g.o&&(h._blob=this.g.o());this.l(h)}.bind(this);d.start()};this.o=function(d,f){this.i=1;this.h=new S({F:f,M:16E5},
d);this.g=new z;this.j()};this.A=function(d,f,e,h){this.i=2;this.h=new A({_blob:e,M:16E5});this.g=new R({N:f,J:h},d);this.j()}};window=self;self.g=!1;function W(b,c){return new V(b,function(){return self.g},function(a){2==a._type&&(a._token=c.h?c.h:"");self.postMessage(a)})}
function X(b){var c=b._type,a=b._cominf,d={iv:CryptoJS.enc.Base64url.parse(a._iv),key:CryptoJS.enc.Base64url.parse(a._key)};self.postMessage({_type:0,_wtype:c,_size:0});var f=new C;f.C(function(e){e&&console.error("IndexedDB is not supported in your browser settings.");if(e=D[a._drvnm])switch(e=new e.g(f,"https://zgayard.f5.si/grantauth.php"),e.h=a._token,c){case 1:W(d,e).o(e,b._downinf._targetId);break;case 2:var h=b._upinf;W(d,e).A(e,h._fname,h._file,h._parentId)}else self.postMessage({_type:2,
_wtype:c,_size:0,_err:"Drive's name is invalid."})})}self.addEventListener("message",function(b){b=b.data;switch(b._type){case 1:case 2:X(b);break;default:self.g=!0}});
