var k;function t(c){function e(b){return c.next(b)}function a(b){return c.throw(b)}return new Promise(function(b,d){function f(h){h.done?b(h.value):Promise.resolve(h.value).then(e,a).then(f,d)}f(c.next())})}function v(c){return t(c())}self.importScripts("vendor/crypto-js.js");function x(c){if(!c)return null;var e=c.charAt(0);if("?"==e||"#"==e)c=c.substring(1);var a={};c.split("&").forEach(function(b){var d=b.indexOf("=");0>d?a[decodeURIComponent(b)]="":a[decodeURIComponent(b.substring(0,d))]=decodeURIComponent(b.substring(d+1))});return a}function y(c,e){var a=[],b;for(b in c)e?a.push(b.concat("=").concat(c[b])):a.push(encodeURIComponent(b).concat("=").concat(encodeURIComponent(c[b])));return 0<a.length?"?".concat(a.join("&")):""}
function z(){return new Promise(function(c){setTimeout(c,500)})};function A(c){var e=CryptoJS.MD5(c);c=CryptoJS.kdf.OpenSSL.execute(c,8,4,e);c.iv.clamp();c.key.clamp();return c}function B(c){var e=Array(c.sigBytes);c=c.words;for(var a=0,b=0;b<c.length;b++){for(var d=c[b],f=a+4-1;f>=a;f--)f<e.length&&(e[f]=d&255),d>>=8;a+=4;if(a>=e.length)break}return e}
function D(){this.h=0;this.g=null;this.l=function(c){const e=this;return v(function*(){e.h=c})};this.write=function(c){const e=this;return v(function*(){Array.isArray(c)?e.g=e.g?e.g.concat(c):c.concat():(e.g||(e.g=[]),e.g.push(c));c=null})};this.cancel=function(){return v(function*(){})};this.i=function(){if(this.g&&0<this.g.length&&(this.g[0]instanceof ArrayBuffer||this.g[0]instanceof Uint8Array)){for(var c=0,e=0;e<this.g.length;e++)c+=this.g[e].byteLength;c=new Uint8Array(c);var a=0;for(e=0;e<this.g.length;++e){var b=
this.g[e];b instanceof ArrayBuffer&&(b=new Uint8Array(b));c.set(b,a);a+=b.byteLength}return c}return this.g};this.o=function(){var c=this.i();c instanceof Uint8Array||(c=new Uint8Array(c));return new Blob([c],{type:"application/octet-binary"})};this.download=function(c){var e=this.o();if(window.navigator.msSaveBlob)window.navigator.msSaveBlob(e,c);else throw Error("Element for download is not specified.");};this.v=function(){return this.h}}
function E(c){this.blob=null;if(c.ma)if(c.ma instanceof Blob)this.blob=c.ma;else throw Error("blob is not a Blob.");else throw Error("blob must be specified.");this.j=1600;c.N&&(this.j=c.N);this.h=0;this.i=null;this.J=function(e){const a=this;return v(function*(){if(e){if(e>=a.g())throw Error("offset can not be bigger than input size.");a.h=e}else a.h=0;a.i=new FileReader})};this.U=function(){return this.j};this.l=function(){return this.h};this.g=function(){return this.blob.size};this.v=function(){return this.h>=
this.g()};this.K=function(e){return new Promise(function(a){if(1!=this.i.readyState){this.i.onload=function(d){a(d.target.result)}.bind(this);var b=this.h;this.h=e?this.h+e:this.h+this.j;this.i.readAsArrayBuffer(this.blob.slice(b,this.h))}}.bind(this))};this.F=function(){this.blob=this.i=null}}
function F(c){this.m=!0;this.g=c.Ea;this.h=this.j=this.iv=this.key=null;this.l=this.i=0;c.Ca&&(this.m=!1);if(!this.g)throw Error("reader must be specified.");if(c.da){var e=null;e="string"==typeof c.da?A(c.da):c.da;this.key=e.key;this.iv=e.iv}else throw Error("keycfg must be specified.");this.K=function(){const a=this;return v(function*(){if(a.l)return a.l;if(a.m)return a.l=16*Math.ceil((a.g.g()+1)/16),a.l;0==a.g.g()&&(yield a.o());var b=a.g.g()-16,d=yield a.F(b);a.l=b+d.length;return a.l})};this.o=
function(a){const b=this;return v(function*(){var d=a||0;if(a){if(b.m)throw Error("Can NOT set offset for encryption.");a-=a%16+16;0>a&&(a=0)}yield b.g.J(a);var f={iv:b.iv,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7};d&&(f.iv=yield b.v(16));b.j=b.m?CryptoJS.algo.AES.createEncryptor(b.key,f):CryptoJS.algo.AES.createDecryptor(b.key,f);b.i=d;b.h=null})};this.F=function(a){const b=this;return v(function*(){var d=b.g.U(),f=null,h=0<=a?a:b.g.l();if(b.i==h&&b.h){if(d<=b.h.length)return b.i+=d,f=b.h.slice(0,
d),b.h=b.h.slice(d),0==b.h.length&&(b.h=null),f;f=b.h;h+=b.h.length;b.i+=b.h.length;d-=b.h.length}var m=16*Math.ceil((h%16+d)/16);b.j&&b.i==h||(yield b.o(h),m+=16);var l=yield b.v(m);m=B(b.j.process(l));b.g.v()&&(m=m.concat(B(b.j.finalize())));h<b.g.l()?(h-=b.g.l()-l.sigBytes,0<h&&(m=m.slice(h)),m.length>d&&(b.h=m.slice(d),m=m.slice(0,d)),b.i+=d):m=null;f?m&&(f=f.concat(m)):m&&(f=m);return f})};this.u=function(){return this.g.l()};this.B=function(){return this.g.v()};this.J=function(){this.g.F();
this.j=this.g=null};this.v=function(a){const b=this;return v(function*(){var d=yield b.g.K(a);return new CryptoJS.lib.WordArray.init(d)})}}
function G(c){this.g=new F(c);this.h=c.Ga;this.speed=this.l=this.i=0;if(!this.h)throw Error("writer must be specified.");this.start=function(e,a){const b=this;return v(function*(){var d=e||0,f=yield b.g.K();yield b.h.l(f);yield b.g.o(e);b.i=Date.now()+1E3;b.l=d;for(d=b.g.B()?2:0;0==d;)(f=yield b.g.F())&&(yield b.h.write(f)),b.g.B()?d=2:a&&!a()&&(d=1);1==d&&(yield b.h.cancel());b.h=null;b.g.J();b.g=null;return 2==d})};this.j=function(){Date.now()>this.i&&(this.speed=1E3*(this.g.u()-this.l)/(Date.now()-
this.i+1E3),this.i=Date.now()+1E3,this.l=this.g.u());return this.speed}};function H(){this.h=!0;this.g=null;this.l=!1;this.K=function(){var c=null;if(this.h)try{c=window.sessionStorage.getItem("login_state")}catch(e){this.h=!1,console.error(e)}return c};this.v=function(c){var e=this.K();return e&&c==e?!0:!1};this.i=function(c,e){if(this.h)try{return window.sessionStorage.setItem(c,e.toString()),!0}catch(a){this.h=!1,console.error(a)}return!1};this.m=function(c){if(this.h)try{window.sessionStorage.removeItem(c)}catch(e){this.h=!1,console.error(e)}};this.F=function(){var c=
this.j("relay_url");return c?c:""};this.J=function(){var c=null,e=this.u("extra_info");e&&(c=JSON.parse(e));return c&&2==c.length?{ua:c[0],ca:c[1]}:null};this.B=function(c){c?(c="string"===typeof c?c:JSON.stringify([c.ua,c.ca]),this.i("drive_extra",c),this.o("extra_info",c)):(this.m("drive_extra"),this.o("extra_info",null))};this.G=function(c){if(window.indexedDB){var e=window.indexedDB.open("zgayard1946");e.onerror=function(){if(c)c("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");
};e.onupgradeneeded=function(a){a.target.result.createObjectStore("settings",{keyPath:"key"})};e.onsuccess=function(a){var b=a.target.result;a=b.transaction("settings","readwrite");a.oncomplete=function(){b.close();c&&c()};a.objectStore("settings").getAll().onsuccess=function(d){this.g={};d.target.result.forEach(function(f){this.g[f.key]=f.value}.bind(this));this.l=(d=this.g.drive)&&this.g[d]&&this.g[d].refresh_token?!0:!1}.bind(this)}.bind(this)}else if(c)c("IndexedDB is not supported in your browser settings.");
else throw Error("IndexedDB is not supported in your browser settings.");};this.u=function(c){var e=this.j("drive");return e&&(e=this.g[e])?e[c]:null};this.o=function(c,e){if(this.g){var a=this.j("drive");e?(this.g[a]||(this.g[a]={}),this.g[a][c]=e):this.g[a]&&this.g[a][c]&&delete this.g[a][c]}};this.U=function(c,e){window.indexedDB.open("zgayard1946").onsuccess=function(a){var b=a.target.result;a=b.transaction("settings","readwrite");a.oncomplete=function(){b.close();e&&e()};a=a.objectStore("settings");
c&&c(a)}};this.j=function(c){return this.g&&this.g[c]?this.g[c]:null};this.saveData=function(c,e,a){this.g&&(this.g[c]=e);this.U(function(b){b.put({key:c,value:e})}.bind(this),a)}};var I={};function J(c,e,a){this.s=c;this.I=e;this.g=a}function K(c,e){this.o=null;this.u=e;this.h=null;this.g=c;this.T||(this.T=function(){})}function L(c){null==c.o&&(c.o=c.g.F());return c.o}
function M(c,e){return v(function*(){var a="POST",b=c.l().concat(encodeURI(e.L)),d=new Headers;if(e&&e.A)d.append("Authorization",e.A);else if(e&&e.ha){var f="Bearer";e&&e.ia&&(f=e.ia);d.append("Authorization",f+" "+e.ha)}else d.append("Authorization",c.h);if(e&&e.oa)for(var h of e.oa.entries())d.append(h[0],h[1]);e&&e.fa&&(a=e.fa);a=yield fetch(b,{method:a,body:e.va,headers:d,redirect:"follow"});401==a.status&&c.g.l&&!e.Fa&&(a=yield N(c,e));return a})}k=K.prototype;
k.qa=function(){const c=this;return v(function*(){var e=c.g.l,a={},b,d=x(window.location.search);(b=x(window.location.hash))&&(d=d?Object.assign(d,b):b);if((b=d)&&b.token_type&&b.access_token){c.h=b.token_type+" "+b.access_token;c.g.i("access_token",c.h);if(b&&b.state)if(c.g.v(b.state))c.g.m("login_state");else return"Unauthorized access to this url.";return null}b&&b.code?a.code=b.code:e&&(a.ra=c.g.u("refresh_token"));if(d=c.g.J())a.clientId=d.ua,a.ya=d.ca;if(a.code||a.ra){if(b&&b.state)if(c.g.v(b.state))c.g.m("login_state");
else return"Unauthorized access to this url.";if((b=yield O(c,a))&&b.token_type&&b.access_token)return d&&b.client_secret_enc&&(d.ca=b.client_secret_enc,c.g.B(d)),c.h=b.token_type+" "+b.access_token,c.g.i("access_token",c.h),e&&a.code&&b.refresh_token&&c.g.o("refresh_token",b.refresh_token),b.logout&&c.g.i("logout_url",b.logout),null}else if(e&&(a.Aa=!0),(b=yield O(c,a))&&b.url)return d&&b.client_secret_enc&&(d.ca=b.client_secret_enc,c.g.B(d)),b.state&&(c.g.i("login_state",b.state)||(b.state=c.j())),
b.logout&&c.g.i("logout_url",b.logout),window.location.href=b.url.concat("&state=".concat(encodeURIComponent(b.state))),"redirect";return b&&b.error?"["+b.error+"] "+b.error_description:"Unknown error occured when doing authorization."})};k.ka=function(){return v(function*(){})};k.V=function(){return v(function*(){})};k.ba=function(){return v(function*(){})};k.Z=function(){return v(function*(){})};k.ja=function(){return v(function*(){})};k.pa=function(){return v(function*(){})};
k.ta=function(c){return new P(c,this)};k.Y=function(){return v(function*(){})};k.Ba=function(){};k.sa=function(c){return new Q(c,this)};function R(c){return v(function*(){return{xa:c.status,ga:yield c.text()}})}function S(c,e,a,b,d){return v(function*(){var f={L:e,fa:a};T(d,f);f=yield M(c,f);var h=yield R(f);if(b&&f.status!=b)throw Error(JSON.stringify(h));return h})}function U(c,e,a){return v(function*(){return(yield S(c,e,"GET",200,a)).ga})}
function T(c,e){c.ia&&(e.ia=c.ia);c.ha&&(e.ha=c.ha);c.A&&(e.A=c.A)}
function O(c,e){return v(function*(){if(!e)throw Error("Options are not specified when auth onedrive.");var a=new FormData;a.append("drive_type",c.j());e.clientId&&a.append("client_id",e.clientId);e.Ja&&a.append("redirect_uri",e.Ja);e.ya&&a.append("client_secret",e.ya);e.code?a.append("code",e.code):e.ra?a.append("refresh_token",e.ra):e.Aa&&a.append("need_code",e.Aa);a=yield fetch(c.u,{method:"POST",body:a,credentials:"include",redirect:"follow"});if(200==a.status)return yield a.json();var b=yield a.text();
throw Error(b+" ("+a.status+")");})}function N(c,e){return v(function*(){console.log("Retry to send ajax.");if(e)e.Fa=!0;else return null;var a=yield c.qa();if(a)return console.error(a),null;e.A=c.h;return yield M(c,e)})}k.za=function(c){return c.ok};
function aa(c){c.la=K;if("function"===typeof Object.create)c.prototype=Object.create(K.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});else{var e=function(){};e.prototype=K.prototype;c.prototype=new e;c.prototype.constructor=c}c.prototype.Ia||(c.prototype.Ia=function(){return this.constructor.la});c.prototype.T||(c.prototype.T=function(...a){return this.constructor.la.call(this,...a)});c.prototype.Ka||(c.prototype.Ka=function(a,...b){return a?this.constructor.la.prototype[a].call(this,
...b):this.constructor.la.call(this,...b)})}function V(c,e,a){aa(a);I[c]=new J(c,e,a)}var W=-1,X=-9,Y=0;
function P(c,e){this.j=e;this.m=c;this.u="";this.g=this.i=0;this.h=null;if(!this.m||!this.m.R)throw Error("fnm is not specified.");this.l=function(a){const b=this;return v(function*(){b.i=a;b.u=yield b.j.Z(b.m,a)})};this.write=function(a){const b=this;return v(function*(){var d=null;if(b.h){if(b.h instanceof ArrayBuffer){var f=b.h.byteLength;0<f?(d=new Uint8Array(f+a.byteLength),d.set(new Uint8Array(b.h),0),d.set(new Uint8Array(a),f)):d=new Uint8Array(a)}else d=0<b.h.length?new Uint8Array(b.h.concat(a)):
new Uint8Array(a);b.h=null}else d=new Uint8Array(a);var h=new Blob([d],{type:"application/octet-binary"}),m="bytes "+b.g+"-";b.g+=h.size;m+=b.g-1+"/"+b.i;var l=0,n=function(){const p=this;return v(function*(){var r=new Headers;r.append("Content-Range",m);try{var q=yield fetch(p.u,{method:"PUT",headers:r,body:h,redirect:"follow"});r="";if(e.za(q)){var u=yield p.j.ja(q);if(u==X)throw a=null,r=yield q.text(),Error(r+" ("+q.status+")");if(u!=W&&u!=Y&&u<p.g)if(q=0,q=a instanceof ArrayBuffer?a.byteLength:
a.length,q-=p.g-u,0<q){var w=a.slice(q);a=null;p.g>=p.i?yield p.write(w):(p.h=w,p.g=u)}else throw a=null,Error("Can NOT continue to upload buffer.");}else throw a=null,r=yield q.text(),Error(r+" ("+q.status+")");}catch(C){if(1>l)l++,yield z(),yield n();else throw h=a=null,C;}})}.bind(b);yield n()})};this.cancel=function(){const a=this;return v(function*(){yield a.j.pa(a.u)})};this.v=function(){return this.i}}
function Q(c,e){this.m=e;this.u=c;this.url="";this.name=null;this.B=this.i=this.h=this.size=0;this.aa=!1;this.G=16E3;c.N&&(this.G=c.N);this.o=this.j=0;this.J=function(a){const b=this;return v(function*(){if(b.aa)if(b.i&&(b.B=b.i,b.i=0),a){if(a>=b.g())throw console.log("offset:"+a+",size:"+b.g()),Error("offset can not be bigger than input size.");b.h=a}else b.h=0;else{var d=yield b.m.Y(b.u);b.aa=!0;if(d){if(b.size=d.C||0,b.url=d.s,b.name=d.I,b.o="1"==d.D?1:0,a){if(a>=b.g())throw Error("offset can not be bigger than input size.");
b.h=a}}else throw Error("Failed to prepare reader.");}})};this.U=function(){return this.G};this.l=function(){return this.h};this.g=function(){return this.size};this.v=function(){return this.h>=this.g()};this.K=function(a){const b=this;return v(function*(){a||(a=b.G);return yield b.$(a)})};this.F=function(){};this.$=function(a){const b=this;return v(function*(){if(a&&b.i)return null;if(a)b.i=a;else if(b.i)a=b.i;else throw Error("size must be specified.");if(b.B)return null;var d=b.h+a-1,f=function(){const h=
this;return v(function*(){var m=h.url,l=new Headers;10<=h.j&&(m=L(h.m),l.append("Zb-Url",h.url));h.m.Ba(l,h.u.A);l.append("Range","bytes="+h.h+"-"+d);try{var n=yield fetch(m,{method:"GET",headers:l,redirect:"follow"});if(h.B){if(h.B=0,h.i)return yield h.$()}else{h.i=0;h.j=10>h.j?1:11;if(200==n.status||206==n.status){2==h.o&&(h.o=1);var p=parseInt(n.headers.get("content-length"),10);if(p)h.h+=p;else{var r=n.headers.get("content-range");if(r){var q=r.indexOf("-");if(0>q)var u=0;else{q++;var w=r.indexOf("/",
q);u=w<=q?0:parseInt(r.slice(q,w),10)}}else u=0;h.h=u?u+1:d+1}200==n.status&&h.h<h.g()?h.h=h.g():h.h>h.g()&&(h.h=h.g());return yield n.arrayBuffer()}if(401==n.status&&1==h.o){console.log("Retry auth.");h.o=2;var C=yield h.m.qa();if(C)console.error(C);else return h.u.A&&delete h.u.A,yield f()}else{var ba=yield n.text();throw Error(ba+" ("+n.status+")");}}}catch(ca){if(0==h.j&&L(h.m))return h.j=10,yield f();if(1==h.j||11==h.j)return h.j++,yield z(),yield f();throw ca;}})}.bind(b);return yield f()})}}
;V("onedrive","Microsoft OneDrive",function(c,e){this.T(c,e);this.j=function(){return"onedrive"};this.ka=function(a){const b=this;return v(function*(){var d="/me/drive/root/children";if(a){if(a.P){d=function(m){const l=this;return v(function*(){var n={S:""};T(a,n);n=yield l.i(n,m);var p=[];n&&p.push(n);return p})}.bind(b);if(a.O){var f={S:a.O};T(a,f);if(f=yield b.i(f))return yield d(f.Da.concat("/").concat(f.I).concat("/").concat(a.P))}else return yield d("/drive/root:/".concat(a.P));return null}a.O&&
(d="/me/drive/items/"+a.O+"/children")}d=yield U(b,d.concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),a);var h=[];d&&JSON.parse(d).value.forEach(function(m){h.push(this.X(m))},b);return h})};this.V=function(a){const b=this;return v(function*(){return yield b.i(a)})};this.ba=function(a){const b=this;return v(function*(){var d="/me/drive/items/".concat(a.W);yield S(b,d,"DELETE",204,a);return 0})};this.Z=function(a){const b=this;return v(function*(){var d={L:"/me",
fa:"POST",A:a.A,oa:new Headers({"Content-Type":"application/json;charset=UTF-8","Cache-Control":"no-cache",Pragma:"no-cache"})};d.L=a.H?"/me/drive/items/"+a.H+":/":d.L+"/drive/root:/";d.L+=a.R;d.L+=":/createUploadSession";d.va=JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"replace",name:a.R}});d=yield M(b,d);var f=yield R(d),h="";d.ok&&(h=JSON.parse(f.ga).uploadUrl);return h})};this.ja=function(a){return v(function*(){if(0<=[200,201].indexOf(a.status))return W;if(0>[202].indexOf(a.status))return X;
var b=yield a.text();if((b=JSON.parse(b).nextExpectedRanges)&&b.length){var d=b[0].indexOf("-");if(0<d)return parseInt(b[0].substring(0,d),10)}return Y})};this.pa=function(a){return v(function*(){var b=yield fetch(a,{method:"DELETE",redirect:"follow"});if(!b.ok)throw(yield b.text())+" ("+b.status+")";})};this.Y=function(a){const b=this;return v(function*(){var d="/me/drive/items/".concat(a.s),f={};a.A&&(f.A=a.A);d=yield U(b,d.concat(y({select:"name,size,@microsoft.graph.downloadUrl"},!0)),f);f=null;
d&&(d=JSON.parse(d),f={s:d["@microsoft.graph.downloadUrl"],I:d.name,C:d.size});return f})};this.l=function(){return"https://graph.microsoft.com/v1.0"};this.i=function(a,b){const d=this;return v(function*(){var f=b?b.startsWith("/me")?b:"/me".concat(b):"/me/drive/items/"+a.S;f=yield S(d,f.concat(y({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),"GET",0,a);if(200==f.xa)return d.X(JSON.parse(f.ga));if(404==f.xa&&b)return null;throw Error(JSON.stringify(f));})};this.X=function(a){var b=
{s:a.id,I:a.name,C:a.size,ea:a.lastModifiedDateTime,Da:a.parentReference.path,M:a.parentReference.id,D:"0"};a.folder?b.D="1":a.file&&(b.D="2");return b}});V("googledrive","Google Drive",function(c,e){this.T(c,e);this.j=function(){return"googledrive"};this.ka=function(a){const b=this;return v(function*(){var d=b.i("/files"),f="'"+(a.O?a.O:"root")+"' in parents";a.P&&(f=f.concat(" and name = '"+a.P+"'"));d=yield U(b,d.concat(y({fields:"files(id,name,mimeType,parents,modifiedTime,size)",q:f},!0)),a);var h=[];JSON.parse(d).files.forEach(function(m){h.push(this.X(m))},b);return h})};this.V=function(a){const b=this;return v(function*(){var d=b.i("/files/").concat(a.S);
d=yield U(b,d.concat(y({fields:"id,name,mimeType,parents,modifiedTime,size"},!0)),a);return b.X(JSON.parse(d))})};this.ba=function(a){const b=this;return v(function*(){var d=b.i("/files/").concat(a.W);yield S(b,d,"DELETE",204,a);return 0})};this.Z=function(a,b){const d=this;return v(function*(){var f={P:a.R,A:a.A};a.H&&(f.O=a.H);f=yield d.ka(f);return 0<f.length?yield d.m(a,b,f[0].s):yield d.m(a,b)})};this.ja=function(a){return v(function*(){if(0<=[200,201].indexOf(a.status))return W;if(0>[308].indexOf(a.status))return X;
var b=a.headers.get("range");if(b){var d=b.indexOf("-");if(0<d)return parseInt(b.slice(d+1),10)+1}return Y})};this.Y=function(a){const b=this;return v(function*(){var d=b.i("/files/").concat(a.s),f={S:a.s};a.A&&(f.A=a.A);if(f=yield b.V(f))f.s=b.l().concat(encodeURI(d)).concat(y({alt:"media"})),b.g.l&&(f.D="1");return f})};this.Ba=function(a,b){b?a.append("Authorization",b):a.append("Authorization",this.h?this.h:"")};this.za=function(a){return a.ok||308==a.status};this.l=function(){return"https://www.googleapis.com"};
this.m=function(a,b,d){const f=this;return v(function*(){var h={},m="POST",l="/files?uploadType=resumable";d?(m="PATCH",l="/files/"+d+"?uploadType=resumable"):(h.name=a.R,a.H&&(h.parents=[a.H]));h={L:"/upload".concat(f.i(l)),fa:m,A:a.A,oa:new Headers({"X-Upload-Content-Length":b,"X-Upload-Content-Type":"application/octet-stream","Content-Type":"application/json; charset=UTF-8"}),va:JSON.stringify(h)};h=yield M(f,h);if(h.ok)return h.headers.get("location")||"";h=yield R(h);throw Error(h.ga);})};this.i=
function(a){return"/drive/v3".concat(a)};this.X=function(a){var b={s:a.id,I:a.name,C:a.size,ea:a.modifiedTime,D:"2"};a.parents&&0<a.parents.length&&(b.M=a.parents[0]);this.v(a.mimeType)&&(b.D="1");return b};this.v=function(a){return"application/vnd.google-apps.folder"==a}});function da(c,e){this.B=e;this.G=c;this.h=null;this.i=this.size=0;this.j=null;this.u=this.m=0;this.o=1600;c.N&&(this.o=c.N);this.J=function(a){const b=this;return v(function*(){var d=yield b.B.Y(b.G);if(d)b.size=d.C||0,d=yield b.B.F(b.G.s),b.h=d,b.h.sort(function(f,h){return f.wa-h.wa}),b.$(a);else throw Error("Failed to prepare reader.");})};this.U=function(){return this.o};this.l=function(){return this.i};this.g=function(){return this.size};this.v=function(){return this.h?this.m>=this.h.length:
!0};this.K=function(a){const b=this;return v(function*(){if(!b.j){var d=yield b.B.B(b.h[b.m].s);d=CryptoJS.enc.Base64url.parse(d);b.j=B(d)}return yield b.aa(a)})};this.F=function(){this.j=this.h=null};this.$=function(a){if(a){if(a>=this.g())throw Error("offset can not be bigger than input size.");this.i=a;var b=0;for(a=0;a<this.h.length&&!(b+=this.h[a].C,this.i<b);a++)this.u=b;if(a<this.h.length)this.m=a;else throw Error("offset can not be bigger than input size.");}else this.m=this.u=this.i=0;this.j=
null};this.aa=function(a){const b=this;return v(function*(){var d=b.i-b.u,f=b.j.length-d;a?a<f&&(f=a):b.o<f&&(f=b.o);var h=new Uint8Array(b.j.slice(d,d+f));b.i+=f;b.j.length==d+f&&(b.j=null,b.m++,b.u=b.i);return h.buffer})}}
function ea(c,e){this.g=e;this.h=c;this.data={s:"",I:"",C:0,M:"",D:"2"};this.j=this.i=0;this.l=function(a){const b=this;return v(function*(){b.i=a;b.data.I=b.h.R;b.h.H&&(b.data.M=b.h.H);b.data.s=yield b.g.Z(b.h,a)})};this.write=function(a){const b=this;return v(function*(){var d=Array.isArray(a)?new CryptoJS.lib.WordArray.init(new Uint8Array(a)):new CryptoJS.lib.WordArray.init(a);b.data.C+=d.sigBytes;var f=d.toString(CryptoJS.enc.Base64url);b.j++;yield b.g.saveData(b.data.s,b.j,d.sigBytes,f);b.data.C>=
b.i&&(yield b.g.G(b.data))})};this.cancel=function(){const a=this;return v(function*(){yield a.g.ba({W:a.data.s})})};this.v=function(){return this.i}}
V("idxdb","Loacal Indexed DB",function(c,e){this.T(c,e);this.j=function(){return"idxdb"};this.qa=function(){return new Promise(function(a){this.Ha(a)})};this.ka=function(a){const b=this;return v(function*(){return yield b.v(void 0,a.O,a.P)})};this.V=function(a){const b=this;return v(function*(){var d=yield b.v(a.S);return d&&0<d.length?d[0]:null})};this.ba=function(a){const b=this;return v(function*(){function d(m){var l;for(l=0;l<f.length;l++)f[l].s==m?f[l].na=!0:f[l].M==m&&("1"==f[l].D?d(f[l].s):
f[l].na=!0)}var f=[],h=0;yield b.i(function(m){m.getAll().onsuccess=function(l){l.target.result.forEach(function(n){f.push({s:n.key,I:"",M:n.pid})})}});d(a.W);yield b.i(function(m){f.forEach(function(l){l.na&&m.delete(l.s)})});yield b.m(function(m){var l=[];f.forEach(function(n){n.na&&"2"==n.D&&l.push(n.s)});0>l.indexOf(a.W)&&l.push(a.W);m.getAllKeys().onsuccess=function(n){n.target.result.forEach(function(p){var r=p.indexOf(":");0<=l.indexOf(p.substring(0,r))&&(m.delete(p),h+=parseInt(p.substring(p.indexOf("_",
r+1)+1),10))})}});return h})};this.ta=function(a){return new ea(a,this)};this.Z=function(a){const b=this;return v(function*(){var d="";a.H&&(d=a.H);return yield b.J(d)})};this.ja=function(){return v(function*(){return Y})};this.pa=function(){return v(function*(){})};this.sa=function(a){return new da(a,this)};this.Y=function(a){const b=this;return v(function*(){return yield b.V({S:a.s})})};this.l=function(){return""};this.G=function(a){const b=this;return v(function*(){a.ea=b.K();var d={key:a.s,name:a.I,
size:a.C,tms:a.ea,type:a.D};a.M&&(d.pid=a.M);yield b.i(function(f){f.put(d)})})};this.saveData=function(a,b,d,f){const h=this;return v(function*(){yield h.m(function(m){m.put({key:a+":"+b+"_"+d,data:f})})})};this.F=function(a){const b=this;return v(function*(){var d=[];yield b.m(function(f){f.getAllKeys().onsuccess=function(h){h.target.result.forEach(function(m){var l=m.indexOf(":");if(m.substring(0,l)==a){var n=m.substring(l+1);l=n.indexOf("_");d.push({s:m,wa:parseInt(n.substring(0,l),10),C:parseInt(n.substring(l+
1),10)})}})}});return d})};this.B=function(a){const b=this;return v(function*(){var d="";yield b.m(function(f){f.get(a).onsuccess=function(h){d=h.target.result.data}});return d})};this.Ha=function(a){if(window.indexedDB){var b=window.indexedDB.open("zgalocaldb");b.onerror=function(){if(a)a("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");}.bind(this);b.onupgradeneeded=function(d){d=d.target.result;d.createObjectStore("items",
{keyPath:"key"});d.createObjectStore("datas",{keyPath:"key"})}.bind(this);b.onsuccess=function(d){d.target.result.close();a&&a()}.bind(this)}else if(a)a("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");};this.i=function(a){return new Promise(function(b){window.indexedDB.open("zgalocaldb").onsuccess=function(d){var f=d.target.result;d=f.transaction("items","readwrite");d.oncomplete=function(){f.close();b()}.bind(this);
d=d.objectStore("items");a&&a(d)}.bind(this)})};this.m=function(a){return new Promise(function(b){window.indexedDB.open("zgalocaldb").onsuccess=function(d){var f=d.target.result;d=f.transaction("datas","readwrite");d.oncomplete=function(){f.close();b()}.bind(this);d=d.objectStore("datas");a&&a(d)}.bind(this)}.bind(this))};this.v=function(a,b,d){const f=this;return v(function*(){var h=[];yield f.i(function(m){m.getAll().onsuccess=function(l){l.target.result.forEach(function(n){var p=!0;a&&(p=a==n.key);
p&&b&&(p=b==n.pid);p&&d&&(p=d==n.name);p&&h.push({s:n.key,I:n.name,C:n.size,ea:n.tms,D:n.type,M:n.pid})})}});return h})};this.K=function(){var a;a||(a=new Date);var b=[],d=[];b.push(a.getFullYear());b.push(a.getMonth()+1);b.push(a.getDate());d.push("0".concat(a.getHours()).slice(-2));d.push("0".concat(a.getMinutes()).slice(-2));d.push("0".concat(a.getSeconds()).slice(-2));return b.join("-")+" "+d.join(":")};this.J=function(a){const b=this;return v(function*(){var d=-1;yield b.i(function(f){f.getAllKeys().onsuccess=
function(h){h.target.result.forEach(function(m){var l=m.indexOf("_");a&&0<l?m.substring(l+1)==a&&(l=parseInt(m.substring(0,l),10),l>d&&(d=l)):!a&&0>l&&(l=parseInt(m,10),l>d&&(d=l))})}});d++;return a?d+"_"+a:d.toString()})}});function fa(c,e,a){this.h=this.g=null;this.u=c;this.i=1;this.v=e;this.j=a;this.l=0;this.m=function(){this.j({type:0,wtype:this.i,size:this.g.g()});var b=new G({Ca:1==this.i,da:this.u,Ea:this.g,Ga:this.h}),d=function(){var h={type:1,wtype:this.i,begin:this.l,spd:b.j(),posn:this.g.l(),size:this.g.g()};this.j(h);return this.v()?!1:!0}.bind(this),f=function(h,m){var l={type:2,wtype:this.i,begin:this.l,posn:this.g.l(),size:this.h.v()};h?l.errr=h.message||h.La:m?this.h.o&&(l.blob=this.h.o()):l.type=3;this.j(l)}.bind(this);
this.l=Date.now();b.start(0,d).then(function(h){f(void 0,h)}).catch(function(h){f(h)})};this.o=function(b,d){this.i=1;this.g=b.sa({s:d,N:16E5});this.h=new D;this.m()};this.B=function(b,d,f,h){this.i=2;this.g=new E({ma:f,N:16E5});this.h=b.ta({R:d,H:h});this.m()}};window=self;self.g=!1;function Z(c,e){return new fa(c,function(){return self.g},function(a){2==a.type&&(a.gtoken=e.h?e.h:"");self.postMessage(a)})}
function ha(c){var e=c.type,a=c.cominf,b={iv:CryptoJS.enc.Base64url.parse(a.iv),key:CryptoJS.enc.Base64url.parse(a.key)};self.postMessage({type:0,wtype:e,size:0});var d=new H;d.G(function(f){f&&console.error("IndexedDB is not supported in your browser settings.");if(f=I[a.drvid])switch(f=new f.g(d,"https://zgayard.f5.si/grantauth.php"),f.h=a.gtoken,e){case 1:Z(b,f).o(f,c.downinf.targetId);break;case 2:var h=c.upinf;Z(b,f).B(f,h.fname,h.file,h.ptid)}else self.postMessage({type:2,wtype:e,size:0,errr:"Drive's name is invalid."})})}
self.addEventListener("message",function(c){c=c.data;switch(c.type){case 1:case 2:ha(c);break;default:self.g=!0}});
