self.importScripts("vendor/crypto-js.js");function t(b){if(!b)return null;var d=b.charAt(0);if("?"==d||"#"==d)b=b.substring(1);var c={};b.split("&").forEach(function(a){var e=a.indexOf("=");0>e?c[decodeURIComponent(a)]="":c[decodeURIComponent(a.substring(0,e))]=decodeURIComponent(a.substring(e+1))});return c}function u(b,d){var c=[],a;for(a in b)d?c.push(a.concat("=").concat(b[a])):c.push(encodeURIComponent(a).concat("=").concat(encodeURIComponent(b[a])));return 0<c.length?"?".concat(c.join("&")):""};function v(b){var d=CryptoJS.MD5(b);b=CryptoJS.kdf.OpenSSL.execute(b,8,4,d);b.iv.clamp();b.key.clamp();return b}function w(b){var d=Array(b.sigBytes);b=b.words;for(var c=0,a=0;a<b.length;a++){for(var e=b[a],h=c+4-1;h>=c;h--)h<d.length&&(d[h]=e&255),e>>=8;c+=4;if(c>=d.length)break}return d}
function x(){this.h=0;this.g=null;this.u=function(b,d){this.h=b;d&&d()};this.write=function(b,d){Array.isArray(b)?this.g=this.g?this.g.concat(b):b.concat():(this.g||(this.g=[]),this.g.push(b));d&&d()};this.cancel=function(b){b&&b(!1,!0)};this.i=function(){if(this.g&&0<this.g.length&&(this.g[0]instanceof ArrayBuffer||this.g[0]instanceof Uint8Array)){for(var b=0,d=0;d<this.g.length;d++)b+=this.g[d].byteLength;b=new Uint8Array(b);var c=0;for(d=0;d<this.g.length;++d){var a=this.g[d];a instanceof ArrayBuffer&&
(a=new Uint8Array(a));b.set(a,c);c+=a.byteLength}return b}return this.g};this.o=function(){var b=this.i();b instanceof Uint8Array||(b=new Uint8Array(b));return new Blob([b],{type:"application/octet-binary"})};this.download=function(b){var d=this.o();if(window.navigator.msSaveBlob)window.navigator.msSaveBlob(d,b);else throw Error("Element for download is not specified.");};this.A=function(){return this.h}}
function y(b){this.j=null;if(b._blob)if(b._blob instanceof Blob)this.j=b._blob;else throw Error("blob is not a Blob.");else throw Error("blob must be specified.");this.u=1600;b.M&&(this.u=b.M);this.g=0;this.o=this.i=null;this.I=function(d,c){if(d){if(d>=this.h())throw Error("offset can not be bigger than input size.");this.g=d}this.i=new FileReader;this.i.onload=function(a){a=a.target.result;this.o&&this.o(a,this)}.bind(this);c&&c()};this.s=function(){return this.g};this.h=function(){return this.j.size};
this.C=function(){return this.g>=this.h()};this.l=function(d){if(1!=this.i.readyState){var c=this.g;this.g=d?this.g+d:this.g+this.u;this.i.readAsArrayBuffer(this.j.slice(c,this.g))}};this.ba=function(){this.j=this.i=null}}
function z(b){if(!b.fa)if(this.getSuperClass&&"Readable"==this.getSuperClass().name)this.super(void 0),this.h=1;else throw Error("writer must be specified in no stream mode.");this.s=this.B=null;this.u=!0;this.g=null;this.l=b.fa;this.iv=this.key=null;this.i=0;this.o=null;this.A=this.j=0;this.speed="0B/s";b.ha&&(this.u=!1);if(b.ea)this.g=b.ea;else throw Error("reader must be specified.");if(b.T){var d=null;d="string"==typeof b.T?v(b.T):b.T;this.key=d.key;this.iv=d.iv}else throw Error("keycfg must be specified.");
this.start=function(c){if(c){if(this.u)throw Error("Can NOT set offset for encryption.");this.i=c;c-=c%16+16;0>c&&(c=0)}this.g.o=this.F.bind(this);this.g.I(c,function(){var a=16*Math.ceil((this.g.h()+1)/16);this.h||!this.l?this.C():this.l.u(a,this.C.bind(this))}.bind(this))};this.I=function(){if(Date.now()>this.j){var c=1E3*(this.g.s()-this.A)/(Date.now()-this.j+1E3);if(c)if(1024>c)var a="B";else 1048576>c?(a="KB",c=Math.round(c/102.4)/10):1073741824>c?(a="MB",c=Math.round(c/104857.6)/10):(a="GB",
c=Math.round(c/1.073741824E8)/10);else a="B",c=0;var e=c.toString();c=e.indexOf(".");var h=e.split(""),f=[];0<=c?f.push(e.slice(c)):c=h.length;for(e=0;0<c;)3==e++&&(f.unshift(","),e=1),f.unshift(h[--c]);this.speed=f.join("").concat(a)+"/s";this.j=Date.now()+1E3;this.A=this.g.s()}return this.speed};this._read=function(c){1==this.h?this.h=2:3==this.h&&(this.g.C()?this.push(null):this.g.l(c))};this.push=function(c){return this.readable?(c&&!this.L?this.superCall("push",new Uint8Array(c)):this.superCall("push",
c),!0):!1};this.C=function(){this.j=Date.now()+1E3;(this.A=this.i)?this.g.l(16):1==this.h?this.h=3:2==this.h?(this.h=3,this.push([])):this.g.l()};this.F=function(c){try{var a=new CryptoJS.lib.WordArray.init(c);if(!this.o){var e={iv:this.iv,mode:CryptoJS.mode.CBC,padding:CryptoJS.pad.Pkcs7};this.i&&(e.iv=a,a=null);this.o=this.u?CryptoJS.algo.AES.createEncryptor(this.key,e):CryptoJS.algo.AES.createDecryptor(this.key,e)}if(a){var h=w(this.o.process(a));this.g.C()&&(h=h.concat(w(this.o.finalize())));
if(this.i<this.g.s()){var f=this.i-(this.g.s()-c.byteLength);0<f&&(h=h.slice(f))}else h=null;this.h?this.push(h):h?this.l&&this.l.write(h,function(){this.g.C()?this.Z():this.B?this.B()?this.g.l():this.l.cancel(function(k,l){this.Z(k,l)}.bind(this)):this.g.l()}.bind(this)):this.g.l();h=null}else this.h?2==this.h?(this.h=3,this.push([])):this.h=3:this.g.l()}catch(k){if(this.h)throw k;this.Z(k)}};this.Z=function(c,a){this.g&&(this.g.ba(),this.g=null);this.s&&(c?this.s(c):this.s(!1,a))}};function A(){this.h=!0;this.g=null;this.l=!1;this.A=function(){var b=null;if(this.h)try{b=window.sessionStorage.getItem("login_state")}catch(d){this.h=!1,console.error(d)}return b};this.j=function(b){var d=this.A();return d&&b==d?!0:!1};this.i=function(b,d){if(this.h)try{return window.sessionStorage.setItem(b,d.toString()),!0}catch(c){this.h=!1,console.error(c)}return!1};this.s=function(){if(this.h)try{window.sessionStorage.removeItem("login_state")}catch(b){this.h=!1,console.error(b)}};this.B=function(b){if(window.indexedDB){var d=
window.indexedDB.open("zgayard1946");d.onerror=function(){if(b)b("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");};d.onupgradeneeded=function(c){c.target.result.createObjectStore("settings",{keyPath:"key"})};d.onsuccess=function(c){var a=c.target.result;c=a.transaction("settings","readwrite");c.oncomplete=function(){a.close();b&&b()};c.objectStore("settings").getAll().onsuccess=function(e){this.g={};e.target.result.forEach(function(h){this.g[h.key]=
h.value}.bind(this));this.l=(e=this.g.drive)&&this.g[e]&&this.g[e].refresh_token?!0:!1}.bind(this)}.bind(this)}else if(b)b("IndexedDB is not supported in your browser settings.");else throw Error("IndexedDB is not supported in your browser settings.");};this.u=function(){var b=this.o();return b&&(b=this.g[b])?b.refresh_token:null};this.C=function(b){if(this.g){var d=this.o();b?(this.g[d]||(this.g[d]={}),this.g[d].refresh_token=b):this.g[d]&&delete this.g[d].refresh_token}};this.o=function(){return this.g&&
this.g.drive?this.g.drive:null}};var B={};function C(b,d,c){this.D=b;this.O=d;this.g=c}function D(b,d,c){this.C=c;this.I=d;this.h=null;this.g=b;this.super||(this.super=function(){})}
function E(b,d){var c="POST",a=b.l().concat(encodeURI(d.H)),e=new XMLHttpRequest;d&&d.U&&(c=d.U);e.open(c,a,!0);d&&d.v?e.setRequestHeader("Authorization",d.v):d&&d.W?(c="Bearer",d&&d.X&&(c=d.X),e.setRequestHeader("Authorization",c+" "+d.W)):e.setRequestHeader("Authorization",b.h);if(d&&d.S)for(var h in d.S)e.setRequestHeader(h,d.S[h]);d&&d.m&&(e.onload=function(f){f=f.target;4==f.readyState&&(401==f.status&&this.g.l&&!d.ka?(console.log("Retry to send ajax."),d&&(d.ka=!0,F(this),d.v=this.h,E(this,
d))):d.m(f))}.bind(b));e.send(d.da)}function G(b){return b.h?b.h:""}
function F(b){var d=b.g.l,c={};var a=t(window.location.search);var e=t(window.location.hash);e&&(a=a?Object.assign(a,e):e);if(a&&a.token_type&&a.access_token)b.h=a.token_type+" "+a.access_token,b.g.i("access_token",b.h),a&&a.state&&b.g.j(a.state)&&b.g.s();else if(a&&a.code?c.code=a.code:d&&(c.$=b.g.u()),c.code||c.$){if(a&&a.state)if(b.g.j(a.state))b.g.s();else return;(a=H(b,c))&&a.token_type&&a.access_token&&(b.h=a.token_type+" "+a.access_token,b.g.i("access_token",b.h),d&&c.code&&a.refresh_token&&
b.g.C(a.refresh_token),a.logout&&b.g.i("logout_url",a.logout))}else d&&(c.ga=!0),(a=H(b,c))&&a.url&&(a.state&&(b.g.i("login_state",a.state)||(a.state=b.j())),a.logout&&b.g.i("logout_url",a.logout),window.location.href=a.url.concat("&state=".concat(encodeURIComponent(a.state))))}D.prototype.s=function(b,d){d&&d(!1)};function I(b){return{G:b.status,P:b.responseText}}
function J(b,d,c,a,e){d={H:d,U:"GET",m:function(h){var f=I(h),k=!1;c&&h.status!=c&&(k=!0);if(k)if(a&&a.m)a.m(f);else throw Error(JSON.stringify(f));else e(f)}.bind(b)};L(a,d);E(b,d)}function M(b,d,c,a){J(b,d,200,c,function(e){a(e.P)})}function L(b,d){b.X&&(d.X=b.X);b.W&&(d.W=b.W);b.v&&(d.v=b.v)}
function H(b,d){if(!d)throw Error("Options are not specified when auth onedrive.");var c=new FormData;c.append("drive_type",b.j());d.clientId&&c.append("client_id",d.clientId);d.ma&&c.append("redirect_uri",d.ma);d.la&&c.append("client_secret",d.la);d.code?c.append("code",d.code):d.$?c.append("refresh_token",d.$):d.ga&&c.append("need_code",d.ga);d=null;var a=new XMLHttpRequest;a.open("POST",b.I,!1);a.withCredentials=!0;a.send(c);if(4==a.readyState)if(200==a.status)d=JSON.parse(a.responseText);else throw Error(a.responseText+
" ("+a.status+")");return d}
function N(b){b.Y=D;if("function"===typeof Object.create)b.prototype=Object.create(D.prototype,{constructor:{value:b,enumerable:!1,writable:!0,configurable:!0}});else{var d=function(){};d.prototype=D.prototype;b.prototype=new d;b.prototype.constructor=b}b.prototype.getSuperClass||(b.prototype.getSuperClass=function(){return this.constructor.Y});b.prototype.super||(b.prototype.super=function(...c){return this.constructor.Y.call(this,...c)});b.prototype.superCall||(b.prototype.superCall=function(c,
...a){return c?this.constructor.Y.prototype[c].call(this,...a):this.constructor.Y.call(this,...a)})}
function O(b,d){this.l=d;this.j=b;this.s="";this.g=this.i=0;this.h=null;if(!this.j||!this.j.N)throw Error("fnm is not specified.");this.u=function(c,a){this.i=c;this.l.B(this.j,c,function(e,h){if(e)this.s=e,a&&a(h);else throw console.error(h),Error(JSON.stringify(h));}.bind(this))};this.write=function(c,a){var e=null;if(this.h){if(this.h instanceof ArrayBuffer){var h=this.h.byteLength;0<h?(e=new Uint8Array(h+c.byteLength),e.set(new Uint8Array(this.h),0),e.set(new Uint8Array(c),h)):e=new Uint8Array(c)}else e=
0<this.h.length?new Uint8Array(this.h.concat(c)):new Uint8Array(c);this.h=null}else e=new Uint8Array(c);var f=new Blob([e],{type:"application/octet-binary"}),k="bytes "+this.g+"-";this.g+=f.size;k+=this.g-1+"/"+this.i;var l=0,m=function(){var r=new XMLHttpRequest;r.open("PUT",this.s,!0);r.setRequestHeader("Content-Range",k);r.onload=function(n){f=null;n=n.target;if(4==n.readyState){var q=this.l.u(n);if(-9==q)throw c=null,Error(n.responseText+" ("+n.status+")");if(-1!=q&&0!=q&&q<this.g){var p=c instanceof
ArrayBuffer?c.byteLength:c.length;p-=this.g-q;if(0<p){p=c.slice(p);c=null;if(this.g>=this.i){this.write(p,a);return}this.h=p;this.g=q}else throw c=null,Error("Can NOT continue to upload buffer.");}a&&a(n.responseText)}}.bind(this);r.onerror=function(){1>l?(l++,setTimeout(function(){m()},500)):f=c=null};r.send(f)}.bind(this);m()};this.cancel=function(c){this.l.s(this.s,c)};this.A=function(){return this.i}}
function P(b,d){this.u=d;this.A=b;this.url="";this.name=null;this.F=this.i=this.g=this.size=0;this.ca=!1;this.aa=16E3;b.M&&(this.aa=b.M);this.B=this.j=0;this.o=null;this.I=function(c,a){if(this.ca){this.i&&(this.F=this.i,this.i=0);if(c){if(c>=this.h())throw console.log("offset:"+c+",size:"+this.h()),Error("offset can not be bigger than input size.");this.g=c}else this.g=0;a&&a()}else this.u.A(this.A,function(e,h){this.ca=!0;if(e){this.size=e._size;this.url=e.D;this.name=e.O;this.B="1"==e._type?1:
0;if(c){if(c>=this.h())throw Error("offset can not be bigger than input size.");this.g=c}a&&a()}else throw Error(h.P+" ("+h.G+")");}.bind(this))};this.s=function(){return this.g};this.h=function(){return this.size};this.C=function(){return this.g>=this.h()};this.l=function(c){c||(c=this.aa);this.L(c)};this.ba=function(){};this.L=function(c){if(!c||!this.i){if(c)this.i=c;else if(this.i)c=this.i;else throw Error("size must be specified.");if(!this.F){var a=this.g+c-1,e=function(){var h=new XMLHttpRequest;
10<=this.j?(h.open("GET",this.u.C,!0),h.setRequestHeader("Zb-Url",this.url)):h.open("GET",this.url,!0);this.A.v?h.setRequestHeader("Authorization",this.A.v):h.setRequestHeader("Authorization",G(this.u));h.setRequestHeader("Range","bytes="+this.g+"-"+a);h.responseType="arraybuffer";h.onload=function(f){if(this.F)this.F=0,this.i&&this.L();else if(this.i=0,f=f.target,4==f.readyState)if(this.j=10>this.j?1:11,200==f.status||206==f.status){2==this.B&&(this.B=1);var k=parseInt(f.getResponseHeader("content-length"),
10);if(k)this.g+=k;else{if(k=f.getResponseHeader("content-range")){var l=k.indexOf("-");if(0>l)k=0;else{l++;var m=k.indexOf("/",l);k=m<=l?0:parseInt(k.slice(l,m),10)}}else k=0;this.g=k?k+1:a+1}200==f.status&&this.g<this.h()?this.g=this.h():this.g>this.h()&&(this.g=this.h());this.o&&this.o(f.response,this);f.response=null}else if(401==f.status&&1==this.B)console.log("Retry auth."),this.B=2,F(this.u),this.A.v&&delete this.A.v,e();else throw Error(f.responseText+" ("+f.status+")");}.bind(this);h.onerror=
function(){if(0==this.j&&this.u.C)this.j=10,e();else if(1==this.j||11==this.j)this.j++,setTimeout(function(){e()},500)}.bind(this);h.send()}.bind(this);e()}}}};function Q(b,d,c){this.super(b,d,c);this.j=function(){return"onedrive"};this.F=function(a){var e="/me/drive/root/children";if(a){if(a._fname){var h=function(f){var k={V:"",m:function(l,m){if(a&&a.m)l?a.m(l):(l=[],m&&l.push(m),a.m(!1,l));else if(l)throw Error(JSON.stringify(l));}};L(a,k);this.i(k,f)}.bind(this);a.K?(e={V:a.K,m:function(f,k){if(f)if(a&&a.m)a.m(f);else throw Error(JSON.stringify(f));else h(k.ja.concat("/").concat(k.O).concat("/").concat(a._fname))}},L(a,e),this.i(e)):h("/drive/root:/".concat(a._fname));
return}a.K&&(e="/me/drive/items/"+a.K+"/children")}M(this,e.concat(u({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),a,function(f){if(a&&a.m){var k=[];f&&JSON.parse(f).value.forEach(function(l){k.push(this.R(l))},this);a.m(!1,k)}}.bind(this))};this.o=function(a){this.i(a)};this.B=function(a,e,h){e={H:"/me",U:"POST",v:a.v,S:{"Content-Type":"application/json;charset=UTF-8","Cache-Control":"no-cache",Pragma:"no-cache"},m:function(f){f=I(f);var k="";200<=f.G&&299>=f.G&&(k=
JSON.parse(f.P).uploadUrl);h(k,f)}.bind(this)};e.H=a.J?"/me/drive/items/"+a.J+":/":e.H+"/drive/root:/";e.H+=a.N;e.H+=":/createUploadSession";e.da=JSON.stringify({item:{"@microsoft.graph.conflictBehavior":"replace",name:a.N}});E(this,e)};this.u=function(a){if(0<=[200,201].indexOf(a.status))return-1;if(0>[202].indexOf(a.status))return-9;if((a=JSON.parse(a.responseText).nextExpectedRanges)&&a.length){var e=a[0].indexOf("-");if(0<e)return parseInt(a[0].substring(0,e),10)}return 0};this.s=function(a,e){var h=
new XMLHttpRequest;h.open("DELETE",a,!0);h.onload=function(f){f=f.target;if(4==f.readyState){var k={G:f.status,P:f.responseText};200<=f.status&&299>=f.status?e&&e(!1,k):(console.log(f.responseText+" ("+f.status+")"),e&&e(k))}}.bind(this);h.send()};this.A=function(a,e){var h="/me/drive/items/".concat(a.D),f={m:function(k,l){var m=null;l&&!k&&(l=JSON.parse(l),m={D:l["@microsoft.graph.downloadUrl"],O:l.name,_size:l.size});e(m,k)}};a.v&&(f.v=a.v);M(this,h.concat(u({select:"name,size,@microsoft.graph.downloadUrl"},
!0)),f,function(k){f.m(!1,k)})};this.l=function(){return"https://graph.microsoft.com/v1.0"};this.i=function(a,e){var h="";h=e?e.startsWith("/me")?e:"/me".concat(e):"/me/drive/items/"+a.V;J(this,h.concat(u({select:"id,name,parentReference,lastModifiedDateTime,size,folder,file"},!0)),0,a,function(f){if(a&&a.m)200==f.G?(f=this.R(JSON.parse(f.P)),a.m(!1,f)):404==f.G&&e?a.m(!1):a.m(f);else if(200!=f.G)throw Error(JSON.stringify(f));}.bind(this))};this.R=function(a){var e={D:a.id,O:a.name,_size:a.size,
ia:a.lastModifiedDateTime,ja:a.parentReference.path,_parentId:a.parentReference.id,_type:"0"};a.folder?e._type="1":a.file&&(e._type="2");return e}}N(Q);B.onedrive=new C("onedrive","Microsoft OneDrive",Q);function R(b,d,c){this.super(b,d,c);this.j=function(){return"googledrive"};this.F=function(a){var e=this.i("/files"),h="'"+(a.K?a.K:"root")+"' in parents";a._fname&&(h=h.concat(" and name = '"+a._fname+"'"));M(this,e.concat(u({fields:"files(id,name,mimeType,parents,modifiedTime,size)",q:h},!0)),a,function(f){if(a&&a.m){var k=[];JSON.parse(f).files.forEach(function(l){k.push(this.R(l))},this);a.m(!1,k)}}.bind(this))};this.o=function(a){var e=this.i("/files/").concat(a.V);M(this,e.concat(u({fields:"id,name,mimeType,parents,modifiedTime,size"},
!0)),a,function(h){a&&a.m&&(h=this.R(JSON.parse(h)),a.m(!1,h))}.bind(this))};this.B=function(a,e,h){var f=function(l){var m={},r="POST",n="/files?uploadType=resumable";l?(r="PATCH",n="/files/"+l+"?uploadType=resumable"):(m.name=a.N,a.J&&(m.parents=[a.J]));l={H:"/upload".concat(this.i(n)),U:r,v:a.v,S:{"X-Upload-Content-Length":e,"X-Upload-Content-Type":"application/octet-stream","Content-Type":"application/json; charset=UTF-8"},da:JSON.stringify(m),m:function(q){var p=I(q),K="";200<=p.G&&299>=p.G&&
(K=q.getResponseHeader("location"));h(K,p)}.bind(this)};E(this,l)}.bind(this),k={m:function(l,m){l?h("",l):0<m.length?f(m[0].D):f()},_fname:a.N,v:a.v};a.J&&(k.K=a.J);this.F(k)};this.u=function(a){if(0<=[200,201].indexOf(a.status))return-1;if(0>[308].indexOf(a.status))return-9;if(a=a.getResponseHeader("range")){var e=a.indexOf("-");if(0<e)return parseInt(a.slice(e+1),10)+1}return 0};this.A=function(a,e){var h=this.i("/files/").concat(a.D),f={V:a.D,m:function(k,l){var m=null;l&&!k&&(m=l,m.D=this.l().concat(encodeURI(h)).concat(u({alt:"media"})),
this.g.l&&(m._type="1"));e(m,k)}.bind(this)};a.v&&(f.v=a.v);this.o(f)};this.l=function(){return"https://www.googleapis.com"};this.i=function(a){return"/drive/v3".concat(a)};this.R=function(a){var e={D:a.id,O:a.name,_size:a.size,ia:a.modifiedTime,_type:"2"};a.parents&&0<a.parents.length&&(e._parentId=a.parents[0]);this.L(a.mimeType)&&(e._type="1");return e};this.L=function(a){return"application/vnd.google-apps.folder"==a}}N(R);B.googledrive=new C("googledrive","Google Drive",R);function S(b,d,c){this.g=this.h=null;this.u=b;this.i=1;this.s=d;this.l=c;this.j=function(){var a=new z({ha:1==this.i,T:this.u,ea:this.h,fa:this.g});a.B=function(){var e={_type:1,_wtype:this.i,_speed:a.I(),_pos:this.h.s(),_size:this.h.h()};this.l(e);return this.s()?!1:!0}.bind(this);a.s=function(e,h){var f={_type:2,_wtype:this.i,_size:this.g.A()};e?f._err=e.message||e.na:h?f._type=3:this.g.o&&(f._blob=this.g.o());this.l(f)}.bind(this);a.start()};this.o=function(a,e){this.i=1;this.h=new P({D:e,M:16E5},
a);this.g=new x;this.j()};this.A=function(a,e,h,f){this.i=2;this.h=new y({_blob:h,M:16E5});this.g=new O({N:e,J:f},a);this.j()}};window=self;self.g=!1;function T(b,d){return new S(b,function(){return self.g},function(c){2==c._type&&(c._token=G(d));self.postMessage(c)})}
function U(b){var d=b._type,c=b._cominf,a={iv:CryptoJS.enc.Base64url.parse(c._iv),key:CryptoJS.enc.Base64url.parse(c._key)};self.postMessage({_type:0,_wtype:d,_size:0});var e=new A;e.B(function(h){h&&console.error("IndexedDB is not supported in your browser settings.");if(h=B[c._drvnm])switch(h=new h.g(e,"https://zgayard.f5.si/grantauth.php","https://zgayard.f5.si/relay.php"),h.h=c._token,d){case 1:T(a,h).o(h,b._downinf._targetId);break;case 2:var f=b._upinf;T(a,h).A(h,f._fname,f._file,f._parentId)}else self.postMessage({_type:2,
_wtype:d,_size:0,_err:"Drive's name is invalid."})})}self.addEventListener("message",function(b){b=b.data;switch(b._type){case 1:case 2:U(b);break;default:self.g=!0}});
